/* Extensión ESL · Career Paths: Flight Attendant, libro 2.
   Las 15 unidades del libro, que siguen las fases de un vuelo (briefing,
   embarque, anuncios, servicio, aproximación, llegada y pasajeros), con su
   vocabulario y la función comunicativa de cada una. Traducciones y ejemplos
   propios; del libro solo se toman el temario y la lista de palabras. */
window.CC = window.CC || {};

CC.CP2 = {
  UNITS: [
    { id: 'cp2-01', course: 'esl', src: 'cp2', n: 1, name: 'Las fases del vuelo', icon: '🛫', hue: 205,
      blurb: 'The Stages of Flight: boarding, takeoff, cruising, descent…' },
    { id: 'cp2-02', course: 'esl', src: 'cp2', n: 2, name: 'El briefing previo al vuelo', icon: '📋', hue: 240,
      blurb: 'Preflight Briefing: flight time, turbulence, crew change…' },
    { id: 'cp2-03', course: 'esl', src: 'cp2', n: 3, name: 'Antes del vuelo (1): el embarque', icon: '🎫', hue: 280,
      blurb: 'Preflight Duties: boarding pass, carry-on item, gate check…' },
    { id: 'cp2-04', course: 'esl', src: 'cp2', n: 4, name: 'Antes del vuelo (2): comprobaciones', icon: '✅', hue: 150,
      blurb: 'Preflight Duties: safety check, head count, arm, push back…' },
    { id: 'cp2-05', course: 'esl', src: 'cp2', n: 5, name: 'Anuncios antes del vuelo', icon: '📢', hue: 20,
      blurb: 'Preflight Announcements: welcome aboard, ETD, PA system…' },
    { id: 'cp2-06', course: 'esl', src: 'cp2', n: 6, name: 'La demostración de seguridad', icon: '🦺', hue: 10,
      blurb: 'The Safety Demonstration: life jacket, mask, forward, aft…' },
    { id: 'cp2-07', course: 'esl', src: 'cp2', n: 7, name: 'En ruta (1): avisos y normas', icon: '💡', hue: 55,
      blurb: 'En Route Duties: seatbelt sign, altitude, in-flight entertainment…' },
    { id: 'cp2-08', course: 'esl', src: 'cp2', n: 8, name: 'En ruta (2): el servicio a bordo', icon: '🥤', hue: 100,
      blurb: 'En Route Duties: beverage, cart, snack, voucher…' },
    { id: 'cp2-09', course: 'esl', src: 'cp2', n: 9, name: 'La aproximación (1)', icon: '🛬', hue: 175,
      blurb: 'Approach: tray table, seatback, upright, trash…' },
    { id: 'cp2-10', course: 'esl', src: 'cp2', n: 10, name: 'La aproximación (2)', icon: '🧭', hue: 225,
      blurb: 'Approach: ETA, connecting flight, holding, headset…' },
    { id: 'cp2-11', course: 'esl', src: 'cp2', n: 11, name: 'La llegada', icon: '🏁', hue: 130,
      blurb: 'Arrival: disarm, local time, remain seated, caution…' },
    { id: 'cp2-12', course: 'esl', src: 'cp2', n: 12, name: 'Después del vuelo', icon: '🧹', hue: 70,
      blurb: 'Post-flight Duties: lost-and-found, seatback pocket, stock…' },
    { id: 'cp2-13', course: 'esl', src: 'cp2', n: 13, name: 'Entre vuelos', icon: '🏨', hue: 300,
      blurb: 'Between Flights: layover hotel, per diem, crash pad…' },
    { id: 'cp2-14', course: 'esl', src: 'cp2', n: 14, name: 'Pasajeros (1): actitudes difíciles', icon: '😤', hue: 5,
      blurb: 'Passengers: impatient, unruly, empathy, vent…' },
    { id: 'cp2-15', course: 'esl', src: 'cp2', n: 15, name: 'Pasajeros (2): necesidades especiales', icon: '♿', hue: 270,
      blurb: 'Passengers: wheelchair, infant, preboard, pax…' }
  ],

  CARDS: [
    /* ───────────── 1 · The Stages of Flight ───────────── */
    { id: 'cp2-approach', unit: 'cp2-01', type: 'def', term: 'Approach',
      q: '¿Qué significa «approach»?',
      a: 'Aproximación: la maniobra para llegar al aeropuerto de destino' },
    { id: 'cp2-arrival', unit: 'cp2-01', type: 'def', term: 'Arrival',
      q: '¿Qué significa «arrival»?',
      a: 'Llegada' },
    { id: 'cp2-boarding', unit: 'cp2-01', type: 'def', term: 'Boarding',
      q: '¿Qué significa «boarding»?',
      a: 'Embarque (abordaje)' },
    { id: 'cp2-climbing', unit: 'cp2-01', type: 'def', term: 'Climbing',
      q: '¿Qué significa «climbing»?',
      a: 'Ascenso: el avión va ganando altura' },
    { id: 'cp2-cruising', unit: 'cp2-01', type: 'def', term: 'Cruising',
      q: '¿Qué significa «cruising»?',
      a: 'Crucero: volar a una altitud estable' },
    { id: 'cp2-descent', unit: 'cp2-01', type: 'def', term: 'Descent',
      q: '¿Qué significa «descent»?',
      a: 'Descenso' },
    { id: 'cp2-disembark', unit: 'cp2-01', type: 'def', term: 'Disembark',
      q: '¿Qué significa «disembark»?',
      a: 'Desembarcar',
      note: 'Ej.: “Passengers may now disembark through the front door.”' },
    { id: 'cp2-landing', unit: 'cp2-01', type: 'def', term: 'Landing',
      q: '¿Qué significa «landing»?',
      a: 'Aterrizaje' },
    { id: 'cp2-post-flight', unit: 'cp2-01', type: 'def', term: 'Post-flight',
      q: '¿Qué significa «post-flight»?',
      a: 'Posvuelo: después del vuelo' },
    { id: 'cp2-preflight', unit: 'cp2-01', type: 'def', term: 'Preflight',
      q: '¿Qué significa «preflight»?',
      a: 'Prevuelo: antes del vuelo' },
    { id: 'cp2-takeoff', unit: 'cp2-01', type: 'def', term: 'Takeoff',
      q: '¿Qué significa «takeoff»?',
      a: 'Despegue' },
    { id: 'cp2-taxiing', unit: 'cp2-01', type: 'def', term: 'Taxiing',
      q: '¿Qué significa «taxiing»?',
      a: 'Rodaje: moverse por tierra hacia la pista o la puerta' },
    { id: 'cp2-01-order', unit: 'cp2-01', type: 'order',
      q: 'Ordena las fases del vuelo',
      steps: ['Preflight',
              'Boarding',
              'Taxiing',
              'Takeoff',
              'Climbing',
              'Cruising',
              'Descent',
              'Approach',
              'Landing',
              'Post-flight'] },
    { id: 'cp2-01-say', unit: 'cp2-01', type: 'num',
      q: 'Comentas con tu compañero qué harán al llegar a Madrid. ¿Qué frase es correcta?',
      a: 'We’re going to have dinner near the hotel.',
      options: ['We’re going to have dinner near the hotel.', 'We go to have dinner near of the hotel.', 'We are going to having dinner near the hotel.', 'We will to have dinner near the hotel.'],
      say: 'We’re going to have dinner near the hotel.',
      note: 'Para planes ya decididos: «be going to» + verbo base.' },
    { id: 'cp2-01-pairs', unit: 'cp2-01', type: 'match',
      q: 'Discussing plans: hablar de planes',
      pairs: [['What are you going to do…?', '¿Qué vas a hacer…?'],
              ['I’m planning to…', 'Tengo pensado…'],
              ['We’re meeting at…', 'Quedamos a las…'],
              ['Are you free after the flight?', '¿Estás libre después del vuelo?']] },

    /* ───────────── 2 · Preflight Briefing ───────────── */
    { id: 'cp2-anticipate', unit: 'cp2-02', type: 'def', term: 'Anticipate',
      q: '¿Qué significa «anticipate»?',
      a: 'Prever, anticipar',
      note: 'Ej.: “We anticipate some turbulence over the mountains.”' },
    { id: 'cp2-brief', unit: 'cp2-02', type: 'def', term: 'Brief',
      q: '¿Qué significa «brief»?',
      a: 'Informar: dar instrucciones antes de una tarea',
      note: 'De ahí viene «briefing»: la reunión informativa antes del vuelo.' },
    { id: 'cp2-crew-change', unit: 'cp2-02', type: 'def', term: 'Crew change',
      q: '¿Qué significa «crew change»?',
      a: 'Cambio de tripulación' },
    { id: 'cp2-flight-origination', unit: 'cp2-02', type: 'def', term: 'Flight origination',
      q: '¿Qué significa «flight origination»?',
      a: 'Origen del vuelo: el aeropuerto donde empieza' },
    { id: 'cp2-flight-time', unit: 'cp2-02', type: 'def', term: 'Flight time',
      q: '¿Qué significa «flight time»?',
      a: 'Tiempo de vuelo',
      note: 'Ej.: “Our flight time today is two hours and ten minutes.”' },
    { id: 'cp2-non-routine-operations', unit: 'cp2-02', type: 'def', term: 'Non-routine operations',
      q: '¿Qué significa «non-routine operations»?',
      a: 'Operaciones no rutinarias: situaciones fuera de lo normal' },
    { id: 'cp2-review', unit: 'cp2-02', type: 'def', term: 'Review',
      q: '¿Qué significa «review»?',
      a: 'Repasar, revisar',
      note: 'Ej.: “Let’s review the emergency procedures.”' },
    { id: 'cp2-taxi-time', unit: 'cp2-02', type: 'def', term: 'Taxi time',
      q: '¿Qué significa «taxi time»?',
      a: 'Tiempo de rodaje' },
    { id: 'cp2-turbulence', unit: 'cp2-02', type: 'def', term: 'Turbulence',
      q: '¿Qué significa «turbulence»?',
      a: 'Turbulencia' },
    { id: 'cp2-weather-conditions', unit: 'cp2-02', type: 'def', term: 'Weather conditions',
      q: '¿Qué significa «weather conditions»?',
      a: 'Condiciones meteorológicas (el tiempo)' },
    { id: 'cp2-02-say', unit: 'cp2-02', type: 'num',
      q: 'El comandante describe el tiempo en el destino. ¿Qué frase es correcta?',
      a: 'It’s cloudy and windy in Bogotá, with light rain.',
      options: ['It’s cloudy and windy in Bogotá, with light rain.', 'Is cloudy and wind in Bogotá, with rain light.', 'It’s cloud and windy in Bogotá, with light rain.', 'There is cloudy and windy in Bogotá.'],
      say: 'It’s cloudy and windy in Bogotá, with light rain.',
      note: 'Para el tiempo se usa «It’s» + adjetivo: «It’s cloudy», «It’s windy».' },
    { id: 'cp2-02-pairs', unit: 'cp2-02', type: 'match',
      q: 'Describing conditions: describir las condiciones',
      pairs: [['Light turbulence', 'Turbulencia ligera'],
              ['Clear skies', 'Cielo despejado'],
              ['Strong headwinds', 'Fuerte viento en contra'],
              ['Low visibility', 'Poca visibilidad']] },

    /* ───────────── 3 · Preflight Duties 1 ───────────── */
    { id: 'cp2-baggage', unit: 'cp2-03', type: 'def', term: 'Baggage',
      q: '¿Qué significa «baggage»?',
      a: 'Equipaje',
      note: 'Es incontable: «two pieces of baggage», nunca «two baggages».', syn: ['Luggage'] },
    { id: 'cp2-boarding-pass', unit: 'cp2-03', type: 'def', term: 'Boarding pass',
      q: '¿Qué significa «boarding pass»?',
      a: 'Pase de abordar (tarjeta de embarque)' },
    { id: 'cp2-capable', unit: 'cp2-03', type: 'def', term: 'Capable',
      q: '¿Qué significa «capable»?',
      a: 'Capaz, apto',
      note: 'Ej.: “Exit row passengers must be capable of opening the door.”' },
    { id: 'cp2-carry-on-item', unit: 'cp2-03', type: 'def', term: 'Carry-on item',
      q: '¿Qué significa «carry-on item»?',
      a: 'Bulto de mano: la maleta que va en el compartimento superior' },
    { id: 'cp2-check', unit: 'cp2-03', type: 'def', term: 'Check',
      q: '¿Qué significa «check»?',
      a: 'Revisar, comprobar; también, documentar (facturar) equipaje',
      note: 'Ej.: “I need to check this bag.”' },
    { id: 'cp2-confirm', unit: 'cp2-03', type: 'def', term: 'Confirm',
      q: '¿Qué significa «confirm»?',
      a: 'Confirmar' },
    { id: 'cp2-gate-check', unit: 'cp2-03', type: 'def', term: 'Gate check',
      q: '¿Qué significa «gate check»?',
      a: 'Documentar en la puerta: enviar a bodega un bulto de mano al embarcar',
      note: 'Ej.: “The bins are full, so we’ll have to gate check your bag.”' },
    { id: 'cp2-luggage', unit: 'cp2-03', type: 'def', term: 'Luggage',
      q: '¿Qué significa «luggage»?',
      a: 'Equipaje (maletas)',
      note: 'También incontable: «a piece of luggage».', syn: ['Baggage'] },
    { id: 'cp2-personal-item', unit: 'cp2-03', type: 'def', term: 'Personal item',
      q: '¿Qué significa «personal item»?',
      a: 'Artículo personal: bolso, mochila pequeña o laptop que va bajo el asiento' },
    { id: 'cp2-seat-assignment', unit: 'cp2-03', type: 'def', term: 'Seat assignment',
      q: '¿Qué significa «seat assignment»?',
      a: 'Asignación de asiento' },
    { id: 'cp2-stow', unit: 'cp2-03', type: 'def', term: 'Stow',
      q: '¿Qué significa «stow»?',
      a: 'Guardar, colocar en su sitio',
      note: 'Ej.: “Please stow your bag under the seat in front of you.”' },
    { id: 'cp2-03-items', unit: 'cp2-03', type: 'list',
      q: 'Personal items: caben bajo el asiento',
      items: ['A small backpack', 'A laptop bag', 'A purse'],
      lures: ['A large rolling suitcase', 'A guitar case'] },
    { id: 'cp2-03-say', unit: 'cp2-03', type: 'num',
      q: 'Un pasajero mayor busca su asiento. ¿Cómo le ofreces ayuda?',
      a: 'May I see your boarding pass? I’ll show you to your seat.',
      options: ['May I see your boarding pass? I’ll show you to your seat.', 'Can I to see your boarding pass? I show you the seat.', 'Give me your boarding pass, I bring you to your seat.', 'Show me the boarding pass and I am taking you to the seat.'],
      say: 'May I see your boarding pass? I’ll show you to your seat.',
      note: 'Tras «can», «may» o «will» va el verbo sin «to»: «May I see…?».' },
    { id: 'cp2-03-pairs', unit: 'cp2-03', type: 'match',
      q: 'Offering assistance: ayudar en el embarque',
      pairs: [['Let me help you with your bag', 'Déjeme ayudarle con su maleta'],
              ['Your seat is just over there', 'Su asiento está justo allí'],
              ['Would you like a hand?', '¿Le echo una mano?'],
              ['I’ll find a space for it', 'Le busco un sitio']] },

    /* ───────────── 4 · Preflight Duties 2 ───────────── */
    { id: 'cp2-arm', unit: 'cp2-04', type: 'def', term: 'Arm',
      q: '¿Qué significa «arm»?',
      a: 'Armar: dejar el tobogán de la puerta listo para desplegarse',
      note: 'Ej.: “Cabin crew, arm doors and cross-check.”' },
    { id: 'cp2-cabin-ready-notification', unit: 'cp2-04', type: 'def', term: 'Cabin ready notification',
      q: '¿Qué significa «cabin ready notification»?',
      a: 'Aviso de cabina lista (a los pilotos)' },
    { id: 'cp2-condition', unit: 'cp2-04', type: 'def', term: 'Condition',
      q: '¿Qué significa «condition»?',
      a: 'Estado, condición',
      note: 'Ej.: “Check the condition of the life vests.”' },
    { id: 'cp2-emergency-equipment', unit: 'cp2-04', type: 'def', term: 'Emergency equipment',
      q: '¿Qué significa «emergency equipment»?',
      a: 'Equipo de emergencia' },
    { id: 'cp2-notify', unit: 'cp2-04', type: 'def', term: 'Notify',
      q: '¿Qué significa «notify»?',
      a: 'Notificar, avisar' },
    { id: 'cp2-passenger-head-count', unit: 'cp2-04', type: 'def', term: 'Passenger head count',
      q: '¿Qué significa «passenger head count»?',
      a: 'Conteo de pasajeros' },
    { id: 'cp2-predeparture-service', unit: 'cp2-04', type: 'def', term: 'Predeparture service',
      q: '¿Qué significa «predeparture service»?',
      a: 'Servicio antes de la salida (bebida de bienvenida)',
      note: 'Suele ofrecerse en primera clase o en ejecutiva.' },
    { id: 'cp2-prior-to', unit: 'cp2-04', type: 'def', term: 'Prior to',
      q: '¿Qué significa «prior to»?',
      a: 'Antes de',
      note: 'Más formal que «before»: “prior to departure”.' },
    { id: 'cp2-push-back', unit: 'cp2-04', type: 'def', term: 'Push back',
      q: '¿Qué significa «push back»?',
      a: 'Push back: el remolque que saca al avión de la puerta hacia atrás' },
    { id: 'cp2-safety-check', unit: 'cp2-04', type: 'def', term: 'Safety check',
      q: '¿Qué significa «safety check»?',
      a: 'Revisión (comprobación) de seguridad' },
    { id: 'cp2-seal', unit: 'cp2-04', type: 'def', term: 'Seal',
      q: '¿Qué significa «seal»?',
      a: 'Precinto; precintar (sellar)',
      note: 'Ej.: “Check that the seal on the first-aid kit is intact.”' },
    { id: 'cp2-secure', unit: 'cp2-04', type: 'def', term: 'Secure',
      q: '¿Qué significa «secure»?',
      a: 'Asegurar, fijar: que nada se mueva',
      note: 'Ej.: “Secure the galley before takeoff.”' },
    { id: 'cp2-smoke-detector', unit: 'cp2-04', type: 'def', term: 'Smoke detector',
      q: '¿Qué significa «smoke detector»?',
      a: 'Detector de humo',
      note: 'Los baños tienen uno: está prohibido manipularlo.' },
    { id: 'cp2-04-order', unit: 'cp2-04', type: 'order',
      q: 'Ordena las tareas antes del despegue (secuencia típica)',
      steps: ['Check the emergency equipment',
              'Board the passengers',
              'Do the passenger head count',
              'Arm the doors and cross-check',
              'Secure the cabin',
              'Give the cabin ready notification'] },
    { id: 'cp2-04-say', unit: 'cp2-04', type: 'num',
      q: 'El sobrecargo pregunta si ya revisaste el equipo de emergencia. ¿Qué respondes?',
      a: 'Yes, I’ve already checked it.',
      options: ['Yes, I’ve already checked it.', 'Yes, I already have check it.', 'Yes, I checked it already yet.', 'Yes, I have already check.'],
      say: 'Yes, I’ve already checked it.',
      note: 'Para tareas recién terminadas: «have» + participio (checked, done, finished).' },
    { id: 'cp2-04-pairs', unit: 'cp2-04', type: 'match',
      q: 'Talking about completion: tareas terminadas',
      pairs: [['I’ve finished…', 'Ya terminé…'],
              ['It’s all done', 'Ya está todo hecho'],
              ['Not yet', 'Todavía no'],
              ['I’m almost done', 'Casi termino']] },

    /* ───────────── 5 · Preflight Announcements ───────────── */
    { id: 'cp2-aboard', unit: 'cp2-05', type: 'def', term: 'Aboard',
      q: '¿Qué significa «aboard»?',
      a: 'A bordo',
      note: 'Ej.: “Welcome aboard!”' },
    { id: 'cp2-allow', unit: 'cp2-05', type: 'def', term: 'Allow',
      q: '¿Qué significa «allow»?',
      a: 'Permitir',
      note: 'Ej.: “Smoking is not allowed on this flight.”' },
    { id: 'cp2-beneath', unit: 'cp2-05', type: 'def', term: 'Beneath',
      q: '¿Qué significa «beneath»?',
      a: 'Debajo de',
      note: 'Más formal que «under»: “Place your bag beneath the seat in front of you.”' },
    { id: 'cp2-deliver', unit: 'cp2-05', type: 'def', term: 'Deliver',
      q: '¿Qué significa «deliver»?',
      a: 'Entregar (llevar algo a alguien)' },
    { id: 'cp2-depart', unit: 'cp2-05', type: 'def', term: 'Depart',
      q: '¿Qué significa «depart»?',
      a: 'Salir, partir' },
    { id: 'cp2-electronic-device', unit: 'cp2-05', type: 'def', term: 'Electronic device',
      q: '¿Qué significa «electronic device»?',
      a: 'Dispositivo electrónico' },
    { id: 'cp2-estimated-time-of-departure-etd', unit: 'cp2-05', type: 'def', term: 'Estimated time of departure (ETD)',
      q: '¿Qué significa «estimated time of departure (ETD)»?',
      a: 'Hora estimada de salida',
      say: 'Estimated time of departure' },
    { id: 'cp2-flight-number', unit: 'cp2-05', type: 'def', term: 'Flight number',
      q: '¿Qué significa «flight number»?',
      a: 'Número de vuelo' },
    { id: 'cp2-full', unit: 'cp2-05', type: 'def', term: 'Full',
      q: '¿Qué significa «full»?',
      a: 'Lleno, completo',
      note: 'Ej.: “Today’s flight is completely full.”' },
    { id: 'cp2-locate', unit: 'cp2-05', type: 'def', term: 'Locate',
      q: '¿Qué significa «locate»?',
      a: 'Localizar, ubicar',
      note: 'Ej.: “Please take a moment to locate the exit nearest you.”' },
    { id: 'cp2-pa-system', unit: 'cp2-05', type: 'def', term: 'PA system',
      q: '¿Qué significa «PA system»?',
      a: 'Megafonía: el sistema de anuncios a bordo',
      note: '«PA» viene de «public address».', say: 'P A system' },
    { id: 'cp2-place', unit: 'cp2-05', type: 'def', term: 'Place',
      q: '¿Qué significa «place»?',
      a: 'Colocar, poner',
      note: 'Ej.: “Please place your bags in the overhead bins.”' },
    { id: 'cp2-proceed', unit: 'cp2-05', type: 'def', term: 'Proceed',
      q: '¿Qué significa «proceed»?',
      a: 'Dirigirse a; continuar',
      note: 'Ej.: “Please proceed to your seats.”' },
    { id: 'cp2-smoking', unit: 'cp2-05', type: 'def', term: 'Smoking',
      q: '¿Qué significa «smoking»?',
      a: 'Fumar (el hecho de fumar)',
      note: 'Ej.: “This is a non-smoking flight.”' },
    { id: 'cp2-until', unit: 'cp2-05', type: 'def', term: 'Until',
      q: '¿Qué significa «until»?',
      a: 'Hasta (que)',
      note: 'Ej.: “Please remain seated until the seatbelt sign is off.”' },
    { id: 'cp2-welcome', unit: 'cp2-05', type: 'def', term: 'Welcome',
      q: '¿Qué significa «welcome»?',
      a: 'Bienvenido(s); dar la bienvenida' },
    { id: 'cp2-05-say', unit: 'cp2-05', type: 'num',
      q: 'Pides a los pasajeros que pongan el teléfono en modo avión. ¿Cuál es el anuncio más cortés?',
      a: 'We kindly ask you to switch your phones to flight mode.',
      options: ['We kindly ask you to switch your phones to flight mode.', 'Phones in flight mode. Now.', 'You have to put flight mode, please.', 'We order you to switch to flight mode.'],
      say: 'We kindly ask you to switch your phones to flight mode.',
      note: 'Fórmulas corteses: «We kindly ask you to…», «Please make sure…», «We would appreciate it if…».' },
    { id: 'cp2-05-pairs', unit: 'cp2-05', type: 'match',
      q: 'Polite instructions: instrucciones corteses',
      pairs: [['Please make sure…', 'Por favor, asegúrense de…'],
              ['We kindly ask you to…', 'Les rogamos que…'],
              ['Please take a moment to…', 'Tómense un momento para…'],
              ['We would appreciate it if…', 'Les agradeceríamos que…']] },

    /* ───────────── 6 · The Safety Demonstration ───────────── */
    { id: 'cp2-aft', unit: 'cp2-06', type: 'def', term: 'Aft',
      q: '¿Qué significa «aft»?',
      a: 'Atrás: en la parte trasera del avión',
      note: 'Ej.: “There are two exits in the aft cabin.”' },
    { id: 'cp2-briefing-card', unit: 'cp2-06', type: 'def', term: 'Briefing card',
      q: '¿Qué significa «briefing card»?',
      a: 'Tarjeta de instrucciones de seguridad' },
    { id: 'cp2-cabin-pressure', unit: 'cp2-06', type: 'def', term: 'Cabin pressure',
      q: '¿Qué significa «cabin pressure»?',
      a: 'Presión de la cabina',
      note: 'Ej.: “In the event of a loss of cabin pressure, oxygen masks will drop.”' },
    { id: 'cp2-fasten', unit: 'cp2-06', type: 'def', term: 'Fasten',
      q: '¿Qué significa «fasten»?',
      a: 'Abrochar' },
    { id: 'cp2-forward', unit: 'cp2-06', type: 'def', term: 'Forward',
      q: '¿Qué significa «forward»?',
      a: 'Adelante: en la parte delantera del avión',
      note: 'Lo contrario de «aft».' },
    { id: 'cp2-life-jacket', unit: 'cp2-06', type: 'def', term: 'Life jacket',
      q: '¿Qué significa «life jacket»?',
      a: 'Chaleco salvavidas',
      note: 'También se dice «life vest».' },
    { id: 'cp2-loss', unit: 'cp2-06', type: 'def', term: 'Loss',
      q: '¿Qué significa «loss»?',
      a: 'Pérdida' },
    { id: 'cp2-mask', unit: 'cp2-06', type: 'def', term: 'Mask',
      q: '¿Qué significa «mask»?',
      a: 'Máscara (mascarilla de oxígeno)' },
    { id: 'cp2-safety-demonstration', unit: 'cp2-06', type: 'def', term: 'Safety demonstration',
      q: '¿Qué significa «safety demonstration»?',
      a: 'Demostración de seguridad' },
    { id: 'cp2-seatbelt', unit: 'cp2-06', type: 'def', term: 'Seatbelt',
      q: '¿Qué significa «seatbelt»?',
      a: 'Cinturón de seguridad' },
    { id: 'cp2-strap', unit: 'cp2-06', type: 'def', term: 'Strap',
      q: '¿Qué significa «strap»?',
      a: 'Correa, cinta' },
    { id: 'cp2-tighten', unit: 'cp2-06', type: 'def', term: 'Tighten',
      q: '¿Qué significa «tighten»?',
      a: 'Ajustar, apretar' },
    { id: 'cp2-water-landing', unit: 'cp2-06', type: 'def', term: 'Water landing',
      q: '¿Qué significa «water landing»?',
      a: 'Amerizaje: aterrizaje en el agua',
      note: 'También se dice «ditching».' },
    { id: 'cp2-window-exit', unit: 'cp2-06', type: 'def', term: 'Window exit',
      q: '¿Qué significa «window exit»?',
      a: 'Salida de ventana (sobre el ala)' },
    { id: 'cp2-06-say', unit: 'cp2-06', type: 'num',
      q: 'Vas a empezar la demostración y los pasajeros siguen hablando. ¿Qué dices por megafonía?',
      a: 'Ladies and gentlemen, may I have your attention, please?',
      options: ['Ladies and gentlemen, may I have your attention, please?', 'Ladies and gentlemen, pay me attention, please.', 'Ladies and gentlemen, give attention, please.', 'Ladies and gentlemen, attention to me, please.'],
      say: 'Ladies and gentlemen, may I have your attention, please?',
      note: '«Prestar atención» es «pay attention», pero para pedirla se dice «May I have your attention?».' },
    { id: 'cp2-06-pairs', unit: 'cp2-06', type: 'match',
      q: 'Getting attention: llamar la atención',
      pairs: [['May I have your attention, please?', '¿Me prestan atención, por favor?'],
              ['Excuse me, sir', 'Disculpe, señor'],
              ['Please direct your attention to…', 'Por favor, dirijan su atención a…'],
              ['Even if you fly often…', 'Aunque viajen con frecuencia…']] },

    /* ───────────── 7 · En Route Duties 1 ───────────── */
    { id: 'cp2-after-takeoff-briefing', unit: 'cp2-07', type: 'def', term: 'After-takeoff briefing',
      q: '¿Qué significa «after-takeoff briefing»?',
      a: 'Anuncio después del despegue' },
    { id: 'cp2-altitude', unit: 'cp2-07', type: 'def', term: 'Altitude',
      q: '¿Qué significa «altitude»?',
      a: 'Altitud (altura de vuelo)' },
    { id: 'cp2-approved', unit: 'cp2-07', type: 'def', term: 'Approved',
      q: '¿Qué significa «approved»?',
      a: 'Aprobado, autorizado',
      note: 'Ej.: “an approved electronic device”.' },
    { id: 'cp2-cell-phone', unit: 'cp2-07', type: 'def', term: 'Cell phone',
      q: '¿Qué significa «cell phone»?',
      a: 'Teléfono celular (móvil)' },
    { id: 'cp2-en-route', unit: 'cp2-07', type: 'def', term: 'En route',
      q: '¿Qué significa «en route»?',
      a: 'En ruta: durante el viaje',
      note: 'Viene del francés; se pronuncia “on rut”.' },
    { id: 'cp2-illuminate', unit: 'cp2-07', type: 'def', term: 'Illuminate',
      q: '¿Qué significa «illuminate»?',
      a: 'Iluminar, encender (una señal)',
      note: 'Ej.: “The seatbelt sign is illuminated.”' },
    { id: 'cp2-in-flight', unit: 'cp2-07', type: 'def', term: 'In-flight',
      q: '¿Qué significa «in-flight»?',
      a: 'Durante el vuelo, a bordo' },
    { id: 'cp2-in-flight-entertainment', unit: 'cp2-07', type: 'def', term: 'In-flight entertainment',
      q: '¿Qué significa «in-flight entertainment»?',
      a: 'Entretenimiento a bordo: películas, música, juegos…' },
    { id: 'cp2-prohibit', unit: 'cp2-07', type: 'def', term: 'Prohibit',
      q: '¿Qué significa «prohibit»?',
      a: 'Prohibir' },
    { id: 'cp2-rewards-program', unit: 'cp2-07', type: 'def', term: 'Rewards program',
      q: '¿Qué significa «rewards program»?',
      a: 'Programa de viajero frecuente (de recompensas)' },
    { id: 'cp2-seatbelt-sign', unit: 'cp2-07', type: 'def', term: 'Seatbelt sign',
      q: '¿Qué significa «seatbelt sign»?',
      a: 'Señal luminosa del cinturón de seguridad' },
    { id: 'cp2-seated', unit: 'cp2-07', type: 'def', term: 'Seated',
      q: '¿Qué significa «seated»?',
      a: 'Sentado',
      note: 'Ej.: “Please remain seated.”' },
    { id: 'cp2-07-say', unit: 'cp2-07', type: 'num',
      q: 'Recuerdas a los pasajeros que mantengan el cinturón abrochado. ¿Qué dices?',
      a: 'Just a reminder: please keep your seatbelt fastened while seated.',
      options: ['Just a reminder: please keep your seatbelt fastened while seated.', 'Remember you to keep the seatbelt fastened.', 'I remind you keep fasten the seatbelt.', 'Don’t forget of fasten your seatbelt.'],
      say: 'Just a reminder: please keep your seatbelt fastened while seated.',
      note: '«Remember to…» o «Don’t forget to…», sin «of». Y «remind» lleva persona: «I remind you to…».' },
    { id: 'cp2-07-pairs', unit: 'cp2-07', type: 'match',
      q: 'Giving a reminder: recordatorios',
      pairs: [['Just a reminder…', 'Solo un recordatorio…'],
              ['Please remember to…', 'Recuerden…'],
              ['Don’t forget to…', 'No olviden…'],
              ['We’d like to remind you that…', 'Les recordamos que…']] },

    /* ───────────── 8 · En Route Duties 2 ───────────── */
    { id: 'cp2-beverage', unit: 'cp2-08', type: 'def', term: 'Beverage',
      q: '¿Qué significa «beverage»?',
      a: 'Bebida',
      note: 'Más formal que «drink»: “beverage service”.' },
    { id: 'cp2-cart', unit: 'cp2-08', type: 'def', term: 'Cart',
      q: '¿Qué significa «cart»?',
      a: 'Carrito (de servicio)',
      note: 'En inglés británico, «trolley».' },
    { id: 'cp2-cash', unit: 'cp2-08', type: 'def', term: 'Cash',
      q: '¿Qué significa «cash»?',
      a: 'Efectivo (dinero en efectivo)' },
    { id: 'cp2-catering', unit: 'cp2-08', type: 'def', term: 'Catering',
      q: '¿Qué significa «catering»?',
      a: 'Catering: la empresa que suministra la comida a bordo' },
    { id: 'cp2-complimentary', unit: 'cp2-08', type: 'def', term: 'Complimentary',
      q: '¿Qué significa «complimentary»?',
      a: 'Gratuito, de cortesía' },
    { id: 'cp2-correct-change', unit: 'cp2-08', type: 'def', term: 'Correct change',
      q: '¿Qué significa «correct change»?',
      a: 'Importe exacto (cambio justo)',
      note: 'Ej.: “Please have the correct change ready.”' },
    { id: 'cp2-credit-card', unit: 'cp2-08', type: 'def', term: 'Credit card',
      q: '¿Qué significa «credit card»?',
      a: 'Tarjeta de crédito' },
    { id: 'cp2-liquor', unit: 'cp2-08', type: 'def', term: 'Liquor',
      q: '¿Qué significa «liquor»?',
      a: 'Licor (bebida alcohólica fuerte)' },
    { id: 'cp2-payment', unit: 'cp2-08', type: 'def', term: 'Payment',
      q: '¿Qué significa «payment»?',
      a: 'Pago' },
    { id: 'cp2-snack', unit: 'cp2-08', type: 'def', term: 'Snack',
      q: '¿Qué significa «snack»?',
      a: 'Refrigerio (bocadillo, tentempié)' },
    { id: 'cp2-soft-drink', unit: 'cp2-08', type: 'def', term: 'Soft drink',
      q: '¿Qué significa «soft drink»?',
      a: 'Refresco (gaseosa)' },
    { id: 'cp2-voucher', unit: 'cp2-08', type: 'def', term: 'Voucher',
      q: '¿Qué significa «voucher»?',
      a: 'Vale, cupón' },
    { id: 'cp2-08-say', unit: 'cp2-08', type: 'num',
      q: 'Ofreces bebidas. ¿Cómo preguntas al pasajero qué prefiere?',
      a: 'Would you prefer coffee or tea?',
      options: ['Would you prefer coffee or tea?', 'What you prefer, coffee or tea?', 'Which prefer you, coffee or tea?', 'Do you would prefer coffee or tea?'],
      say: 'Would you prefer coffee or tea?',
      note: 'En las preguntas, el auxiliar va delante del sujeto: «Would you…?», «What do you…?».' },
    { id: 'cp2-08-pairs', unit: 'cp2-08', type: 'match',
      q: 'Asking about options: preguntar por opciones',
      pairs: [['What would you like?', '¿Qué desea?'],
              ['Which would you prefer?', '¿Cuál prefiere?'],
              ['We have chicken or pasta', 'Tenemos pollo o pasta'],
              ['Would you like anything else?', '¿Desea algo más?']] },

    /* ───────────── 9 · Approach 1 ───────────── */
    { id: 'cp2-armrest', unit: 'cp2-09', type: 'def', term: 'Armrest',
      q: '¿Qué significa «armrest»?',
      a: 'Reposabrazos (descansabrazos)' },
    { id: 'cp2-buckle', unit: 'cp2-09', type: 'def', term: 'Buckle',
      q: '¿Qué significa «buckle»?',
      a: 'Hebilla; abrochar',
      note: 'Ej.: “Please buckle up.”' },
    { id: 'cp2-collect', unit: 'cp2-09', type: 'def', term: 'Collect',
      q: '¿Qué significa «collect»?',
      a: 'Recoger' },
    { id: 'cp2-discard', unit: 'cp2-09', type: 'def', term: 'Discard',
      q: '¿Qué significa «discard»?',
      a: 'Desechar, tirar' },
    { id: 'cp2-lock', unit: 'cp2-09', type: 'def', term: 'Lock',
      q: '¿Qué significa «lock»?',
      a: 'Trabar (cerrar con seguro)',
      note: 'Ej.: “Make sure your tray table is locked.”' },
    { id: 'cp2-lower', unit: 'cp2-09', type: 'def', term: 'Lower',
      q: '¿Qué significa «lower»?',
      a: 'Bajar',
      note: 'Ej.: “Please lower your armrest.”' },
    { id: 'cp2-pass', unit: 'cp2-09', type: 'def', term: 'Pass',
      q: '¿Qué significa «pass»?',
      a: 'Pasar: dar algo a otra persona',
      note: 'Ej.: “Please pass your cups to the aisle.”' },
    { id: 'cp2-recline', unit: 'cp2-09', type: 'def', term: 'Recline',
      q: '¿Qué significa «recline»?',
      a: 'Reclinar' },
    { id: 'cp2-seatback', unit: 'cp2-09', type: 'def', term: 'Seatback',
      q: '¿Qué significa «seatback»?',
      a: 'Respaldo (del asiento)' },
    { id: 'cp2-trash', unit: 'cp2-09', type: 'def', term: 'Trash',
      q: '¿Qué significa «trash»?',
      a: 'Basura',
      note: 'En inglés británico, «rubbish».' },
    { id: 'cp2-tray-table', unit: 'cp2-09', type: 'def', term: 'Tray table',
      q: '¿Qué significa «tray table»?',
      a: 'Mesita plegable (bandeja)' },
    { id: 'cp2-turn-off', unit: 'cp2-09', type: 'def', term: 'Turn off',
      q: '¿Qué significa «turn off»?',
      a: 'Apagar' },
    { id: 'cp2-upright', unit: 'cp2-09', type: 'def', term: 'Upright',
      q: '¿Qué significa «upright»?',
      a: 'Vertical (derecho)',
      note: 'Ej.: “Return your seatback to the upright position.”' },
    { id: 'cp2-09-say', unit: 'cp2-09', type: 'num',
      q: 'Ya pediste que suban el respaldo. ¿Cómo añades otra instrucción?',
      a: 'Also, please make sure your tray table is stowed.',
      options: ['Also, please make sure your tray table is stowed.', 'Also, please make sure your tray table stowed.', 'And too, please stow the tray table.', 'Moreover please you stow your tray table.'],
      say: 'Also, please make sure your tray table is stowed.',
      note: '«Also» va al principio o antes del verbo; «too», al final de la frase.' },
    { id: 'cp2-09-pairs', unit: 'cp2-09', type: 'match',
      q: 'Adding an instruction: añadir instrucciones',
      pairs: [['Also, please…', 'Además, por favor…'],
              ['In addition to that…', 'Sumado a eso…'],
              ['One more thing…', 'Una cosa más…'],
              ['And finally…', 'Y por último…']] },

    /* ───────────── 10 · Approach 2 ───────────── */
    { id: 'cp2-account-for', unit: 'cp2-10', type: 'def', term: 'Account for',
      q: '¿Qué significa «account for»?',
      a: 'Tener controlado: comprobar que no falta nada ni nadie',
      note: 'Ej.: “All carts must be accounted for before landing.”' },
    { id: 'cp2-announce', unit: 'cp2-10', type: 'def', term: 'Announce',
      q: '¿Qué significa «announce»?',
      a: 'Anunciar' },
    { id: 'cp2-connecting-flight', unit: 'cp2-10', type: 'def', term: 'Connecting flight',
      q: '¿Qué significa «connecting flight»?',
      a: 'Vuelo de conexión' },
    { id: 'cp2-destination', unit: 'cp2-10', type: 'def', term: 'Destination',
      q: '¿Qué significa «destination»?',
      a: 'Destino' },
    { id: 'cp2-estimated-time-of-arrival-eta', unit: 'cp2-10', type: 'def', term: 'Estimated time of arrival (ETA)',
      q: '¿Qué significa «estimated time of arrival (ETA)»?',
      a: 'Hora estimada de llegada',
      say: 'Estimated time of arrival' },
    { id: 'cp2-headset', unit: 'cp2-10', type: 'def', term: 'Headset',
      q: '¿Qué significa «headset»?',
      a: 'Audífonos (auriculares)',
      note: 'Ej.: “We’ll be collecting headsets shortly.”' },
    { id: 'cp2-holding', unit: 'cp2-10', type: 'def', term: 'Holding',
      q: '¿Qué significa «holding»?',
      a: 'Espera: dar vueltas en el aire antes de aterrizar',
      note: 'Ej.: “We are in a holding pattern due to traffic.”' },
    { id: 'cp2-money', unit: 'cp2-10', type: 'def', term: 'Money',
      q: '¿Qué significa «money»?',
      a: 'Dinero',
      note: 'Es incontable: «How much money?», nunca «How many moneys?».' },
    { id: 'cp2-reassure', unit: 'cp2-10', type: 'def', term: 'Reassure',
      q: '¿Qué significa «reassure»?',
      a: 'Tranquilizar (dar seguridad)',
      note: 'Ej.: “She reassured the nervous passenger.”' },
    { id: 'cp2-secure-the-cabin', unit: 'cp2-10', type: 'def', term: 'Secure the cabin',
      q: '¿Qué significa «secure the cabin»?',
      a: 'Asegurar la cabina: dejarla lista para aterrizar' },
    { id: 'cp2-10-say', unit: 'cp2-10', type: 'num',
      q: 'Como sobrecargo, repartes tareas antes del aterrizaje. ¿Qué frase es correcta?',
      a: 'Marco, could you collect the headsets in rows 1 to 10?',
      options: ['Marco, could you collect the headsets in rows 1 to 10?', 'Marco, I need that you collect the headsets.', 'Marco, can you to collect the headsets?', 'Marco, could you collecting the headsets?'],
      say: 'Marco, could you collect the headsets in rows 1 to 10?',
      note: '«Necesito que hagas…» se dice «I need you to…», no «I need that you…».' },
    { id: 'cp2-10-pairs', unit: 'cp2-10', type: 'match',
      q: 'Assigning tasks: repartir tareas',
      pairs: [['Could you take care of…?', '¿Te puedes encargar de…?'],
              ['I need you to…', 'Necesito que…'],
              ['You’re in charge of…', 'Tú estás a cargo de…'],
              ['Please check…', 'Por favor, revisa…']] },

    /* ───────────── 11 · Arrival ───────────── */
    { id: 'cp2-assistance', unit: 'cp2-11', type: 'def', term: 'Assistance',
      q: '¿Qué significa «assistance»?',
      a: 'Asistencia, ayuda',
      note: 'Ej.: “Passengers requiring assistance, please remain seated.”' },
    { id: 'cp2-call-button', unit: 'cp2-11', type: 'def', term: 'Call button',
      q: '¿Qué significa «call button»?',
      a: 'Botón de llamada a la tripulación' },
    { id: 'cp2-caution', unit: 'cp2-11', type: 'def', term: 'Caution',
      q: '¿Qué significa «caution»?',
      a: 'Precaución, cuidado',
      note: 'Ej.: “Use caution when opening the overhead bins.”' },
    { id: 'cp2-complete', unit: 'cp2-11', type: 'def', term: 'Complete',
      q: '¿Qué significa «complete»?',
      a: 'Completo; completar (terminar)',
      note: 'Ej.: “Remain seated until the aircraft has come to a complete stop.”' },
    { id: 'cp2-disarm', unit: 'cp2-11', type: 'def', term: 'Disarm',
      q: '¿Qué significa «disarm»?',
      a: 'Desarmar: quitar el tobogán del modo automático',
      note: 'Ej.: “Cabin crew, disarm doors and cross-check.”' },
    { id: 'cp2-injury', unit: 'cp2-11', type: 'def', term: 'Injury',
      q: '¿Qué significa «injury»?',
      a: 'Lesión, herida' },
    { id: 'cp2-land', unit: 'cp2-11', type: 'def', term: 'Land',
      q: '¿Qué significa «land»?',
      a: 'Aterrizar',
      note: 'Ej.: “We have just landed in San Salvador.”' },
    { id: 'cp2-local-time', unit: 'cp2-11', type: 'def', term: 'Local time',
      q: '¿Qué significa «local time»?',
      a: 'Hora local' },
    { id: 'cp2-park', unit: 'cp2-11', type: 'def', term: 'Park',
      q: '¿Qué significa «park»?',
      a: 'Estacionar (aparcar) el avión',
      note: 'Ej.: “once we are parked at the gate”.' },
    { id: 'cp2-remain', unit: 'cp2-11', type: 'def', term: 'Remain',
      q: '¿Qué significa «remain»?',
      a: 'Permanecer',
      note: 'Ej.: “Please remain seated.”' },
    { id: 'cp2-remind', unit: 'cp2-11', type: 'def', term: 'Remind',
      q: '¿Qué significa «remind»?',
      a: 'Recordar (a alguien)',
      note: '«Remind» es recordarle algo a otro; «remember» es acordarte tú.' },
    { id: 'cp2-shift', unit: 'cp2-11', type: 'def', term: 'Shift',
      q: '¿Qué significa «shift»?',
      a: 'Moverse, desplazarse',
      note: 'Ej.: “Items may have shifted during the flight.”' },
    { id: 'cp2-11-say', unit: 'cp2-11', type: 'num',
      q: 'Quieres insistir en que no se levanten todavía. ¿Qué dices?',
      a: 'It’s very important that you stay seated until the sign is off.',
      options: ['It’s very important that you stay seated until the sign is off.', 'Is very important you stay seated until the sign is off.', 'It’s very important that you stays seated until the sign is off.', 'It’s very importantly that you stay seated.'],
      say: 'It’s very important that you stay seated until the sign is off.',
      note: 'No olvides el sujeto «it»: «It’s important…».' },
    { id: 'cp2-11-pairs', unit: 'cp2-11', type: 'match',
      q: 'Stressing a point: insistir en algo',
      pairs: [['I must stress that…', 'Debo insistir en que…'],
              ['It’s essential that…', 'Es imprescindible que…'],
              ['Please note that…', 'Tengan en cuenta que…'],
              ['Under no circumstances…', 'Bajo ninguna circunstancia…']] },

    /* ───────────── 12 · Post-flight Duties ───────────── */
    { id: 'cp2-air-vent', unit: 'cp2-12', type: 'def', term: 'Air vent',
      q: '¿Qué significa «air vent»?',
      a: 'Rejilla de ventilación (salida de aire)' },
    { id: 'cp2-blanket', unit: 'cp2-12', type: 'def', term: 'Blanket',
      q: '¿Qué significa «blanket»?',
      a: 'Manta (cobija, frazada)' },
    { id: 'cp2-clean', unit: 'cp2-12', type: 'def', term: 'Clean',
      q: '¿Qué significa «clean»?',
      a: 'Limpiar; limpio' },
    { id: 'cp2-drawer', unit: 'cp2-12', type: 'def', term: 'Drawer',
      q: '¿Qué significa «drawer»?',
      a: 'Cajón',
      note: 'En el galley, los cajones guardan cubiertos, vasos y demás.' },
    { id: 'cp2-litter', unit: 'cp2-12', type: 'def', term: 'Litter',
      q: '¿Qué significa «litter»?',
      a: 'Basura tirada (desperdicios)',
      note: 'Como verbo, «to litter» es tirar basura donde no se debe.' },
    { id: 'cp2-lost-and-found', unit: 'cp2-12', type: 'def', term: 'Lost-and-found',
      q: '¿Qué significa «lost-and-found»?',
      a: 'Objetos perdidos' },
    { id: 'cp2-organize', unit: 'cp2-12', type: 'def', term: 'Organize',
      q: '¿Qué significa «organize»?',
      a: 'Organizar, ordenar' },
    { id: 'cp2-pillow', unit: 'cp2-12', type: 'def', term: 'Pillow',
      q: '¿Qué significa «pillow»?',
      a: 'Almohada' },
    { id: 'cp2-replace', unit: 'cp2-12', type: 'def', term: 'Replace',
      q: '¿Qué significa «replace»?',
      a: 'Sustituir: poner otro en su lugar',
      note: 'Ej.: “Replace the safety cards in the seatback pockets.”' },
    { id: 'cp2-seatback-pocket', unit: 'cp2-12', type: 'def', term: 'Seatback pocket',
      q: '¿Qué significa «seatback pocket»?',
      a: 'Bolsillo del respaldo' },
    { id: 'cp2-stock', unit: 'cp2-12', type: 'def', term: 'Stock',
      q: '¿Qué significa «stock»?',
      a: 'Abastecer: llenar de provisiones',
      note: 'Ej.: “The galley is fully stocked.”' },
    { id: 'cp2-store', unit: 'cp2-12', type: 'def', term: 'Store',
      q: '¿Qué significa «store»?',
      a: 'Guardar, almacenar',
      note: 'Como sustantivo, «store» es «tienda».' },
    { id: 'cp2-toilet-paper', unit: 'cp2-12', type: 'def', term: 'Toilet paper',
      q: '¿Qué significa «toilet paper»?',
      a: 'Papel higiénico' },
    { id: 'cp2-12-say', unit: 'cp2-12', type: 'num',
      q: 'Un pasajero se queja de que su asiento estaba sucio. ¿Cómo te disculpas?',
      a: 'I’m so sorry about that. Let me find you a clean seat.',
      options: ['I’m so sorry about that. Let me find you a clean seat.', 'I’m so sorry for that. I search you a clean seat.', 'Sorry, but is not my fault.', 'I’m sorry. I will look you a clean seat.'],
      say: 'I’m so sorry about that. Let me find you a clean seat.',
      note: '«Buscarle algo a alguien» = «find you something» (o «look for something for you»).' },
    { id: 'cp2-12-pairs', unit: 'cp2-12', type: 'match',
      q: 'Making an apology: pedir disculpas',
      pairs: [['I’m terribly sorry', 'Lo siento muchísimo'],
              ['Please accept our apologies', 'Le rogamos acepte nuestras disculpas'],
              ['I understand your frustration', 'Entiendo su molestia'],
              ['Let me make it right', 'Déjeme solucionarlo']] },

    /* ───────────── 13 · Between Flights ───────────── */
    { id: 'cp2-accommodations', unit: 'cp2-13', type: 'def', term: 'Accommodations',
      q: '¿Qué significa «accommodations»?',
      a: 'Alojamiento (hospedaje)' },
    { id: 'cp2-continuous-duty-overnight-cdo', unit: 'cp2-13', type: 'def', term: 'Continuous duty overnight (CDO)',
      q: '¿Qué significa «continuous duty overnight (CDO)»?',
      a: 'Jornada nocturna continua: volar de noche con pocas horas de descanso antes del primer vuelo de la mañana',
      say: 'Continuous duty overnight' },
    { id: 'cp2-crash-pad', unit: 'cp2-13', type: 'def', term: 'Crash pad',
      q: '¿Qué significa «crash pad»?',
      a: 'Departamento compartido por tripulantes cerca de su base',
      note: 'Muy común entre quienes viven en otra ciudad.' },
    { id: 'cp2-crew-meal', unit: 'cp2-13', type: 'def', term: 'Crew meal',
      q: '¿Qué significa «crew meal»?',
      a: 'Comida de la tripulación' },
    { id: 'cp2-deplane', unit: 'cp2-13', type: 'def', term: 'Deplane',
      q: '¿Qué significa «deplane»?',
      a: 'Bajar del avión',
      note: 'Sinónimo de «disembark».' },
    { id: 'cp2-ground-time', unit: 'cp2-13', type: 'def', term: 'Ground time',
      q: '¿Qué significa «ground time»?',
      a: 'Tiempo en tierra del avión entre dos vuelos',
      syn: ['Sit time'] },
    { id: 'cp2-hotel', unit: 'cp2-13', type: 'def', term: 'Hotel',
      q: '¿Qué significa «hotel»?',
      a: 'Hotel',
      note: 'El acento va al final, “ho-TEL”, y la h sí suena.' },
    { id: 'cp2-leg', unit: 'cp2-13', type: 'def', term: 'Leg',
      q: '¿Qué significa «leg»?',
      a: 'Tramo (etapa) de un viaje',
      note: 'Ej.: “Today I have a four-leg trip.”' },
    { id: 'cp2-per-diem', unit: 'cp2-13', type: 'def', term: 'Per diem',
      q: '¿Qué significa «per diem»?',
      a: 'Viático (dieta): dinero diario para gastos fuera de base',
      note: 'Del latín «por día».' },
    { id: 'cp2-remain-overnight', unit: 'cp2-13', type: 'def', term: 'Remain overnight',
      q: '¿Qué significa «remain overnight»?',
      a: 'Pernoctar: pasar la noche fuera de base',
      note: 'Se abrevia «RON».' },
    { id: 'cp2-sit-time', unit: 'cp2-13', type: 'def', term: 'Sit time',
      q: '¿Qué significa «sit time»?',
      a: 'Tiempo de espera de la tripulación en el aeropuerto entre dos tramos',
      syn: ['Ground time'] },
    { id: 'cp2-time-away-from-base', unit: 'cp2-13', type: 'def', term: 'Time away from base',
      q: '¿Qué significa «time away from base»?',
      a: 'Tiempo fuera de base',
      note: 'Se abrevia «TAFB» y suele determinar el viático.' },
    { id: 'cp2-13-say', unit: 'cp2-13', type: 'num',
      q: 'Es tu primera pernocta en Nueva York. ¿Cómo pides consejo a un compañero?',
      a: 'What would you recommend doing on a layover here?',
      options: ['What would you recommend doing on a layover here?', 'Can you give me an advice for the layover?', 'What you recommend for do in the layover?', 'What do you recommend me to do here?'],
      say: 'What would you recommend doing on a layover here?',
      note: '«Advice» es incontable: «some advice» o «a piece of advice», nunca «an advice».' },
    { id: 'cp2-13-pairs', unit: 'cp2-13', type: 'match',
      q: 'Asking for advice: pedir consejo',
      pairs: [['What would you recommend?', '¿Qué me recomiendas?'],
              ['Do you have any tips for…?', '¿Tienes algún truco para…?'],
              ['What should I do if…?', '¿Qué hago si…?'],
              ['Is it worth…?', '¿Vale la pena…?']] },

    /* ───────────── 14 · Passengers 1 ───────────── */
    { id: 'cp2-angry', unit: 'cp2-14', type: 'def', term: 'Angry',
      q: '¿Qué significa «angry»?',
      a: 'Enojado (enfadado)' },
    { id: 'cp2-demanding', unit: 'cp2-14', type: 'def', term: 'Demanding',
      q: '¿Qué significa «demanding»?',
      a: 'Exigente' },
    { id: 'cp2-disrespectful', unit: 'cp2-14', type: 'def', term: 'Disrespectful',
      q: '¿Qué significa «disrespectful»?',
      a: 'Irrespetuoso' },
    { id: 'cp2-empathy', unit: 'cp2-14', type: 'def', term: 'Empathy',
      q: '¿Qué significa «empathy»?',
      a: 'Empatía' },
    { id: 'cp2-impatient', unit: 'cp2-14', type: 'def', term: 'Impatient',
      q: '¿Qué significa «impatient»?',
      a: 'Impaciente' },
    { id: 'cp2-irritable', unit: 'cp2-14', type: 'def', term: 'Irritable',
      q: '¿Qué significa «irritable»?',
      a: 'Irritable',
      note: 'Se escribe igual, pero se pronuncia “Í-ri-ta-bol”.', syn: ['Short-tempered'] },
    { id: 'cp2-polite', unit: 'cp2-14', type: 'def', term: 'Polite',
      q: '¿Qué significa «polite»?',
      a: 'Educado, cortés' },
    { id: 'cp2-short-tempered', unit: 'cp2-14', type: 'def', term: 'Short-tempered',
      q: '¿Qué significa «short-tempered»?',
      a: 'De mal genio: que se enoja enseguida',
      syn: ['Irritable'] },
    { id: 'cp2-stressed', unit: 'cp2-14', type: 'def', term: 'Stressed',
      q: '¿Qué significa «stressed»?',
      a: 'Estresado' },
    { id: 'cp2-take-it-out-on', unit: 'cp2-14', type: 'def', term: 'Take it out on',
      q: '¿Qué significa «take it out on»?',
      a: 'Desquitarse con (alguien)',
      note: 'Ej.: “He was angry about the delay and took it out on the crew.”' },
    { id: 'cp2-unruly', unit: 'cp2-14', type: 'def', term: 'Unruly',
      q: '¿Qué significa «unruly»?',
      a: 'Revoltoso, disruptivo: que no obedece' },
    { id: 'cp2-vent', unit: 'cp2-14', type: 'def', term: 'Vent',
      q: '¿Qué significa «vent»?',
      a: 'Desahogarse',
      note: 'Ej.: “Let the passenger vent before you respond.” También es una salida de aire.' },
    { id: 'cp2-14-say', unit: 'cp2-14', type: 'num',
      q: 'Tu compañera calmó muy bien a un pasajero enojado. ¿Cómo la felicitas?',
      a: 'You handled that really well. Great job!',
      options: ['You handled that really well. Great job!', 'You handled that very good. Great job!', 'You did it very well done!', 'Great work you made!'],
      say: 'You handled that really well. Great job!',
      note: 'Con verbos se usa el adverbio «well», no el adjetivo «good».' },
    { id: 'cp2-14-pairs', unit: 'cp2-14', type: 'match',
      q: 'Giving praise: felicitar',
      pairs: [['Great job!', '¡Buen trabajo!'],
              ['You handled that really well', 'Lo manejaste muy bien'],
              ['I’m impressed', 'Me impresionaste'],
              ['Keep up the good work', 'Sigue así']] },

    /* ───────────── 15 · Passengers 2 ───────────── */
    { id: 'cp2-assist', unit: 'cp2-15', type: 'def', term: 'Assist',
      q: '¿Qué significa «assist»?',
      a: 'Ayudar, asistir' },
    { id: 'cp2-disabled', unit: 'cp2-15', type: 'def', term: 'Disabled',
      q: '¿Qué significa «disabled»?',
      a: 'Con discapacidad',
      note: 'Hoy se prefiere «passenger with a disability».' },
    { id: 'cp2-elderly', unit: 'cp2-15', type: 'def', term: 'Elderly',
      q: '¿Qué significa «elderly»?',
      a: 'Mayor (de edad avanzada)',
      note: 'Ej.: “elderly passengers” = pasajeros de la tercera edad.' },
    { id: 'cp2-escort', unit: 'cp2-15', type: 'def', term: 'Escort',
      q: '¿Qué significa «escort»?',
      a: 'Acompañar (escoltar); acompañante' },
    { id: 'cp2-family', unit: 'cp2-15', type: 'def', term: 'Family',
      q: '¿Qué significa «family»?',
      a: 'Familia',
      note: 'Ej.: “Families with young children may board first.”' },
    { id: 'cp2-infant', unit: 'cp2-15', type: 'def', term: 'Infant',
      q: '¿Qué significa «infant»?',
      a: 'Bebé (menor de 2 años)',
      note: 'En aviación, «infant» es un niño de menos de 2 años que viaja en brazos.' },
    { id: 'cp2-medical-needs', unit: 'cp2-15', type: 'def', term: 'Medical needs',
      q: '¿Qué significa «medical needs»?',
      a: 'Necesidades médicas' },
    { id: 'cp2-pax', unit: 'cp2-15', type: 'def', term: 'Pax',
      q: '¿Qué significa «pax»?',
      a: 'Pax: abreviatura de pasajero(s)',
      note: 'Ej.: “We have 180 pax on board.”' },
    { id: 'cp2-preboard', unit: 'cp2-15', type: 'def', term: 'Preboard',
      q: '¿Qué significa «preboard»?',
      a: 'Embarcar antes (embarque prioritario)' },
    { id: 'cp2-special-needs', unit: 'cp2-15', type: 'def', term: 'Special needs',
      q: '¿Qué significa «special needs»?',
      a: 'Necesidades especiales' },
    { id: 'cp2-unaccompanied-minors', unit: 'cp2-15', type: 'def', term: 'Unaccompanied minors',
      q: '¿Qué significa «unaccompanied minors»?',
      a: 'Menores no acompañados',
      note: 'Se abrevia «UM» o «UMNR».' },
    { id: 'cp2-wheelchair', unit: 'cp2-15', type: 'def', term: 'Wheelchair',
      q: '¿Qué significa «wheelchair»?',
      a: 'Silla de ruedas' },
    { id: 'cp2-15-say', unit: 'cp2-15', type: 'num',
      q: 'Una madre no logra calmar a su bebé durante el descenso. ¿Qué le sugieres?',
      a: 'You could try giving the baby a bottle during descent.',
      options: ['You could try giving the baby a bottle during descent.', 'You could try to giving the baby a bottle.', 'Try you give the baby a bottle.', 'Maybe you can to give the baby a bottle.'],
      say: 'You could try giving the baby a bottle during descent.',
      note: 'Tragar ayuda a igualar la presión de los oídos del bebé.' },
    { id: 'cp2-15-pairs', unit: 'cp2-15', type: 'match',
      q: 'Making a suggestion: sugerir',
      pairs: [['You could try…', 'Podría intentar…'],
              ['It might help to…', 'Quizá ayude…'],
              ['Have you thought about…?', '¿Ha pensado en…?'],
              ['If I were you, I’d…', 'Yo en su lugar…']] }
  ]
};
