/* Extensión ESL: inglés técnico de aviación para hispanohablantes.
   Mismo formato de fichas que el examen TCP. En las fichas `def`, `term` es la
   expresión en inglés y `a` su traducción; `say` es el texto que se lee en voz
   alta (si falta, se lee `term`). */
window.CC = window.CC || {};

CC.ESL = {
  UNITS: [
    { id: 'e-apt',   course: 'esl', name: 'Seguridad en el aeropuerto', icon: '🛂', hue: 280, blurb: 'Airport security: filtro, rayos X y equipaje' },
    { id: 'e-acft',  course: 'esl', name: 'Seguridad en el avión',      icon: '🦺', hue: 12,  blurb: 'Aircraft safety: demo, salidas y equipos' },
    { id: 'e-cs',    course: 'esl', name: 'Customer service',           icon: '🤝', hue: 145, blurb: 'Atención al pasajero en inglés' },
    { id: 'e-parts', course: 'esl', name: 'Partes y fases del vuelo',   icon: '🛠️', hue: 220, blurb: 'Galley, jump seat, landing gear y más' },
    { id: 'e-pa',    course: 'esl', name: 'Anuncios y emergencias',     icon: '📢', hue: 35,  blurb: 'PA announcements y órdenes de evacuación' },
    { id: 'e-radio', course: 'esl', name: 'Alfabeto y radio OACI',      icon: '🔤', hue: 200, blurb: 'Alfa, Bravo, Charlie… Roger, Wilco' }
  ],

  CARDS: [
    /* ───────────── Seguridad en el aeropuerto ───────────── */
    { id: 'esl-a1', unit: 'e-apt', type: 'def', term: 'Security checkpoint',
      q: '¿Qué significa «security checkpoint»?',
      a: 'Control o filtro de seguridad',
      note: 'Ej.: “Please proceed to the security checkpoint.”' },
    { id: 'esl-a2', unit: 'e-apt', type: 'def', term: 'Screening',
      q: '¿Qué significa «screening»?',
      a: 'Inspección de pasajeros y equipaje',
      note: 'Ej.: “All passengers are subject to security screening.”' },
    { id: 'esl-a3', unit: 'e-apt', type: 'def', term: 'Walk-through metal detector',
      q: '¿Qué significa «walk-through metal detector»?',
      a: 'Arco detector de metales' },
    { id: 'esl-a4', unit: 'e-apt', type: 'def', term: 'Pat-down',
      q: '¿Qué significa «pat-down»?',
      a: 'Cacheo o registro manual',
      note: 'Ej.: “I need to do a pat-down. Please raise your arms.”' },
    { id: 'esl-a5', unit: 'e-apt', type: 'def', term: 'Carry-on baggage',
      q: '¿Qué significa «carry-on baggage»?',
      a: 'Equipaje de mano' },
    { id: 'esl-a6', unit: 'e-apt', type: 'def', term: 'Checked baggage',
      q: '¿Qué significa «checked baggage»?',
      a: 'Equipaje facturado (documentado)' },
    { id: 'esl-a7', unit: 'e-apt', type: 'def', term: 'Boarding pass',
      q: '¿Qué significa «boarding pass»?',
      a: 'Tarjeta de embarque (pase de abordar)' },
    { id: 'esl-a8', unit: 'e-apt', type: 'def', term: 'Unattended baggage',
      q: '¿Qué significa «unattended baggage»?',
      a: 'Equipaje desatendido (sin vigilancia)',
      note: 'Ej.: “Unattended baggage will be removed and may be destroyed.”' },
    { id: 'esl-a9', unit: 'e-apt', type: 'def', term: 'Dangerous goods',
      q: '¿Qué significa «dangerous goods»?',
      a: 'Mercancías peligrosas' },
    { id: 'esl-a10', unit: 'e-apt', type: 'def', term: 'Airside',
      q: '¿Qué significa «airside»?',
      a: 'Lado aire: la zona restringida después del control de seguridad',
      note: 'Lo contrario es «landside» (lado tierra).' },
    { id: 'esl-a11', unit: 'e-apt', type: 'num',
      q: 'Completa: “Please ___ your laptop from your bag and place it in a separate tray.”',
      a: 'remove', options: ['remove', 'remain', 'remind', 'release'],
      say: 'Please remove your laptop from your bag and place it in a separate tray.' },
    { id: 'esl-a12', unit: 'e-apt', type: 'num',
      q: 'Completa: “Liquids must be in containers of 100 ___ or less.”',
      a: 'ml (millilitres)', options: ['ml (millilitres)', 'litres', 'kilos', 'metres'],
      say: 'Liquids must be in containers of one hundred millilitres or less.' },
    { id: 'esl-a13', unit: 'e-apt', type: 'list',
      q: 'Prohibited items in carry-on baggage (artículos prohibidos en el equipaje de mano)',
      items: ['Knives and blades', 'Firearms', 'Flammable liquids', 'Explosives'],
      lures: ['Reading glasses', 'Paperback books', 'Chewing gum', 'A mobile phone'] },
    { id: 'esl-a14', unit: 'e-apt', type: 'match',
      q: 'Instrucciones en el filtro de seguridad',
      pairs: [['Empty your pockets', 'Vacíe sus bolsillos'],
              ['Take off your shoes', 'Quítese los zapatos'],
              ['Raise your arms', 'Levante los brazos'],
              ['Step aside, please', 'Hágase a un lado, por favor'],
              ['Walk through', 'Pase por el arco']] },
    { id: 'esl-a15', unit: 'e-apt', type: 'order',
      q: 'Ordena el diálogo en el filtro de seguridad',
      steps: ['Officer: Good morning. Boarding pass and passport, please.',
              'Passenger: Here you are.',
              'Officer: Do you have any liquids or electronics in your bag?',
              'Passenger: Yes, a laptop and a small bag of liquids.',
              'Officer: Please place them in a separate tray and walk through.'] },

    /* ───────────── Seguridad en el avión ───────────── */
    { id: 'esl-s1', unit: 'e-acft', type: 'def', term: 'Life vest',
      q: '¿Qué significa «life vest»?',
      a: 'Chaleco salvavidas',
      note: 'Ej.: “Your life vest is located under your seat.”' },
    { id: 'esl-s2', unit: 'e-acft', type: 'def', term: 'Oxygen mask',
      q: '¿Qué significa «oxygen mask»?',
      a: 'Máscara de oxígeno',
      note: 'Ej.: “Secure your own mask before assisting others.”' },
    { id: 'esl-s3', unit: 'e-acft', type: 'def', term: 'Emergency exit',
      q: '¿Qué significa «emergency exit»?',
      a: 'Salida de emergencia' },
    { id: 'esl-s4', unit: 'e-acft', type: 'def', term: 'Floor path lighting',
      q: '¿Qué significa «floor path lighting»?',
      a: 'Luces de emergencia del piso que señalan el camino a la salida',
      note: 'Ej.: “Floor path lighting will guide you to an exit.”' },
    { id: 'esl-s5', unit: 'e-acft', type: 'def', term: 'Brace position',
      q: '¿Qué significa «brace position»?',
      a: 'Posición de impacto (de protección)' },
    { id: 'esl-s6', unit: 'e-acft', type: 'def', term: 'Evacuation slide',
      q: '¿Qué significa «evacuation slide»?',
      a: 'Tobogán de evacuación' },
    { id: 'esl-s7', unit: 'e-acft', type: 'def', term: 'Fasten seatbelt sign',
      q: '¿Qué significa «fasten seatbelt sign»?',
      a: 'Señal luminosa de abrocharse el cinturón',
      note: 'Ej.: “The captain has turned on the fasten seatbelt sign.”' },
    { id: 'esl-s8', unit: 'e-acft', type: 'def', term: 'Safety card',
      q: '¿Qué significa «safety card»?',
      a: 'Tarjeta de instrucciones de seguridad' },
    { id: 'esl-s9', unit: 'e-acft', type: 'def', term: 'Flight deck',
      q: '¿Qué significa «flight deck»?',
      a: 'Cabina de mando (de los pilotos)',
      note: 'Ej.: “The flight deck door must remain locked during the flight.”' },
    { id: 'esl-s10', unit: 'e-acft', type: 'def', term: 'Unruly passenger',
      q: '¿Qué significa «unruly passenger»?',
      a: 'Pasajero disruptivo o conflictivo',
      note: 'También se dice «disruptive passenger».' },
    { id: 'esl-s11', unit: 'e-acft', type: 'num',
      q: 'Completa: “Please make sure your seat back is in the ___ position.”',
      a: 'upright', options: ['upright', 'reclined', 'closed', 'down'],
      say: 'Please make sure your seat back is in the upright position.' },
    { id: 'esl-s12', unit: 'e-acft', type: 'num',
      q: 'Completa: “Pull the mask ___ you to start the flow of oxygen.”',
      a: 'towards', options: ['towards', 'away from', 'under', 'behind'],
      say: 'Pull the mask towards you to start the flow of oxygen.' },
    { id: 'esl-s13', unit: 'e-acft', type: 'order',
      q: 'Ordena la demostración del chaleco salvavidas',
      steps: ['Remove the life vest from the pouch under your seat.',
              'Slip it over your head.',
              'Fasten the straps around your waist and pull them tight.',
              'When you leave the aircraft, pull the red tabs to inflate it.',
              'If it does not inflate, blow into the mouthpieces.'] },
    { id: 'esl-s14', unit: 'e-acft', type: 'list',
      q: 'Before takeoff, passengers must… (antes del despegue)',
      items: ['Fasten their seatbelts', 'Put their seat backs upright', 'Stow their tray tables'],
      lures: ['Unfasten their seatbelts', 'Recline their seats', 'Leave their bags in the aisle'] },
    { id: 'esl-s15', unit: 'e-acft', type: 'match',
      q: 'Verbos del cinturón y el equipaje',
      pairs: [['Fasten', 'Abrochar'],
              ['Unfasten', 'Desabrochar'],
              ['Tighten', 'Ajustar'],
              ['Stow', 'Guardar (colocar en su sitio)']] },

    /* ───────────── Customer service ───────────── */
    { id: 'esl-c1', unit: 'e-cs', type: 'def', term: 'Aisle seat',
      q: '¿Qué significa «aisle seat»?',
      a: 'Asiento de pasillo',
      note: 'Ojo: «aisle» se pronuncia “ail”, la s es muda.' },
    { id: 'esl-c2', unit: 'e-cs', type: 'def', term: 'Window seat',
      q: '¿Qué significa «window seat»?',
      a: 'Asiento de ventanilla' },
    { id: 'esl-c3', unit: 'e-cs', type: 'def', term: 'Connecting flight',
      q: '¿Qué significa «connecting flight»?',
      a: 'Vuelo de conexión' },
    { id: 'esl-c4', unit: 'e-cs', type: 'def', term: 'Delay',
      q: '¿Qué significa «delay»?',
      a: 'Retraso (demora)',
      note: 'Ej.: “We apologise for the delay.”' },
    { id: 'esl-c5', unit: 'e-cs', type: 'def', term: 'Complimentary',
      q: '¿Qué significa «complimentary»?',
      a: 'Gratuito, de cortesía',
      note: 'Ej.: “Soft drinks and snacks are complimentary.”' },
    { id: 'esl-c6', unit: 'e-cs', type: 'def', term: 'Special meal',
      q: '¿Qué significa «special meal»?',
      a: 'Comida especial (vegetariana, sin gluten…)' },
    { id: 'esl-c7', unit: 'e-cs', type: 'def', term: 'Unaccompanied minor (UM)',
      q: '¿Qué significa «unaccompanied minor»?',
      a: 'Menor no acompañado',
      say: 'Unaccompanied minor' },
    { id: 'esl-c8', unit: 'e-cs', type: 'def', term: 'Lost and found',
      q: '¿Qué significa «lost and found»?',
      a: 'Objetos perdidos' },
    { id: 'esl-c9', unit: 'e-cs', type: 'num',
      q: '¿Cuál es la forma más cortés de pedirlo?',
      a: 'Could you please fasten your seatbelt?',
      options: ['Could you please fasten your seatbelt?', 'Fasten your seatbelt now.',
                'You must to fasten your seatbelt.', 'Seatbelt, quickly.'] },
    { id: 'esl-c10', unit: 'e-cs', type: 'num',
      q: 'Completa: “I’m sorry ___ the inconvenience.”',
      a: 'for', options: ['for', 'of', 'about', 'to'],
      say: 'I’m sorry for the inconvenience.' },
    { id: 'esl-c11', unit: 'e-cs', type: 'num',
      q: 'El pasajero te dice “Thank you!”. ¿Qué respondes?',
      a: 'You’re welcome.',
      options: ['You’re welcome.', 'Of nothing.', 'Yes, thank you.', 'No problem for me.'],
      note: '«Of nothing» es una traducción literal de «de nada»: en inglés no se usa.' },
    { id: 'esl-c12', unit: 'e-cs', type: 'order',
      q: 'Ordena el servicio de bebidas',
      steps: ['Crew: Good afternoon! Would you like something to drink?',
              'Passenger: Yes, an orange juice, please.',
              'Crew: Would you like ice with that?',
              'Passenger: No ice, thanks.',
              'Crew: Here you are. Enjoy your flight!'] },
    { id: 'esl-c13', unit: 'e-cs', type: 'match',
      q: 'Artículos que piden los pasajeros',
      pairs: [['Blanket', 'Manta (cobija)'],
              ['Pillow', 'Almohada'],
              ['Headphones', 'Auriculares (audífonos)'],
              ['Tray table', 'Mesa plegable'],
              ['Sick bag', 'Bolsa para el mareo']] },
    { id: 'esl-c14', unit: 'e-cs', type: 'list',
      q: 'Frases para calmar a un pasajero molesto',
      items: ['I understand how you feel.', 'Let me see what I can do.', 'Thank you for your patience.'],
      lures: ['That’s not my problem.', 'Calm down!', 'You are wrong.', 'Complain to the airline.'] },

    /* ───────────── Partes y fases del vuelo ───────────── */
    { id: 'esl-p1', unit: 'e-parts', type: 'def', term: 'Galley',
      q: '¿Qué significa «galley»?',
      a: 'Cocina del avión (galley)' },
    { id: 'esl-p2', unit: 'e-parts', type: 'def', term: 'Lavatory',
      q: '¿Qué significa «lavatory»?',
      a: 'Baño (lavabo) del avión',
      note: 'Ej.: “The lavatories are located at the front and rear of the cabin.”' },
    { id: 'esl-p3', unit: 'e-parts', type: 'def', term: 'Overhead bin',
      q: '¿Qué significa «overhead bin»?',
      a: 'Compartimento superior para el equipaje' },
    { id: 'esl-p4', unit: 'e-parts', type: 'def', term: 'Jump seat',
      q: '¿Qué significa «jump seat»?',
      a: 'Asiento plegable de la tripulación' },
    { id: 'esl-p5', unit: 'e-parts', type: 'def', term: 'Fuselage',
      q: '¿Qué significa «fuselage»?',
      a: 'Fuselaje (cuerpo principal del avión)' },
    { id: 'esl-p6', unit: 'e-parts', type: 'def', term: 'Landing gear',
      q: '¿Qué significa «landing gear»?',
      a: 'Tren de aterrizaje' },
    { id: 'esl-p7', unit: 'e-parts', type: 'def', term: 'Wing',
      q: '¿Qué significa «wing»?',
      a: 'Ala' },
    { id: 'esl-p8', unit: 'e-parts', type: 'def', term: 'Flaps',
      q: '¿Qué significa «flaps»?',
      a: 'Superficies del ala que aumentan la sustentación a baja velocidad' },
    { id: 'esl-p9', unit: 'e-parts', type: 'def', term: 'Auxiliary Power Unit (APU)',
      q: '¿Qué significa «APU»?',
      a: 'Unidad de potencia auxiliar',
      say: 'Auxiliary Power Unit' },
    { id: 'esl-p10', unit: 'e-parts', type: 'def', term: 'Call button',
      q: '¿Qué significa «call button»?',
      a: 'Botón de llamada a la tripulación' },
    { id: 'esl-p11', unit: 'e-parts', type: 'match',
      q: 'Fases del vuelo',
      pairs: [['Takeoff', 'Despegue'],
              ['Landing', 'Aterrizaje'],
              ['Taxi', 'Rodaje'],
              ['Climb', 'Ascenso'],
              ['Cruise', 'Crucero']] },
    { id: 'esl-p12', unit: 'e-parts', type: 'order',
      q: 'Ordena las fases del vuelo (flight phases)',
      steps: ['Boarding', 'Pushback', 'Taxi', 'Takeoff', 'Climb', 'Cruise', 'Descent', 'Landing'] },

    /* ───────────── Anuncios y emergencias ───────────── */
    { id: 'esl-e1', unit: 'e-pa', type: 'def', term: 'Brace for impact!',
      q: '¿Qué significa «Brace for impact!»?',
      a: '¡Prepárense para el impacto! (adopten la posición de impacto)' },
    { id: 'esl-e2', unit: 'e-pa', type: 'def', term: 'Heads down, stay down!',
      q: '¿Qué significa «Heads down, stay down!»?',
      a: '¡Cabezas abajo, quédense abajo!' },
    { id: 'esl-e3', unit: 'e-pa', type: 'def', term: 'Leave everything!',
      q: '¿Qué significa «Leave everything!»?',
      a: '¡Dejen todo! (sin equipaje)' },
    { id: 'esl-e4', unit: 'e-pa', type: 'def', term: 'Jump and slide!',
      q: '¿Qué significa «Jump and slide!»?',
      a: '¡Salten y deslícense!' },
    { id: 'esl-e5', unit: 'e-pa', type: 'def', term: 'Come this way!',
      q: '¿Qué significa «Come this way!»?',
      a: '¡Vengan por aquí!' },
    { id: 'esl-e6', unit: 'e-pa', type: 'def', term: 'Cabin crew, arm doors and cross-check',
      q: '¿Qué significa «Cabin crew, arm doors and cross-check»?',
      a: 'Tripulación, armen toboganes y hagan verificación cruzada' },
    { id: 'esl-e7', unit: 'e-pa', type: 'num',
      q: 'Completa: “Ladies and gentlemen, the captain has turned ___ the fasten seatbelt sign.”',
      a: 'on', options: ['on', 'in', 'up', 'at'],
      say: 'Ladies and gentlemen, the captain has turned on the fasten seatbelt sign.' },
    { id: 'esl-e8', unit: 'e-pa', type: 'num',
      q: 'Completa: “We will be landing ___ approximately twenty minutes.”',
      a: 'in', options: ['in', 'on', 'at', 'for'],
      say: 'We will be landing in approximately twenty minutes.' },
    { id: 'esl-e9', unit: 'e-pa', type: 'num',
      q: 'Completa: “We are currently experiencing some ___. Please return to your seats.”',
      a: 'turbulence', options: ['turbulence', 'turbulent', 'turbine', 'trouble air'],
      say: 'We are currently experiencing some turbulence. Please return to your seats.' },
    { id: 'esl-e10', unit: 'e-pa', type: 'order',
      q: 'Ordena las órdenes de evacuación (guion estándar)',
      steps: ['Evacuate! Evacuate!', 'Unfasten your seatbelts!', 'Come this way!', 'Leave everything!', 'Jump and slide!'] },
    { id: 'esl-e11', unit: 'e-pa', type: 'match',
      q: 'Expresiones de los anuncios',
      pairs: [['Ladies and gentlemen', 'Señoras y señores'],
              ['Please remain seated', 'Por favor, permanezcan sentados'],
              ['Local time', 'Hora local'],
              ['Final approach', 'Aproximación final']] },

    /* ───────────── Alfabeto y radio OACI ───────────── */
    { id: 'esl-r1', unit: 'e-radio', type: 'match',
      q: 'Alfabeto OACI: A – E',
      pairs: [['A', 'Alfa'], ['B', 'Bravo'], ['C', 'Charlie'], ['D', 'Delta'], ['E', 'Echo']] },
    { id: 'esl-r2', unit: 'e-radio', type: 'match',
      q: 'Alfabeto OACI: F – J',
      pairs: [['F', 'Foxtrot'], ['G', 'Golf'], ['H', 'Hotel'], ['I', 'India'], ['J', 'Juliett']] },
    { id: 'esl-r3', unit: 'e-radio', type: 'match',
      q: 'Alfabeto OACI: K – O',
      pairs: [['K', 'Kilo'], ['L', 'Lima'], ['M', 'Mike'], ['N', 'November'], ['O', 'Oscar']] },
    { id: 'esl-r4', unit: 'e-radio', type: 'match',
      q: 'Alfabeto OACI: P – T',
      pairs: [['P', 'Papa'], ['Q', 'Quebec'], ['R', 'Romeo'], ['S', 'Sierra'], ['T', 'Tango']] },
    { id: 'esl-r5', unit: 'e-radio', type: 'match',
      q: 'Alfabeto OACI: U – Z',
      pairs: [['U', 'Uniform'], ['V', 'Victor'], ['W', 'Whiskey'], ['X', 'X-ray'], ['Y', 'Yankee'], ['Z', 'Zulu']] },
    { id: 'esl-r6', unit: 'e-radio', type: 'num',
      q: '¿Cómo se dice el número 9 por radio?',
      a: 'Niner', options: ['Niner', 'Nine-o', 'Nein', 'Nono'],
      note: 'Se dice «niner» para no confundirlo con «nein» (no, en alemán).', say: 'Niner' },
    { id: 'esl-r7', unit: 'e-radio', type: 'num',
      q: '¿Cómo se lee «FL350» por radio?',
      a: 'Flight level three five zero',
      options: ['Flight level three five zero', 'Flight level three hundred fifty',
                'Flight level thirty-five hundred', 'Floor level three five zero'],
      say: 'Flight level three five zero' },
    { id: 'esl-r8', unit: 'e-radio', type: 'def', term: 'Roger',
      q: '¿Qué significa «Roger»?',
      a: 'Recibido: he recibido todo el mensaje' },
    { id: 'esl-r9', unit: 'e-radio', type: 'def', term: 'Wilco',
      q: '¿Qué significa «Wilco»?',
      a: 'Entendido y cumpliré (will comply)' },
    { id: 'esl-r10', unit: 'e-radio', type: 'def', term: 'Say again',
      q: '¿Qué significa «Say again»?',
      a: 'Repita (todo o parte del mensaje)',
      note: 'Por radio no se dice «repeat»: en fraseología militar significa volver a disparar.' },
    { id: 'esl-r11', unit: 'e-radio', type: 'def', term: 'Affirm',
      q: '¿Qué significa «Affirm»?',
      a: 'Sí (afirmativo)' },
    { id: 'esl-r12', unit: 'e-radio', type: 'def', term: 'Standby',
      q: '¿Qué significa «Standby»?',
      a: 'Espere, le llamaré' }
  ]
};
