/* Extensión ESL · Career Paths: Flight Attendant, libro 1.
   Las 15 unidades del libro (tripulación, aeropuerto, avión, imagen, tipos de
   vuelo y radio) con su vocabulario y la función comunicativa de cada una.
   Las traducciones y los ejemplos son propios: del libro solo se toman el
   temario y la lista de palabras. Mismo formato que js/data-esl.js; `syn`
   marca los sinónimos de la unidad, que no se usan como distractores entre sí. */
window.CC = window.CC || {};

CC.CP1 = {
  UNITS: [
    { id: 'cp1-01', course: 'esl', src: 'cp1', n: 1, name: 'La tripulación de vuelo', icon: '👩‍✈️', hue: 210,
      blurb: 'The Flight Crew: captain, purser, first officer…' },
    { id: 'cp1-02', course: 'esl', src: 'cp1', n: 2, name: 'Personal de la aerolínea', icon: '🧑‍💼', hue: 250,
      blurb: 'Airline Employees: gate agent, ramp agent, dispatcher…' },
    { id: 'cp1-03', course: 'esl', src: 'cp1', n: 3, name: 'Gente en el aeropuerto', icon: '👥', hue: 290,
      blurb: 'People in the Airport: screener, customs agent, mechanic…' },
    { id: 'cp1-04', course: 'esl', src: 'cp1', n: 4, name: 'Partes del aeropuerto', icon: '🏢', hue: 30,
      blurb: 'Parts of the Airport: terminal, concourse, runway…' },
    { id: 'cp1-05', course: 'esl', src: 'cp1', n: 5, name: 'Seguridad aeroportuaria', icon: '🛂', hue: 330,
      blurb: 'Airport Security: scanner, metal detector, crew lane…' },
    { id: 'cp1-06', course: 'esl', src: 'cp1', n: 6, name: 'Partes del avión', icon: '✈️', hue: 200,
      blurb: 'Parts of an Aircraft: fuselage, nose, wing, landing gear…' },
    { id: 'cp1-07', course: 'esl', src: 'cp1', n: 7, name: 'La cabina de pasajeros (1)', icon: '💺', hue: 160,
      blurb: 'Parts of the Cabin: aisle, row, window, business class…' },
    { id: 'cp1-08', course: 'esl', src: 'cp1', n: 8, name: 'La cabina de pasajeros (2)', icon: '🚪', hue: 120,
      blurb: 'Parts of the Cabin: galley, jumpseat, exit row, lavatory…' },
    { id: 'cp1-09', course: 'esl', src: 'cp1', n: 9, name: 'Exigencias físicas', icon: '💪', hue: 0,
      blurb: 'Physical Demands: fatigue, lift, confined space…' },
    { id: 'cp1-10', course: 'esl', src: 'cp1', n: 10, name: 'Imagen personal', icon: '💄', hue: 340,
      blurb: 'Appearance: grooming, jewelry, makeup, tattoos…' },
    { id: 'cp1-11', course: 'esl', src: 'cp1', n: 11, name: 'El uniforme', icon: '👔', hue: 230,
      blurb: 'Uniforms: blouse, slacks, ID badge, wings…' },
    { id: 'cp1-12', course: 'esl', src: 'cp1', n: 12, name: 'Tipos de vuelo', icon: '🌍', hue: 180,
      blurb: 'Types of Flights: non-stop, layover, long-haul…' },
    { id: 'cp1-13', course: 'esl', src: 'cp1', n: 13, name: 'Tipos de aeronave', icon: '🛩️', hue: 260,
      blurb: 'Types of Aircraft: regional jet, wide-body, turboprop…' },
    { id: 'cp1-14', course: 'esl', src: 'cp1', n: 14, name: 'Comunicaciones por radio', icon: '📻', hue: 190,
      blurb: 'Radio Communications: mayday, callsign, roger, over…' },
    { id: 'cp1-15', course: 'esl', src: 'cp1', n: 15, name: 'Retrasos y cancelaciones', icon: '⏳', hue: 45,
      blurb: 'Delays and Cancellations: de-ice, congestion, storm…' }
  ],

  CARDS: [
    /* ───────────── 1 · The Flight Crew ───────────── */
    { id: 'cp1-captain', unit: 'cp1-01', type: 'def', term: 'Captain',
      q: '¿Qué significa «captain»?',
      a: 'Comandante (capitán): el piloto al mando y máximo responsable del vuelo',
      note: 'Ej.: “Good morning, this is your captain speaking.”' },
    { id: 'cp1-chief-purser', unit: 'cp1-01', type: 'def', term: 'Chief purser',
      q: '¿Qué significa «chief purser»?',
      a: 'Sobrecargo principal: dirige a todos los sobrecargos y auxiliares a bordo',
      note: 'En aviones grandes hay varios pursers; el chief purser está por encima de todos.' },
    { id: 'cp1-copilot', unit: 'cp1-01', type: 'def', term: 'Copilot',
      q: '¿Qué significa «copilot»?',
      a: 'Copiloto: el piloto que asiste al comandante',
      note: 'En lenguaje formal se dice «first officer».', syn: ['First officer'] },
    { id: 'cp1-first-officer', unit: 'cp1-01', type: 'def', term: 'First officer',
      q: '¿Qué significa «first officer»?',
      a: 'Primer oficial: título formal del copiloto, segundo al mando',
      note: 'Ej.: “First Officer Díaz will be flying the aircraft today.”', syn: ['Copilot'] },
    { id: 'cp1-flight-attendant', unit: 'cp1-01', type: 'def', term: 'Flight attendant',
      q: '¿Qué significa «flight attendant»?',
      a: 'Auxiliar de vuelo (tripulante de cabina)',
      note: 'Es el término neutro que hoy sustituye a «stewardess» y «steward».' },
    { id: 'cp1-flight-crew', unit: 'cp1-01', type: 'def', term: 'Flight crew',
      q: '¿Qué significa «flight crew»?',
      a: 'Tripulación de vuelo: las personas que trabajan a bordo',
      note: 'En sentido estricto son los pilotos; los auxiliares forman la «cabin crew».' },
    { id: 'cp1-flight-officer', unit: 'cp1-01', type: 'def', term: 'Flight officer',
      q: '¿Qué significa «flight officer»?',
      a: 'Oficial de vuelo: tripulante con licencia que trabaja en la cabina de mando' },
    { id: 'cp1-pilot', unit: 'cp1-01', type: 'def', term: 'Pilot',
      q: '¿Qué significa «pilot»?',
      a: 'Piloto: quien vuela (maneja) el avión' },
    { id: 'cp1-purser', unit: 'cp1-01', type: 'def', term: 'Purser',
      q: '¿Qué significa «purser»?',
      a: 'Sobrecargo (jefe de cabina): coordina al resto de los auxiliares',
      note: 'Se pronuncia “PUR-ser”.' },
    { id: 'cp1-senior-crew-member', unit: 'cp1-01', type: 'def', term: 'Senior crew member',
      q: '¿Qué significa «senior crew member»?',
      a: 'Tripulante sénior: auxiliar con más rango o experiencia, a cargo de una zona de la cabina' },
    { id: 'cp1-service-manager', unit: 'cp1-01', type: 'def', term: 'Service manager',
      q: '¿Qué significa «service manager»?',
      a: 'Jefe de servicio: organiza el servicio a bordo y al equipo que lo da' },
    { id: 'cp1-01-deck', unit: 'cp1-01', type: 'list',
      q: 'Trabajan en la cabina de mando (flight deck)',
      items: ['Captain', 'First officer', 'Flight officer'],
      lures: ['Purser', 'Flight attendant', 'Service manager'] },
    { id: 'cp1-01-say', unit: 'cp1-01', type: 'num',
      q: 'Te presentas a una compañera nueva antes del vuelo. ¿Qué dices?',
      a: 'Hi, I’m Laura. I’ll be working in the forward cabin today.',
      options: ['Hi, I’m Laura. I’ll be working in the forward cabin today.', 'Hi, I call me Laura. I work in the forward cabin today.', 'Hi, my name are Laura. I’m working forward today.', 'Hi, I have Laura. I will work forward today.'],
      say: 'Hi, I’m Laura. I’ll be working in the forward cabin today.',
      note: '«Me llamo…» se dice «My name is…» o «I’m…», nunca «I call me».' },
    { id: 'cp1-01-pairs', unit: 'cp1-01', type: 'match',
      q: 'Introductions: frases para presentarse',
      pairs: [['Nice to meet you', 'Encantada de conocerte'],
              ['Let me introduce…', 'Te presento a…'],
              ['This is our captain', 'Este es nuestro comandante'],
              ['I’m the purser on this flight', 'Soy el sobrecargo de este vuelo']] },

    /* ───────────── 2 · Airline Employees ───────────── */
    { id: 'cp1-airline', unit: 'cp1-02', type: 'def', term: 'Airline',
      q: '¿Qué significa «airline»?',
      a: 'Aerolínea (compañía aérea)' },
    { id: 'cp1-baggage-handler', unit: 'cp1-02', type: 'def', term: 'Baggage handler',
      q: '¿Qué significa «baggage handler»?',
      a: 'Maletero: carga y descarga las maletas del avión' },
    { id: 'cp1-flight-dispatcher', unit: 'cp1-02', type: 'def', term: 'Flight dispatcher',
      q: '¿Qué significa «flight dispatcher»?',
      a: 'Despachador de vuelo: planifica ruta, combustible y meteorología con el comandante' },
    { id: 'cp1-gate-agent', unit: 'cp1-02', type: 'def', term: 'Gate agent',
      q: '¿Qué significa «gate agent»?',
      a: 'Agente de puerta de embarque: controla el embarque en la sala',
      note: 'Ej.: “Please see the gate agent to change your seat.”' },
    { id: 'cp1-ground-crew', unit: 'cp1-02', type: 'def', term: 'Ground crew',
      q: '¿Qué significa «ground crew»?',
      a: 'Personal de tierra: trabaja con el avión en la plataforma' },
    { id: 'cp1-lineman', unit: 'cp1-02', type: 'def', term: 'Lineman',
      q: '¿Qué significa «lineman»?',
      a: 'Operario de línea: reposta, remolca y estaciona los aviones en tierra' },
    { id: 'cp1-passenger-service-agent', unit: 'cp1-02', type: 'def', term: 'Passenger service agent',
      q: '¿Qué significa «passenger service agent»?',
      a: 'Agente de atención al pasajero: ayuda a los viajeros en el aeropuerto' },
    { id: 'cp1-ramp-agent', unit: 'cp1-02', type: 'def', term: 'Ramp agent',
      q: '¿Qué significa «ramp agent»?',
      a: 'Agente de rampa: carga la bodega y guía al avión en la plataforma' },
    { id: 'cp1-station-agent', unit: 'cp1-02', type: 'def', term: 'Station agent',
      q: '¿Qué significa «station agent»?',
      a: 'Agente de estación: empleado de la aerolínea que cubre varias tareas en un aeropuerto' },
    { id: 'cp1-ticket-agent', unit: 'cp1-02', type: 'def', term: 'Ticket agent',
      q: '¿Qué significa «ticket agent»?',
      a: 'Agente de boletos: vende pasajes y documenta a los pasajeros en el mostrador' },
    { id: 'cp1-02-say', unit: 'cp1-02', type: 'num',
      q: 'Quieres saber cuándo empieza el embarque. ¿Qué preguntas?',
      a: 'When will boarding begin?',
      options: ['When will boarding begin?', 'When boarding will begin?', 'When does begins boarding?', 'What hour boarding begin?'],
      say: 'When will boarding begin?',
      note: 'En la pregunta, el auxiliar va antes del sujeto: «When will boarding begin?».' },
    { id: 'cp1-02-pairs', unit: 'cp1-02', type: 'match',
      q: 'Asking when: preguntar cuándo ocurrirá algo',
      pairs: [['When will…?', '¿Cuándo…?'],
              ['What time does… start?', '¿A qué hora empieza…?'],
              ['How long until…?', '¿Cuánto falta para…?'],
              ['Any idea when…?', '¿Sabes cuándo…?']] },

    /* ───────────── 3 · People in the Airport ───────────── */
    { id: 'cp1-air-traffic-controller', unit: 'cp1-03', type: 'def', term: 'Air traffic controller',
      q: '¿Qué significa «air traffic controller»?',
      a: 'Controlador aéreo (de tránsito aéreo)' },
    { id: 'cp1-cargo-forwarder', unit: 'cp1-03', type: 'def', term: 'Cargo forwarder',
      q: '¿Qué significa «cargo forwarder»?',
      a: 'Transitario de carga: organiza el envío de mercancías por avión' },
    { id: 'cp1-cargo-handler', unit: 'cp1-03', type: 'def', term: 'Cargo handler',
      q: '¿Qué significa «cargo handler»?',
      a: 'Operario de carga: sube y baja la mercancía del avión' },
    { id: 'cp1-customs-agent', unit: 'cp1-03', type: 'def', term: 'Customs agent',
      q: '¿Qué significa «customs agent»?',
      a: 'Agente de aduanas' },
    { id: 'cp1-food-service', unit: 'cp1-03', type: 'def', term: 'Food service',
      q: '¿Qué significa «food service»?',
      a: 'Servicio de comidas (catering) del aeropuerto o de a bordo' },
    { id: 'cp1-ground-controller', unit: 'cp1-03', type: 'def', term: 'Ground controller',
      q: '¿Qué significa «ground controller»?',
      a: 'Controlador de tierra: dirige a los aviones por las calles de rodaje',
      note: 'Por radio se le llama «Ground».' },
    { id: 'cp1-mechanic', unit: 'cp1-03', type: 'def', term: 'Mechanic',
      q: '¿Qué significa «mechanic»?',
      a: 'Mecánico (técnico de mantenimiento)' },
    { id: 'cp1-passenger', unit: 'cp1-03', type: 'def', term: 'Passenger',
      q: '¿Qué significa «passenger»?',
      a: 'Pasajero',
      note: 'En la jerga de aviación se abrevia «pax».' },
    { id: 'cp1-screener', unit: 'cp1-03', type: 'def', term: 'Screener',
      q: '¿Qué significa «screener»?',
      a: 'Inspector de seguridad: revisa a pasajeros y equipaje en el filtro' },
    { id: 'cp1-security-personnel', unit: 'cp1-03', type: 'def', term: 'Security personnel',
      q: '¿Qué significa «security personnel»?',
      a: 'Personal de seguridad: vigila el aeropuerto',
      note: 'Es incontable: «security personnel are…», sin s.' },
    { id: 'cp1-03-say', unit: 'cp1-03', type: 'num',
      q: 'No oíste bien el número de puerta de embarque. ¿Cómo lo aclaras?',
      a: 'Sorry, did you say gate fifteen or fifty?',
      options: ['Sorry, did you say gate fifteen or fifty?', 'Sorry, what you said, gate fifteen or fifty?', 'Repeat me the gate, please.', 'Sorry, you said me gate fifteen or fifty?'],
      say: 'Sorry, did you say gate fifteen or fifty?',
      note: '15 (fif-TEEN) y 50 (FIF-ty) se confunden mucho: el acento cae en sílabas distintas.' },
    { id: 'cp1-03-pairs', unit: 'cp1-03', type: 'match',
      q: 'Clarifying: aclarar información',
      pairs: [['Do you mean…?', '¿Quiere decir…?'],
              ['Could you repeat that?', '¿Podría repetirlo?'],
              ['Just to confirm…', 'Solo para confirmar…'],
              ['So, you’re saying…', 'Entonces, me dice que…']] },

    /* ───────────── 4 · Parts of the Airport ───────────── */
    { id: 'cp1-air-traffic-control-atc', unit: 'cp1-04', type: 'def', term: 'Air traffic control (ATC)',
      q: '¿Qué significa «air traffic control»?',
      a: 'Control de tránsito aéreo',
      say: 'Air traffic control' },
    { id: 'cp1-concourse', unit: 'cp1-04', type: 'def', term: 'Concourse',
      q: '¿Qué significa «concourse»?',
      a: 'Muelle de embarque: el vestíbulo donde están las puertas de embarque' },
    { id: 'cp1-control-tower', unit: 'cp1-04', type: 'def', term: 'Control tower',
      q: '¿Qué significa «control tower»?',
      a: 'Torre de control' },
    { id: 'cp1-customs', unit: 'cp1-04', type: 'def', term: 'Customs',
      q: '¿Qué significa «customs»?',
      a: 'Aduana',
      note: 'Ej.: “All arriving passengers must go through customs.”' },
    { id: 'cp1-gate', unit: 'cp1-04', type: 'def', term: 'Gate',
      q: '¿Qué significa «gate»?',
      a: 'Puerta de embarque',
      note: 'Ej.: “Flight 204 is now boarding at gate 12.”' },
    { id: 'cp1-restricted', unit: 'cp1-04', type: 'def', term: 'Restricted',
      q: '¿Qué significa «restricted»?',
      a: 'Restringido: solo para personal autorizado',
      note: 'Ej.: “Restricted area. Authorized personnel only.”' },
    { id: 'cp1-runway', unit: 'cp1-04', type: 'def', term: 'Runway',
      q: '¿Qué significa «runway»?',
      a: 'Pista (de despegue y aterrizaje)' },
    { id: 'cp1-security-checkpoint', unit: 'cp1-04', type: 'def', term: 'Security checkpoint',
      q: '¿Qué significa «security checkpoint»?',
      a: 'Filtro (control) de seguridad' },
    { id: 'cp1-taxiway', unit: 'cp1-04', type: 'def', term: 'Taxiway',
      q: '¿Qué significa «taxiway»?',
      a: 'Calle de rodaje: une la pista con la plataforma' },
    { id: 'cp1-terminal', unit: 'cp1-04', type: 'def', term: 'Terminal',
      q: '¿Qué significa «terminal»?',
      a: 'Terminal: el edificio de pasajeros' },
    { id: 'cp1-04-say', unit: 'cp1-04', type: 'num',
      q: 'Necesitas saber dónde se recoge el equipaje. ¿Cómo lo preguntas?',
      a: 'Excuse me, could you tell me where baggage claim is?',
      options: ['Excuse me, could you tell me where baggage claim is?', 'Excuse me, could you tell me where is baggage claim?', 'Excuse me, where baggage claim is?', 'Excuse me, you know where is baggage claim?'],
      say: 'Excuse me, could you tell me where baggage claim is?',
      note: 'En las preguntas indirectas («Could you tell me…») no se invierte el orden: «where it is», no «where is it».' },
    { id: 'cp1-04-pairs', unit: 'cp1-04', type: 'match',
      q: 'Asking for information: pedir información',
      pairs: [['Could you tell me…?', '¿Podría decirme…?'],
              ['Where can I find…?', '¿Dónde encuentro…?'],
              ['Do you know if…?', '¿Sabe si…?'],
              ['Which way is…?', '¿Por dónde se va a…?']] },

    /* ───────────── 5 · Airport Security ───────────── */
    { id: 'cp1-crew-lane', unit: 'cp1-05', type: 'def', term: 'Crew lane',
      q: '¿Qué significa «crew lane»?',
      a: 'Fila exclusiva para tripulantes en el filtro de seguridad' },
    { id: 'cp1-detect', unit: 'cp1-05', type: 'def', term: 'Detect',
      q: '¿Qué significa «detect»?',
      a: 'Detectar' },
    { id: 'cp1-explosive-detection', unit: 'cp1-05', type: 'def', term: 'Explosive detection',
      q: '¿Qué significa «explosive detection»?',
      a: 'Detección de explosivos',
      note: 'A veces pasan un hisopo por la maleta para buscar restos de explosivos.' },
    { id: 'cp1-identification', unit: 'cp1-05', type: 'def', term: 'Identification',
      q: '¿Qué significa «identification»?',
      a: 'Identificación (documento de identidad)',
      note: 'Se abrevia «ID»: “May I see your ID, please?”' },
    { id: 'cp1-metal-detector', unit: 'cp1-05', type: 'def', term: 'Metal detector',
      q: '¿Qué significa «metal detector»?',
      a: 'Detector de metales' },
    { id: 'cp1-pat-down', unit: 'cp1-05', type: 'def', term: 'Pat down',
      q: '¿Qué significa «pat down»?',
      a: 'Cacheo (registro manual)',
      note: 'Como verbo: “to pat someone down”.' },
    { id: 'cp1-prohibited', unit: 'cp1-05', type: 'def', term: 'Prohibited',
      q: '¿Qué significa «prohibited»?',
      a: 'Prohibido',
      note: 'Ej.: “Prohibited items will be confiscated.”' },
    { id: 'cp1-scan', unit: 'cp1-05', type: 'def', term: 'Scan',
      q: '¿Qué significa «scan»?',
      a: 'Escanear (revisar con un escáner)' },
    { id: 'cp1-scanner', unit: 'cp1-05', type: 'def', term: 'Scanner',
      q: '¿Qué significa «scanner»?',
      a: 'Escáner (de cuerpo o de equipaje)' },
    { id: 'cp1-x-ray-machine', unit: 'cp1-05', type: 'def', term: 'X-ray machine',
      q: '¿Qué significa «X-ray machine»?',
      a: 'Máquina de rayos X' },
    { id: 'cp1-05-say', unit: 'cp1-05', type: 'num',
      q: 'Le pediste por error a un pasajero que se quitara los zapatos. ¿Cómo te disculpas?',
      a: 'My apologies, that was my mistake.',
      options: ['My apologies, that was my mistake.', 'My apologise, it was my mistake.', 'I excuse me, it was my fault.', 'Sorry for my mistake of me.'],
      say: 'My apologies, that was my mistake.',
      note: '«Apology» es el sustantivo y «apologize», el verbo: «My apologies» o «I apologize».' },
    { id: 'cp1-05-pairs', unit: 'cp1-05', type: 'match',
      q: 'Apologizing: pedir disculpas',
      pairs: [['I apologize for…', 'Le pido disculpas por…'],
              ['I’m sorry about that', 'Lo siento mucho'],
              ['That was my mistake', 'Fue un error mío'],
              ['It won’t happen again', 'No volverá a pasar']] },

    /* ───────────── 6 · Parts of an Aircraft ───────────── */
    { id: 'cp1-aircraft', unit: 'cp1-06', type: 'def', term: 'Aircraft',
      q: '¿Qué significa «aircraft»?',
      a: 'Aeronave (avión)',
      note: 'Es igual en singular y en plural: “one aircraft, two aircraft”.' },
    { id: 'cp1-cabin-door', unit: 'cp1-06', type: 'def', term: 'Cabin door',
      q: '¿Qué significa «cabin door»?',
      a: 'Puerta de la cabina: por donde se embarca y desembarca' },
    { id: 'cp1-fuselage', unit: 'cp1-06', type: 'def', term: 'Fuselage',
      q: '¿Qué significa «fuselage»?',
      a: 'Fuselaje: el cuerpo principal del avión' },
    { id: 'cp1-landing-gear', unit: 'cp1-06', type: 'def', term: 'Landing gear',
      q: '¿Qué significa «landing gear»?',
      a: 'Tren de aterrizaje' },
    { id: 'cp1-nose', unit: 'cp1-06', type: 'def', term: 'Nose',
      q: '¿Qué significa «nose»?',
      a: 'Morro (nariz) del avión' },
    { id: 'cp1-tire', unit: 'cp1-06', type: 'def', term: 'Tire',
      q: '¿Qué significa «tire»?',
      a: 'Neumático (llanta)',
      note: 'En inglés británico se escribe «tyre».' },
    { id: 'cp1-turbine-engine', unit: 'cp1-06', type: 'def', term: 'Turbine engine',
      q: '¿Qué significa «turbine engine»?',
      a: 'Motor de turbina (reactor)' },
    { id: 'cp1-turboprop-engine', unit: 'cp1-06', type: 'def', term: 'Turboprop engine',
      q: '¿Qué significa «turboprop engine»?',
      a: 'Motor turbohélice: una turbina que mueve una hélice' },
    { id: 'cp1-wheel', unit: 'cp1-06', type: 'def', term: 'Wheel',
      q: '¿Qué significa «wheel»?',
      a: 'Rueda' },
    { id: 'cp1-wing', unit: 'cp1-06', type: 'def', term: 'Wing',
      q: '¿Qué significa «wing»?',
      a: 'Ala' },
    { id: 'cp1-06-say', unit: 'cp1-06', type: 'num',
      q: 'El mecánico menciona un problema con una rueda. ¿Cómo pides más detalles?',
      a: 'Could you tell me a little more about the problem?',
      options: ['Could you tell me a little more about the problem?', 'Could you tell me more little about the problem?', 'Can you say me more about the problem?', 'Tell me more of the problem, could you?'],
      say: 'Could you tell me a little more about the problem?',
      note: '«Say» no lleva a la persona detrás; con persona se usa «tell»: «tell me».' },
    { id: 'cp1-06-pairs', unit: 'cp1-06', type: 'match',
      q: 'Asking for more information: pedir más detalles',
      pairs: [['Can you be more specific?', '¿Puede ser más específico?'],
              ['What else should I know?', '¿Qué más debo saber?'],
              ['Could you explain that?', '¿Podría explicarlo?'],
              ['Anything else?', '¿Algo más?']] },

    /* ───────────── 7 · Parts of the Cabin 1 ───────────── */
    { id: 'cp1-aisle', unit: 'cp1-07', type: 'def', term: 'Aisle',
      q: '¿Qué significa «aisle»?',
      a: 'Pasillo',
      note: 'Se pronuncia “ail”: la s es muda.' },
    { id: 'cp1-business-class', unit: 'cp1-07', type: 'def', term: 'Business class',
      q: '¿Qué significa «business class»?',
      a: 'Clase ejecutiva (business)' },
    { id: 'cp1-cabin', unit: 'cp1-07', type: 'def', term: 'Cabin',
      q: '¿Qué significa «cabin»?',
      a: 'Cabina de pasajeros' },
    { id: 'cp1-center', unit: 'cp1-07', type: 'def', term: 'Center',
      q: '¿Qué significa «center»?',
      a: 'Centro: el asiento del medio',
      note: 'Ej.: “I have a center seat in row 22.” En inglés británico, «centre».' },
    { id: 'cp1-coach', unit: 'cp1-07', type: 'def', term: 'Coach',
      q: '¿Qué significa «coach»?',
      a: 'Clase turista (económica)',
      note: 'En EE. UU. se dice «coach»; también «economy class».' },
    { id: 'cp1-first-class', unit: 'cp1-07', type: 'def', term: 'First class',
      q: '¿Qué significa «first class»?',
      a: 'Primera clase' },
    { id: 'cp1-row', unit: 'cp1-07', type: 'def', term: 'Row',
      q: '¿Qué significa «row»?',
      a: 'Fila (de asientos)',
      note: 'Ej.: “Your seat is in row 14.”' },
    { id: 'cp1-seat', unit: 'cp1-07', type: 'def', term: 'Seat',
      q: '¿Qué significa «seat»?',
      a: 'Asiento' },
    { id: 'cp1-travel-class', unit: 'cp1-07', type: 'def', term: 'Travel class',
      q: '¿Qué significa «travel class»?',
      a: 'Clase de viaje: primera, ejecutiva o turista' },
    { id: 'cp1-window', unit: 'cp1-07', type: 'def', term: 'Window',
      q: '¿Qué significa «window»?',
      a: 'Ventanilla',
      note: 'Ej.: “Would you prefer a window or an aisle seat?”' },
    { id: 'cp1-07-say', unit: 'cp1-07', type: 'num',
      q: 'Una pasajera no alcanza el compartimento superior. ¿Qué le dices?',
      a: 'Would you like me to help you with that?',
      options: ['Would you like me to help you with that?', 'Do you want that I help you with that?', 'You want I help you with that?', 'Would you like that I help you?'],
      say: 'Would you like me to help you with that?',
      note: 'Tras «want» o «would like» va «me to help», no «that I help» (calco de «¿quiere que le ayude?»).' },
    { id: 'cp1-07-pairs', unit: 'cp1-07', type: 'match',
      q: 'Offering assistance: ofrecer ayuda',
      pairs: [['Can I help you?', '¿Le puedo ayudar?'],
              ['Let me get that for you', 'Yo se lo alcanzo'],
              ['Allow me', 'Permítame'],
              ['Can I help you find your seat?', '¿Le ayudo a encontrar su asiento?']] },

    /* ───────────── 8 · Parts of the Cabin 2 ───────────── */
    { id: 'cp1-cockpit', unit: 'cp1-08', type: 'def', term: 'Cockpit',
      q: '¿Qué significa «cockpit»?',
      a: 'Cabina de mando (de los pilotos)',
      note: 'Hoy las aerolíneas prefieren decir «flight deck».', syn: ['Flight deck'] },
    { id: 'cp1-compartment', unit: 'cp1-08', type: 'def', term: 'Compartment',
      q: '¿Qué significa «compartment»?',
      a: 'Compartimento: espacio cerrado para guardar cosas',
      syn: ['Overhead', 'Storage bin'] },
    { id: 'cp1-emergency-exit', unit: 'cp1-08', type: 'def', term: 'Emergency exit',
      q: '¿Qué significa «emergency exit»?',
      a: 'Salida de emergencia' },
    { id: 'cp1-exit-row', unit: 'cp1-08', type: 'def', term: 'Exit row',
      q: '¿Qué significa «exit row»?',
      a: 'Fila de salida de emergencia',
      note: 'Quien se sienta ahí debe poder y querer ayudar en una evacuación.' },
    { id: 'cp1-flight-deck', unit: 'cp1-08', type: 'def', term: 'Flight deck',
      q: '¿Qué significa «flight deck»?',
      a: 'Cabina de vuelo: nombre profesional de la cabina de mando',
      syn: ['Cockpit'] },
    { id: 'cp1-galley', unit: 'cp1-08', type: 'def', term: 'Galley',
      q: '¿Qué significa «galley»?',
      a: 'Galley: la cocina de a bordo' },
    { id: 'cp1-jumpseat', unit: 'cp1-08', type: 'def', term: 'Jumpseat',
      q: '¿Qué significa «jumpseat»?',
      a: 'Asiento plegable de la tripulación',
      note: 'También se escribe «jump seat».' },
    { id: 'cp1-lavatory', unit: 'cp1-08', type: 'def', term: 'Lavatory',
      q: '¿Qué significa «lavatory»?',
      a: 'Baño (lavabo) del avión',
      note: 'En la cabina se abrevia «lav».' },
    { id: 'cp1-overhead', unit: 'cp1-08', type: 'def', term: 'Overhead',
      q: '¿Qué significa «overhead»?',
      a: 'De arriba: «the overhead» es el compartimento sobre los asientos',
      note: 'Ej.: “Please place your bag in the overhead.”', syn: ['Compartment', 'Storage bin'] },
    { id: 'cp1-storage-bin', unit: 'cp1-08', type: 'def', term: 'Storage bin',
      q: '¿Qué significa «storage bin»?',
      a: 'Contenedor (cajón) para guardar objetos',
      syn: ['Compartment', 'Overhead'] },
    { id: 'cp1-08-say', unit: 'cp1-08', type: 'num',
      q: 'Quieres iniciar una charla amable con el pasajero de la fila de salida. ¿Qué dices?',
      a: 'Hi there! Are you heading home or traveling for work?',
      options: ['Hi there! Are you heading home or traveling for work?', 'Hi! Why you travel?', 'Hello. What is your motive of travel?', 'Hi! Where you are going?'],
      say: 'Hi there! Are you heading home or traveling for work?',
      note: '«Motivo del viaje» es «reason for travel»; en una charla, mejor preguntar directamente.' },
    { id: 'cp1-08-pairs', unit: 'cp1-08', type: 'match',
      q: 'Starting a conversation: romper el hielo',
      pairs: [['How’s your day going?', '¿Qué tal su día?'],
              ['Is this your first time in…?', '¿Es su primera vez en…?'],
              ['Where are you headed?', '¿Hacia dónde va?'],
              ['Nice weather today, isn’t it?', 'Qué buen tiempo hace hoy, ¿verdad?']] },

    /* ───────────── 9 · Physical Demands ───────────── */
    { id: 'cp1-confined-space', unit: 'cp1-09', type: 'def', term: 'Confined space',
      q: '¿Qué significa «confined space»?',
      a: 'Espacio reducido (confinado)' },
    { id: 'cp1-engine-noise', unit: 'cp1-09', type: 'def', term: 'Engine noise',
      q: '¿Qué significa «engine noise»?',
      a: 'Ruido de los motores' },
    { id: 'cp1-exposure', unit: 'cp1-09', type: 'def', term: 'Exposure',
      q: '¿Qué significa «exposure»?',
      a: 'Exposición (a radiación, gérmenes, cambios de presión…)' },
    { id: 'cp1-fatigue', unit: 'cp1-09', type: 'def', term: 'Fatigue',
      q: '¿Qué significa «fatigue»?',
      a: 'Fatiga (cansancio acumulado)',
      note: 'Se pronuncia “fa-TIIG”.' },
    { id: 'cp1-illness', unit: 'cp1-09', type: 'def', term: 'Illness',
      q: '¿Qué significa «illness»?',
      a: 'Enfermedad' },
    { id: 'cp1-lift', unit: 'cp1-09', type: 'def', term: 'Lift',
      q: '¿Qué significa «lift»?',
      a: 'Levantar (cargar peso)',
      note: 'Ej.: “Bend your knees when you lift heavy bags.” En inglés británico, «a lift» es también un ascensor.' },
    { id: 'cp1-physically-demanding', unit: 'cp1-09', type: 'def', term: 'Physically demanding',
      q: '¿Qué significa «physically demanding»?',
      a: 'Exigente físicamente (duro para el cuerpo)',
      syn: ['Strenuous'] },
    { id: 'cp1-size-restriction', unit: 'cp1-09', type: 'def', term: 'Size restriction',
      q: '¿Qué significa «size restriction»?',
      a: 'Restricción de talla: estatura o alcance mínimo y máximo',
      note: 'Muchas aerolíneas piden alcanzar cierta altura con el brazo (el «reach test»).' },
    { id: 'cp1-strenuous', unit: 'cp1-09', type: 'def', term: 'Strenuous',
      q: '¿Qué significa «strenuous»?',
      a: 'Agotador: que exige un gran esfuerzo',
      syn: ['Physically demanding'] },
    { id: 'cp1-09-say', unit: 'cp1-09', type: 'num',
      q: 'Un compañero dice que el trabajo de auxiliar es fácil. ¿Cómo discrepas con educación?',
      a: 'I see your point, but I don’t really agree.',
      options: ['I see your point, but I don’t really agree.', 'I am not agree with you.', 'I don’t agree you, it’s not easy.', 'You have not reason.'],
      say: 'I see your point, but I don’t really agree.',
      note: '«Agree» es un verbo: «I don’t agree», nunca «I am not agree». Y «tener razón» es «to be right».' },
    { id: 'cp1-09-pairs', unit: 'cp1-09', type: 'match',
      q: 'Disagreeing: expresar desacuerdo',
      pairs: [['I’m not so sure about that', 'No estoy tan seguro de eso'],
              ['I see it differently', 'Yo lo veo distinto'],
              ['That’s true, but…', 'Es cierto, pero…'],
              ['I’m afraid I disagree', 'Me temo que no estoy de acuerdo']] },

    /* ───────────── 10 · Appearance Guidelines ───────────── */
    { id: 'cp1-appearance', unit: 'cp1-10', type: 'def', term: 'Appearance',
      q: '¿Qué significa «appearance»?',
      a: 'Apariencia, aspecto (imagen personal)' },
    { id: 'cp1-body-piercing', unit: 'cp1-10', type: 'def', term: 'Body piercing',
      q: '¿Qué significa «body piercing»?',
      a: 'Piercing (perforación en el cuerpo)' },
    { id: 'cp1-bracelet', unit: 'cp1-10', type: 'def', term: 'Bracelet',
      q: '¿Qué significa «bracelet»?',
      a: 'Pulsera (brazalete)' },
    { id: 'cp1-earring', unit: 'cp1-10', type: 'def', term: 'Earring',
      q: '¿Qué significa «earring»?',
      a: 'Arete (pendiente)' },
    { id: 'cp1-facial-hair', unit: 'cp1-10', type: 'def', term: 'Facial hair',
      q: '¿Qué significa «facial hair»?',
      a: 'Vello facial: barba y bigote',
      note: 'Ej.: “Facial hair must be neatly trimmed.”' },
    { id: 'cp1-grooming', unit: 'cp1-10', type: 'def', term: 'Grooming',
      q: '¿Qué significa «grooming»?',
      a: 'Arreglo e higiene personal',
      note: 'Ej.: “Good grooming is part of the uniform.”' },
    { id: 'cp1-jewelry', unit: 'cp1-10', type: 'def', term: 'Jewelry',
      q: '¿Qué significa «jewelry»?',
      a: 'Joyas',
      note: 'Es incontable: «a piece of jewelry». En inglés británico, «jewellery».' },
    { id: 'cp1-makeup', unit: 'cp1-10', type: 'def', term: 'Makeup',
      q: '¿Qué significa «makeup»?',
      a: 'Maquillaje' },
    { id: 'cp1-necklace', unit: 'cp1-10', type: 'def', term: 'Necklace',
      q: '¿Qué significa «necklace»?',
      a: 'Collar' },
    { id: 'cp1-ring', unit: 'cp1-10', type: 'def', term: 'Ring',
      q: '¿Qué significa «ring»?',
      a: 'Anillo',
      note: 'Ej.: “a wedding ring” (anillo de bodas).' },
    { id: 'cp1-tattoo', unit: 'cp1-10', type: 'def', term: 'Tattoo',
      q: '¿Qué significa «tattoo»?',
      a: 'Tatuaje' },
    { id: 'cp1-tie-bar', unit: 'cp1-10', type: 'def', term: 'Tie bar',
      q: '¿Qué significa «tie bar»?',
      a: 'Pisacorbata (prendedor de corbata)' },
    { id: 'cp1-10-rules', unit: 'cp1-10', type: 'list',
      q: 'Normas de imagen habituales (appearance guidelines)',
      items: ['Neatly trimmed facial hair', 'A tie bar with the uniform tie', 'No visible tattoos'],
      lures: ['Several necklaces at once', 'Facial piercings', 'Untidy hair'] },
    { id: 'cp1-10-say', unit: 'cp1-10', type: 'num',
      q: 'Tu compañera lleva demasiadas pulseras. ¿Cómo le sugieres quitarse una?',
      a: 'Why don’t you take one of those bracelets off?',
      options: ['Why don’t you take one of those bracelets off?', 'Why you don’t take off one bracelet?', 'I suggest you to take off a bracelet.', 'You should to take off one bracelet.'],
      say: 'Why don’t you take one of those bracelets off?',
      note: 'Se dice «I suggest (that) you take off…» o «You should take off…», sin «to».' },
    { id: 'cp1-10-pairs', unit: 'cp1-10', type: 'match',
      q: 'Making suggestions: hacer sugerencias',
      pairs: [['I suggest you…', 'Te sugiero que…'],
              ['Why don’t you…?', '¿Por qué no…?'],
              ['You might want to…', 'Quizá te convenga…'],
              ['How about…?', '¿Qué tal si…?']] },

    /* ───────────── 11 · Uniforms ───────────── */
    { id: 'cp1-blouse', unit: 'cp1-11', type: 'def', term: 'Blouse',
      q: '¿Qué significa «blouse»?',
      a: 'Blusa' },
    { id: 'cp1-dress-shirt', unit: 'cp1-11', type: 'def', term: 'Dress shirt',
      q: '¿Qué significa «dress shirt»?',
      a: 'Camisa de vestir' },
    { id: 'cp1-id-badge', unit: 'cp1-11', type: 'def', term: 'ID badge',
      q: '¿Qué significa «ID badge»?',
      a: 'Gafete (credencial de identificación)',
      note: 'Ej.: “Your ID badge must be visible at all times.”', say: 'I D badge' },
    { id: 'cp1-image', unit: 'cp1-11', type: 'def', term: 'Image',
      q: '¿Qué significa «image»?',
      a: 'Imagen: cómo te percibe el público',
      note: 'Ej.: “The uniform is part of the airline’s image.”' },
    { id: 'cp1-jacket', unit: 'cp1-11', type: 'def', term: 'Jacket',
      q: '¿Qué significa «jacket»?',
      a: 'Chaqueta (saco)' },
    { id: 'cp1-regulation', unit: 'cp1-11', type: 'def', term: 'Regulation',
      q: '¿Qué significa «regulation»?',
      a: 'Norma, reglamento',
      note: 'Ej.: “uniform regulations”. Como adjetivo: “regulation shoes” (zapatos reglamentarios).' },
    { id: 'cp1-skirt', unit: 'cp1-11', type: 'def', term: 'Skirt',
      q: '¿Qué significa «skirt»?',
      a: 'Falda' },
    { id: 'cp1-slacks', unit: 'cp1-11', type: 'def', term: 'Slacks',
      q: '¿Qué significa «slacks»?',
      a: 'Pantalón de vestir' },
    { id: 'cp1-stockings', unit: 'cp1-11', type: 'def', term: 'Stockings',
      q: '¿Qué significa «stockings»?',
      a: 'Medias' },
    { id: 'cp1-tie', unit: 'cp1-11', type: 'def', term: 'Tie',
      q: '¿Qué significa «tie»?',
      a: 'Corbata' },
    { id: 'cp1-uniform', unit: 'cp1-11', type: 'def', term: 'Uniform',
      q: '¿Qué significa «uniform»?',
      a: 'Uniforme' },
    { id: 'cp1-wings', unit: 'cp1-11', type: 'def', term: 'Wings',
      q: '¿Qué significa «wings»?',
      a: 'Alas: la insignia con alas del uniforme',
      note: 'Se reciben al terminar el curso: “to earn your wings”.' },
    { id: 'cp1-11-say', unit: 'cp1-11', type: 'num',
      q: 'Le explicas a un auxiliar nuevo un error frecuente con el uniforme. ¿Qué frase es correcta?',
      a: 'A common mistake is wearing the ID badge on the wrong side.',
      options: ['A common mistake is wearing the ID badge on the wrong side.', 'A common mistake is wear the ID badge on the wrong side.', 'A common error is to wearing the ID badge in the wrong side.', 'A mistake common is wearing the ID badge on the wrong side.'],
      say: 'A common mistake is wearing the ID badge on the wrong side.',
      note: 'Tras «is» va el gerundio o «to» + verbo: «A common mistake is wearing…» o «…is to wear…».' },
    { id: 'cp1-11-pairs', unit: 'cp1-11', type: 'match',
      q: 'Common errors: hablar de errores frecuentes',
      pairs: [['A common mistake is…', 'Un error frecuente es…'],
              ['People often forget to…', 'La gente suele olvidar…'],
              ['Make sure you don’t…', 'Asegúrate de no…'],
              ['Be careful not to…', 'Ten cuidado de no…']] },

    /* ───────────── 12 · Types of Flights ───────────── */
    { id: 'cp1-charter', unit: 'cp1-12', type: 'def', term: 'Charter',
      q: '¿Qué significa «charter»?',
      a: 'Vuelo chárter: avión contratado por un grupo o una empresa' },
    { id: 'cp1-connection', unit: 'cp1-12', type: 'def', term: 'Connection',
      q: '¿Qué significa «connection»?',
      a: 'Conexión: cambio de avión para seguir el viaje' },
    { id: 'cp1-direct-flight', unit: 'cp1-12', type: 'def', term: 'Direct flight',
      q: '¿Qué significa «direct flight»?',
      a: 'Vuelo directo: mismo número de vuelo, aunque haga escalas sin cambiar de avión',
      note: 'No es lo mismo que «non-stop» (sin ninguna escala).' },
    { id: 'cp1-domestic', unit: 'cp1-12', type: 'def', term: 'Domestic',
      q: '¿Qué significa «domestic»?',
      a: 'Nacional (doméstico): dentro del mismo país',
      note: 'Ej.: “the domestic terminal”.' },
    { id: 'cp1-flight', unit: 'cp1-12', type: 'def', term: 'Flight',
      q: '¿Qué significa «flight»?',
      a: 'Vuelo' },
    { id: 'cp1-intercontinental', unit: 'cp1-12', type: 'def', term: 'Intercontinental',
      q: '¿Qué significa «intercontinental»?',
      a: 'Intercontinental: entre continentes' },
    { id: 'cp1-international', unit: 'cp1-12', type: 'def', term: 'International',
      q: '¿Qué significa «international»?',
      a: 'Internacional' },
    { id: 'cp1-layover', unit: 'cp1-12', type: 'def', term: 'Layover',
      q: '¿Qué significa «layover»?',
      a: 'Escala: parada entre dos vuelos',
      note: 'Para la tripulación, también es la estancia en otra ciudad entre vuelos.' },
    { id: 'cp1-long-haul', unit: 'cp1-12', type: 'def', term: 'Long-haul',
      q: '¿Qué significa «long-haul»?',
      a: 'De largo recorrido (larga distancia)' },
    { id: 'cp1-non-stop', unit: 'cp1-12', type: 'def', term: 'Non-stop',
      q: '¿Qué significa «non-stop»?',
      a: 'Sin escalas' },
    { id: 'cp1-short-haul', unit: 'cp1-12', type: 'def', term: 'Short-haul',
      q: '¿Qué significa «short-haul»?',
      a: 'De corto recorrido (corta distancia)' },
    { id: 'cp1-12-opposites', unit: 'cp1-12', type: 'match',
      q: 'Une cada tipo de vuelo con su contrario',
      pairs: [['Short-haul', 'Long-haul'],
              ['Domestic', 'International'],
              ['Non-stop', 'With a connection'],
              ['Scheduled', 'Charter']] },
    { id: 'cp1-12-say', unit: 'cp1-12', type: 'num',
      q: 'Le explicas a un compañero el itinerario de mañana. ¿Qué frase es correcta?',
      a: 'We depart at 6:40 and arrive in Lima at 11:15.',
      options: ['We depart at 6:40 and arrive in Lima at 11:15.', 'We are depart at 6:40 and arrive to Lima at 11:15.', 'We will departing at 6:40 and arrive at Lima 11:15.', 'We departs at 6:40 and arrives in Lima at 11:15.'],
      say: 'We depart at 6:40 and arrive in Lima at 11:15.',
      note: 'Para horarios fijos se usa el presente simple. Y se llega «in» una ciudad, no «to».' },
    { id: 'cp1-12-pairs', unit: 'cp1-12', type: 'match',
      q: 'Plans and schedules: planes y horarios',
      pairs: [['We’re scheduled to…', 'Está previsto que…'],
              ['The flight leaves at…', 'El vuelo sale a las…'],
              ['We have a two-hour layover in…', 'Tenemos una escala de dos horas en…'],
              ['After that, we fly on to…', 'Después seguimos hacia…']] },

    /* ───────────── 13 · Types of Aircraft ───────────── */
    { id: 'cp1-air-taxi', unit: 'cp1-13', type: 'def', term: 'Air taxi',
      q: '¿Qué significa «air taxi»?',
      a: 'Aerotaxi: avión pequeño que vuela bajo demanda' },
    { id: 'cp1-cabin-class', unit: 'cp1-13', type: 'def', term: 'Cabin class',
      q: '¿Qué significa «cabin class»?',
      a: 'Bimotor de cabina: avioneta de dos motores con cabina de pasajeros, típica de vuelos chárter' },
    { id: 'cp1-commuterliner', unit: 'cp1-13', type: 'def', term: 'Commuterliner',
      q: '¿Qué significa «commuterliner»?',
      a: 'Avión de cercanías: pequeño avión comercial de hasta 19 plazas para trayectos cortos' },
    { id: 'cp1-feederliner', unit: 'cp1-13', type: 'def', term: 'Feederliner',
      q: '¿Qué significa «feederliner»?',
      a: 'Avión alimentador: lleva pasajeros de aeropuertos pequeños a un gran aeropuerto (hub)' },
    { id: 'cp1-narrow-body-airliner', unit: 'cp1-13', type: 'def', term: 'Narrow-body airliner',
      q: '¿Qué significa «narrow-body airliner»?',
      a: 'Avión de fuselaje estrecho: un solo pasillo',
      note: 'Ej.: Airbus A320 o Boeing 737.' },
    { id: 'cp1-regional-airliner', unit: 'cp1-13', type: 'def', term: 'Regional airliner',
      q: '¿Qué significa «regional airliner»?',
      a: 'Avión regional: avión de pasajeros mediano para rutas entre ciudades cercanas',
      syn: ['Regional jet'] },
    { id: 'cp1-regional-jet', unit: 'cp1-13', type: 'def', term: 'Regional jet',
      q: '¿Qué significa «regional jet»?',
      a: 'Jet regional: reactor de pasajeros pequeño para rutas regionales',
      note: 'Ej.: Embraer E190 o Bombardier CRJ.', syn: ['Regional airliner'] },
    { id: 'cp1-turbofan', unit: 'cp1-13', type: 'def', term: 'Turbofan',
      q: '¿Qué significa «turbofan»?',
      a: 'Turbofán: el motor a reacción de los aviones comerciales' },
    { id: 'cp1-turboprop', unit: 'cp1-13', type: 'def', term: 'Turboprop',
      q: '¿Qué significa «turboprop»?',
      a: 'Avión turbohélice',
      note: 'Ej.: ATR 72 o Dash 8.' },
    { id: 'cp1-wide-body-airliner', unit: 'cp1-13', type: 'def', term: 'Wide-body airliner',
      q: '¿Qué significa «wide-body airliner»?',
      a: 'Avión de fuselaje ancho: dos pasillos',
      note: 'Ej.: Boeing 787 o Airbus A350.' },
    { id: 'cp1-13-say', unit: 'cp1-13', type: 'num',
      q: 'Tienes que terminar una charla con un pasajero para seguir con el servicio. ¿Qué dices?',
      a: 'It was nice talking to you. I’d better get back to work.',
      options: ['It was nice talking to you. I’d better get back to work.', 'Okay, I go now. Bye.', 'I must to go back to work now.', 'Was nice to talk you.'],
      say: 'It was nice talking to you. I’d better get back to work.',
      note: '«I’d better…» = «más vale que…»: una forma amable de despedirse.' },
    { id: 'cp1-13-pairs', unit: 'cp1-13', type: 'match',
      q: 'Ending a conversation: despedirse',
      pairs: [['It was nice talking to you', 'Fue un gusto hablar con usted'],
              ['I’d better get going', 'Será mejor que me vaya'],
              ['Let me know if you need anything', 'Avíseme si necesita algo'],
              ['Enjoy the rest of your flight', 'Disfrute el resto del vuelo']] },

    /* ───────────── 14 · Radio Communications ───────────── */
    { id: 'cp1-affirmative', unit: 'cp1-14', type: 'def', term: 'Affirmative',
      q: '¿Qué significa «affirmative»?',
      a: 'Afirmativo (sí)',
      note: 'La OACI recomienda «affirm»; «affirmative» es común en EE. UU.' },
    { id: 'cp1-callsign', unit: 'cp1-14', type: 'def', term: 'Callsign',
      q: '¿Qué significa «callsign»?',
      a: 'Indicativo (distintivo de llamada) de un avión',
      note: 'Ej.: “Avianca five eight one”.' },
    { id: 'cp1-mayday', unit: 'cp1-14', type: 'def', term: 'Mayday',
      q: '¿Qué significa «Mayday»?',
      a: 'Mayday: llamada de socorro por peligro grave e inminente',
      note: 'Se repite tres veces. Para urgencias menos graves se usa «pan-pan».' },
    { id: 'cp1-negative', unit: 'cp1-14', type: 'def', term: 'Negative',
      q: '¿Qué significa «negative»?',
      a: 'Negativo (no)' },
    { id: 'cp1-phonetic-alphabet', unit: 'cp1-14', type: 'def', term: 'Phonetic alphabet',
      q: '¿Qué significa «phonetic alphabet»?',
      a: 'Alfabeto fonético: Alfa, Bravo, Charlie…' },
    { id: 'cp1-plain-english', unit: 'cp1-14', type: 'def', term: 'Plain English',
      q: '¿Qué significa «plain English»?',
      a: 'Inglés sencillo: lenguaje claro cuando la fraseología no alcanza' },
    { id: 'cp1-roger', unit: 'cp1-14', type: 'def', term: 'Roger',
      q: '¿Qué significa «Roger»?',
      a: 'Recibido: he recibido todo el mensaje' },
    { id: 'cp1-over', unit: 'cp1-14', type: 'def', term: 'Over',
      q: '¿Qué significa «over»?',
      a: 'Cambio: terminé de hablar y espero respuesta',
      note: '«Over and out» es de película: «out» significa que ya no esperas respuesta.' },
    { id: 'cp1-standby', unit: 'cp1-14', type: 'def', term: 'Standby',
      q: '¿Qué significa «standby»?',
      a: 'Espere (aguarde)' },
    { id: 'cp1-unable', unit: 'cp1-14', type: 'def', term: 'Unable',
      q: '¿Qué significa «unable»?',
      a: 'No puedo cumplir (imposible)',
      note: 'Ej.: “Unable, due to weather.”' },
    { id: 'cp1-14-say', unit: 'cp1-14', type: 'num',
      q: 'Llamas a la cabina de mando por el interfono y nadie responde. ¿Qué dices?',
      a: 'Flight deck, this is the cabin. Can you hear me?',
      options: ['Flight deck, this is the cabin. Can you hear me?', 'Flight deck, this is the cabin. You hear me?', 'Flight deck, here the cabin. Are you listening me?', 'Flight deck, it is the cabin. Hear you me?'],
      say: 'Flight deck, this is the cabin. Can you hear me?',
      note: '«Listen» lleva «to» («listen to me»). Para comprobar que te oyen: «Can you hear me?» o «Do you read me?».' },
    { id: 'cp1-14-pairs', unit: 'cp1-14', type: 'match',
      q: 'Prompting a response: pedir una respuesta',
      pairs: [['Do you read me?', '¿Me recibe?'],
              ['Please confirm', 'Confirme, por favor'],
              ['Did you copy?', '¿Lo copió?'],
              ['Awaiting your reply', 'Espero su respuesta']] },

    /* ───────────── 15 · Delays and Cancellations ───────────── */
    { id: 'cp1-air-traffic', unit: 'cp1-15', type: 'def', term: 'Air traffic',
      q: '¿Qué significa «air traffic»?',
      a: 'Tránsito (tráfico) aéreo' },
    { id: 'cp1-cancellation', unit: 'cp1-15', type: 'def', term: 'Cancellation',
      q: '¿Qué significa «cancellation»?',
      a: 'Cancelación' },
    { id: 'cp1-congestion', unit: 'cp1-15', type: 'def', term: 'Congestion',
      q: '¿Qué significa «congestion»?',
      a: 'Congestión: saturación de tráfico' },
    { id: 'cp1-de-ice', unit: 'cp1-15', type: 'def', term: 'De-ice',
      q: '¿Qué significa «de-ice»?',
      a: 'Deshielar: quitar el hielo del avión',
      note: 'El hielo en las alas reduce la sustentación; por eso se quita antes de despegar.' },
    { id: 'cp1-delay', unit: 'cp1-15', type: 'def', term: 'Delay',
      q: '¿Qué significa «delay»?',
      a: 'Retraso (demora)' },
    { id: 'cp1-lightning', unit: 'cp1-15', type: 'def', term: 'Lightning',
      q: '¿Qué significa «lightning»?',
      a: 'Rayos (relámpagos)',
      note: 'Ojo: «lightning» (rayos) no es «lighting» (iluminación).' },
    { id: 'cp1-mechanical-failure', unit: 'cp1-15', type: 'def', term: 'Mechanical failure',
      q: '¿Qué significa «mechanical failure»?',
      a: 'Falla mecánica (avería)' },
    { id: 'cp1-snow', unit: 'cp1-15', type: 'def', term: 'Snow',
      q: '¿Qué significa «snow»?',
      a: 'Nieve' },
    { id: 'cp1-storm', unit: 'cp1-15', type: 'def', term: 'Storm',
      q: '¿Qué significa «storm»?',
      a: 'Tormenta' },
    { id: 'cp1-unsafe', unit: 'cp1-15', type: 'def', term: 'Unsafe',
      q: '¿Qué significa «unsafe»?',
      a: 'Inseguro, peligroso' },
    { id: 'cp1-15-weather', unit: 'cp1-15', type: 'list',
      q: 'Causas meteorológicas de un retraso',
      items: ['Snow', 'Lightning', 'Storms'],
      lures: ['Congestion', 'Mechanical failure', 'A full flight'] },
    { id: 'cp1-15-pa', unit: 'cp1-15', type: 'order',
      q: 'Ordena el anuncio de un retraso',
      steps: ['Ladies and gentlemen, this is the purser speaking.',
              'Unfortunately, there will be a short delay.',
              'The airport is congested and we are waiting for our turn to take off.',
              'We expect to be on our way in about twenty minutes.',
              'Thank you for your patience.'] },
    { id: 'cp1-15-say', unit: 'cp1-15', type: 'num',
      q: 'Una pasajera teme perder su conexión por el retraso. ¿Cómo la tranquilizas?',
      a: 'Please don’t worry. Our ground staff will help you rebook.',
      options: ['Please don’t worry. Our ground staff will help you rebook.', 'Don’t worry, is no problem.', 'No worry, the staff help you.', 'Not to worry you, they will rebook.'],
      say: 'Please don’t worry. Our ground staff will help you rebook.',
      note: 'En inglés el sujeto no se omite: «it’s no problem», no «is no problem».' },
    { id: 'cp1-15-pairs', unit: 'cp1-15', type: 'match',
      q: 'Providing reassurance: tranquilizar',
      pairs: [['Please don’t worry', 'No se preocupe, por favor'],
              ['Everything is under control', 'Todo está bajo control'],
              ['We’ll take care of it', 'Nosotros nos encargamos'],
              ['You’re in good hands', 'Está en buenas manos']] }
  ]
};
