/* Contenido del Examen Final de Tripulante de Cabina (TCP).
   Cada ficha conserva su referencia al número de pregunta del examen original. */
window.CC = window.CC || {};

CC.UNITS = [
  { id: 'vuelo',  name: 'Teoría de vuelo',        icon: '✈️', hue: 205, blurb: 'Aerodinámica, ejes y sustentación' },
  { id: 'meteo',  name: 'Presión y meteorología', icon: '🌦️', hue: 190, blurb: 'Aire acondicionado, atmósfera y nubes' },
  { id: 'nav',    name: 'Navegación',             icon: '🧭', hue: 260, blurb: 'VFR, latitud, longitud y día civil' },
  { id: 'norma',  name: 'Normativa aérea',        icon: '📜', hue: 35,  blurb: 'OACI, anexos, IATA y RAC' },
  { id: 'proc',   name: 'Procedimientos',         icon: '🧑‍✈️', hue: 340, blurb: 'Demo, briefing, jerarquía y cabina' },
  { id: 'equipo', name: 'Equipos de la aeronave', icon: '🛠️', hue: 220, blurb: 'PSU, APU, FAP y luces de llamado' },
  { id: 'emer',   name: 'Emergencias y fuego',    icon: '🧯', hue: 12,  blurb: 'Extintores, descompresión y oxígeno' },
  { id: 'surv',   name: 'Supervivencia',          icon: '🛟', hue: 160, blurb: 'Chaleco, balsa, ELT y señales' },
  { id: 'avsec',  name: 'Seguridad (AVSEC)',      icon: '🛡️', hue: 280, blurb: 'Amenazas, DEPA/DEPU y mercancías' },
  { id: 'pa',     name: 'Primeros auxilios',      icon: '🩺', hue: 145, blurb: 'Signos vitales, RCP y protocolos' }
];

/* type: def | num | list | order | match */
CC.CARDS = [
  /* ───────────── Teoría de vuelo ───────────── */
  { id: 'v1', unit: 'vuelo', type: 'def', ref: 1, term: 'Aerodinámica',
    q: '¿Qué es la aerodinámica?',
    a: 'Es la parte que estudia el comportamiento de los objetos cuando se mueven en el aire.' },
  { id: 'v2', unit: 'vuelo', type: 'list', ref: 2,
    q: 'Las 2 razones básicas para que un avión vuele',
    items: ['La forma aerodinámica de las alas', 'La fuerza impulsora de los motores'],
    lures: ['El peso del combustible a bordo', 'La presurización de la cabina', 'El viento de cola en crucero', 'La altitud del aeródromo'] },
  { id: 'v3', unit: 'vuelo', type: 'def', ref: 3, term: 'Envergadura',
    q: '¿Qué es la envergadura?',
    a: 'Es la distancia entre las puntas de las alas.' },
  { id: 'v4', unit: 'vuelo', type: 'def', ref: 3, term: 'Cuerda',
    q: '¿Qué es la cuerda?',
    a: 'Es la distancia entre el borde de salida y el punto del borde de ataque donde la cuerda se interseca con este último.' },
  { id: 'v5', unit: 'vuelo', type: 'def', ref: 3, term: 'Espesor',
    q: '¿Qué es el espesor?',
    a: 'Es la distancia entre la parte superior (extradós) y la parte inferior (intradós) del ala.' },
  { id: 'v6', unit: 'vuelo', type: 'def', ref: 4, term: 'Centro de gravedad',
    q: '¿Qué es el centro de gravedad?',
    a: 'Es el punto donde se unen los 3 ejes del avión.' },
  { id: 'v7', unit: 'vuelo', type: 'def', ref: 5, term: 'Teoría de vuelo',
    q: '¿Por qué vuela un aeroplano siendo más pesado que el aire?',
    a: 'Porque el simple hecho de moverse a través del aire desarrolla la fuerza de sustentación necesaria.' },

  /* ───────────── Presión y meteorología ───────────── */
  { id: 'm1', unit: 'meteo', type: 'def', ref: 6, term: 'Sistema de aire acondicionado',
    q: '¿Qué hace el sistema de aire acondicionado?',
    a: 'Es el que proporciona aire nuevo a toda la cabina.' },
  { id: 'm2', unit: 'meteo', type: 'def', ref: 6, term: 'Fuselaje',
    q: 'En cuanto a presurización, ¿qué caracteriza al fuselaje?',
    a: 'Es resistente al diferencial de presión.' },
  { id: 'm3', unit: 'meteo', type: 'def', ref: 6, term: 'Válvula de escape',
    q: '¿Cuál es la función de la válvula de escape?',
    a: 'Deja salir parte del aire de la cabina.' },
  { id: 'm4', unit: 'meteo', type: 'def', ref: 7, term: 'Meteorología',
    q: '¿Qué es la meteorología?',
    a: 'Es la parte de la física que trata de los fenómenos atmosféricos.' },
  { id: 'm5', unit: 'meteo', type: 'def', ref: 8, term: 'La atmósfera',
    q: '¿Qué es la atmósfera?',
    a: 'Es la masa de aire que rodea la Tierra y donde aún se hace efectiva la fuerza de gravedad terrestre.' },
  { id: 'm6', unit: 'meteo', type: 'def', ref: 9, term: 'Presión atmosférica',
    q: '¿Qué es la presión atmosférica?',
    a: 'Es el peso del aire sobre la superficie de la Tierra.' },
  { id: 'm7', unit: 'meteo', type: 'def', ref: 10, term: 'Cumulonimbo',
    q: '¿Qué nube no puede atravesar ningún avión y por qué?',
    a: 'El cumulonimbo: debido a que tiene tormentas y hielo, ningún avión puede atravesarlo.' },

  /* ───────────── Navegación ───────────── */
  { id: 'n1', unit: 'nav', type: 'def', ref: 11, term: 'Navegación',
    q: '¿Qué es la navegación?',
    a: 'Es la habilidad de trasladarse de un lugar a otro de la Tierra siguiendo el mejor camino de una manera rápida, segura y eficaz.' },
  { id: 'n2', unit: 'nav', type: 'def', ref: 12, term: 'Navegación observada',
    q: '¿Qué es la navegación observada?',
    a: 'Es el método de navegar de un sitio a otro por medio de la observación de puntos visibles en el terreno (vías férreas, estaciones, pueblos, caminos, ríos) y luego ubicar dicho punto sobre una carta aeronáutica.' },
  { id: 'n3', unit: 'nav', type: 'def', ref: 13, term: 'VFR',
    q: '¿Qué significa VFR?',
    a: 'Visual Flight Rules (Reglas de Vuelo Visual).' },
  { id: 'n4', unit: 'nav', type: 'def', ref: 14, term: 'Día civil',
    q: '¿Qué es el día civil?',
    a: 'Es el tiempo que comienza a la medianoche y termina a la medianoche del día siguiente. Se usa en casi todos los países.' },
  { id: 'n5', unit: 'nav', type: 'def', ref: 15, term: 'Latitud',
    q: '¿Qué es la latitud?',
    a: 'Es la distancia medida en grados entre un lugar cualquiera de la superficie terrestre y el Ecuador.' },
  { id: 'n6', unit: 'nav', type: 'def', ref: 16, term: 'Longitud',
    q: '¿Qué es la longitud?',
    a: 'Es la distancia expresada en grados desde el meridiano que pasa por ese lugar hasta el meridiano de Greenwich.' },

  /* ───────────── Normativa ───────────── */
  { id: 'r1', unit: 'norma', type: 'def', ref: 17, term: 'OACI',
    q: '¿De qué se encarga la OACI?',
    a: 'A su cargo se encuentra el ordenamiento del desarrollo técnico y económico de la aviación mundial.' },
  { id: 'r2', unit: 'norma', type: 'def', ref: 18, term: 'Anexo 6',
    q: '¿De qué trata el Anexo 6?',
    a: 'Trata del transporte aéreo comercial internacional — Aviones.' },
  { id: 'r3', unit: 'norma', type: 'def', ref: 19, term: 'Anexo 1',
    q: '¿Cuál es el Anexo 1?',
    a: 'Licencias al personal.' },
  { id: 'r4', unit: 'norma', type: 'def', ref: 20, term: 'IATA',
    q: '¿Qué es la IATA?',
    a: 'Es el instrumento para la cooperación entre aerolíneas, promoviendo la seguridad, fiabilidad, confianza y economía en el transporte aéreo en beneficio de los consumidores.' },
  { id: 'r5', unit: 'norma', type: 'num', ref: 20,
    q: '¿Dónde y cuándo fue fundada la IATA?',
    a: 'En La Habana, Cuba, en abril de 1945',
    options: ['En La Habana, Cuba, en abril de 1945', 'En Chicago, EE. UU., en diciembre de 1944', 'En Montreal, Canadá, en abril de 1947', 'En Varsovia, Polonia, en octubre de 1929'] },
  { id: 'r6', unit: 'norma', type: 'def', ref: 59, term: 'RAC 17',
    q: '¿Qué RAC habla de la seguridad de la aviación civil?',
    a: 'El RAC 17.' },

  /* ───────────── Procedimientos de cabina ───────────── */
  { id: 'p1', unit: 'proc', type: 'order', ref: 21,
    q: 'Procedimiento con un pasajero sentado en la salida de emergencia',
    steps: [
      'Informar al pasajero que va sentado en una salida de emergencia y que deberá colaborar con la tripulación en caso de emergencia. Si no acepta, se le debe reubicar.',
      'Informar que dicha salida sólo debe ser abierta cuando lo indique la tripulación.',
      'Informar que antes de abrir la salida se debe esperar a que la aeronave se detenga por completo y verificar las condiciones exteriores (no fuego, en amarizaje que el agua no rebase la ventanilla, no escombros, no barrancos).',
      'Si existiera alguna duda del procedimiento, recomendarle que lea la tarjeta de emergencia.'
    ] },
  { id: 'p2', unit: 'proc', type: 'list', ref: 22,
    q: 'Elementos que debe incluir la demostración de seguridad (demo)',
    items: ['Uso del cinturón de seguridad', 'Uso del oxígeno suplementario', 'Tarjeta de seguridad o emergencia',
            'Cantidad y ubicación de salidas de emergencia y luces de emergencia', 'Uso del chaleco salvavidas'],
    lures: ['Uso del carro de servicio', 'Ubicación del APU', 'Manejo del extintor de halón', 'Uso de la máscara Puritan-Bennett'] },
  { id: 'p3', unit: 'proc', type: 'num', ref: 23,
    q: '¿A partir de qué distancia de la costa se considera sobrevuelo de agua (con equipo de flotación)?',
    a: 'A más de 50 millas náuticas de la costa',
    options: ['A más de 50 millas náuticas de la costa', 'A más de 25 millas náuticas de la costa', 'A más de 100 millas náuticas de la costa', 'A más de 12 millas náuticas de la costa'],
    note: 'También aplica cuando el despegue o aterrizaje tenga su trayectoria de despegue o aproximación situada por encima del agua.' },
  { id: 'p4', unit: 'proc', type: 'list', ref: 24,
    q: 'Al iluminarse la señal del cinturón para el descenso, ¿qué se revisa en la cabina de pasajeros?',
    items: ['Cinturones abrochados', 'Mesa de servicio vertical y asegurada', 'Equipaje de mano asegurado en los lugares establecidos',
            'Bines cerrados', 'Equipos electrónicos portátiles apagados', 'Persianas de las ventanas totalmente abiertas'],
    lures: ['Cortinas de clase ejecutiva cerradas', 'Luces de cabina encendidas al máximo', 'Hornos precalentados', 'Chalecos salvavidas repartidos'] },
  { id: 'p5', unit: 'proc', type: 'order', ref: 25,
    q: 'Jerarquía dentro de una aeronave',
    steps: ['Capitán de nave o comandante', 'Primer oficial o copiloto', 'Ingeniero de vuelo (cuando exista a bordo) o jefe de vuelo',
            'Tripulante de cabina 2 (por orden de antigüedad)', 'Tripulante de cabina 3', 'Tripulante de cabina 4 y así sucesivamente'] },
  { id: 'p6', unit: 'proc', type: 'list', ref: 26,
    q: 'Las 2 funciones del compartimiento para equipaje de mano',
    items: ['Almacenaje de equipaje de mano y efectos personales de los pasajeros', 'Almacenaje de equipo de emergencia'],
    lures: ['Almacenaje de comida caliente', 'Ubicación del oxígeno suplementario', 'Almacenaje de la balsa del capitán'] },
  { id: 'p7', unit: 'proc', type: 'def', ref: 27, term: 'Reabastecimiento de combustible',
    q: '¿Qué exige el procedimiento de reabastecimiento de combustible con pasajeros a bordo?',
    a: 'El número mínimo requerido de tripulantes de cabina debe estar a bordo y preparado para una evacuación inmediata de emergencia, según lo especificado en el manual de operaciones.' },
  { id: 'p8', unit: 'proc', type: 'def', ref: 28, term: 'Briefing',
    q: '¿Qué es el briefing?',
    a: 'Reunión efectuada previa al vuelo donde la tripulación coordina su trabajo. Además se realiza un repaso sobre procedimientos de seguridad.' },
  { id: 'p9', unit: 'proc', type: 'def', ref: 29, term: 'Puerta tipo 3',
    q: '¿Qué son las puertas tipo 3?',
    a: 'Son las salidas de la aeronave que no llegan hasta el piso, como las ventanillas de emergencia, que sólo son abiertas en caso de emergencia.' },
  { id: 'p10', unit: 'proc', type: 'def', ref: 30, term: 'Escotilla',
    q: '¿Qué es la escotilla?',
    a: 'Es una salida de emergencia ubicada en el techo de la cabina de mando.' },
  { id: 'p11', unit: 'proc', type: 'def', ref: 31, term: 'Extensión del cinturón',
    q: '¿Para qué sirve la extensión del cinturón de seguridad?',
    a: 'El cinturón del asiento puede ser prolongado mediante una extensión para los pasajeros que lo requieran (por ejemplo, pasajeros con sobrepeso).' },
  { id: 'p12', unit: 'proc', type: 'order', ref: 50,
    q: 'T.E.S.T. — información que da el capitán en una emergencia',
    steps: ['T — Tipo de emergencia', 'E — Evacuación (si se evacuará y por dónde)', 'S — Señal (qué señal dará para posiciones de impacto)', 'T — Tiempo con el que se cuenta para preparar la cabina'] },

  /* ───────────── Equipos de la aeronave ───────────── */
  { id: 'e1', unit: 'equipo', type: 'def', ref: 32, term: 'ACSD',
    q: '¿Qué es el ACSD (Aviation Child Safety Device)?',
    a: 'Dispositivo proporcionado por el pasajero, aprobado para uso de niños con peso entre 10 y 20 kilos.' },
  { id: 'e2', unit: 'equipo', type: 'num', ref: 32,
    q: '¿Para qué peso está aprobado el ACSD?',
    a: 'Niños entre 10 y 20 kilos',
    options: ['Niños entre 10 y 20 kilos', 'Niños entre 5 y 15 kilos', 'Niños entre 15 y 25 kilos', 'Niños entre 20 y 30 kilos'] },
  { id: 'e3', unit: 'equipo', type: 'def', ref: 33, term: 'PSU',
    q: '¿Qué es el PSU (Passenger Service Unit) y dónde se ubica?',
    a: 'Unidades localizadas en la parte inferior de los compartimientos de equipaje (bines), o sea, arriba de los asientos de pasajeros.' },
  { id: 'e4', unit: 'equipo', type: 'def', ref: 34, term: 'Circuit breakers',
    q: '¿Qué ocurre con un circuit breaker en un cortocircuito?',
    a: 'Salta quedando fuera de su posición normal. No está permitido volverlo a su posición normal.' },
  { id: 'e5', unit: 'equipo', type: 'def', ref: 35, term: 'APU',
    q: '¿Qué es el APU (Auxiliary Power Unit)?',
    a: 'Es un generador de electricidad y presión neumática (aire) que se usa básicamente cuando los motores están apagados y la aeronave no está conectada a una fuente eléctrica exterior de tierra.' },
  { id: 'e6', unit: 'equipo', type: 'def', ref: 36, term: 'FAP',
    q: '¿Qué es el FAP (Flight Attendant Panel)?',
    a: 'Es un tablero digital táctil en el cual el tripulante de cabina puede visualizar y controlar el status de la cabina y las diferentes áreas de ésta.' },
  { id: 'e7', unit: 'equipo', type: 'match', ref: 37,
    q: 'Colores del sistema de luces de llamado',
    pairs: [['Azul fijo', 'Llamada de pasajero desde el asiento'],
            ['Ámbar intermitente', 'Se ha detectado llamada en el lavabo'],
            ['Ámbar', 'Llamada de pasajero desde el lavabo'],
            ['Rojo fijo', 'Llamada desde la cabina de mando'],
            ['Rojo intermitente', 'Llamada de emergencia de la cabina de mando']] },
  { id: 'e8', unit: 'equipo', type: 'num', ref: 41,
    q: '¿Cuál es la duración de la lámpara de mano?',
    a: '6 horas aproximadamente',
    options: ['6 horas aproximadamente', '4 horas aproximadamente', '15 minutos aproximadamente', '12 horas aproximadamente'] },

  /* ───────────── Emergencias y fuego ───────────── */
  { id: 'f1', unit: 'emer', type: 'list', ref: 38,
    q: 'Tipos de extinguidores',
    items: ['Agua', 'Polvo', 'Espuma', 'Dióxido de carbono (CO₂)'],
    lures: ['Arena', 'Nitrógeno líquido', 'Vapor de agua', 'Gas freón'] },
  { id: 'f2', unit: 'emer', type: 'def', ref: 39, term: 'Gas freón',
    q: '¿Dónde está el gas freón y cómo se activa?',
    a: 'Está debajo del lavamanos y se enciende automáticamente cuando se alcanza una temperatura mayor (se activa a los 78 °C) o se activa con un botón en el monitor (fijo).' },
  { id: 'f3', unit: 'emer', type: 'num', ref: 39,
    q: '¿A qué temperatura se activa el gas freón?',
    a: 'A los 78 °C',
    options: ['A los 78 °C', 'A los 68 °C', 'A los 88 °C', 'A los 100 °C'] },
  { id: 'f4', unit: 'emer', type: 'def', ref: 40, term: 'Máscara Puritan-Bennett',
    q: '¿Cuál es el componente principal de la máscara protectora contra humo Puritan-Bennett?',
    a: 'Generador químico de clorato de sodio + hierro + purificador o filtro compuesto de superóxido de potasio.' },
  { id: 'f5', unit: 'emer', type: 'num', ref: 40,
    q: '¿Cuál es la duración de la máscara protectora contra humo Puritan-Bennett?',
    a: '15 minutos aproximadamente',
    options: ['15 minutos aproximadamente', '30 minutos aproximadamente', '6 horas aproximadamente', '10 minutos aproximadamente'] },
  { id: 'f6', unit: 'emer', type: 'num', ref: 56,
    q: '¿Cuál es el tiempo de descarga del extintor de halón?',
    a: 'De 7 a 10 segundos',
    options: ['De 7 a 10 segundos', 'De 15 a 20 segundos', 'De 3 a 5 segundos', 'De 30 a 40 segundos'] },
  { id: 'f7', unit: 'emer', type: 'def', ref: 45, term: 'Descompresión rápida o explosiva',
    q: '¿Qué tipo de descompresión produce un cambio brusco de presión en la cabina por daño severo en la estructura?',
    a: 'La descompresión rápida o explosiva.' },
  { id: 'f8', unit: 'emer', type: 'match', ref: 46,
    q: 'Formas de accionar el sistema de oxígeno suplementario',
    pairs: [['Automáticamente', 'Al detectar los aneroides una altitud de 14.000 pies'],
            ['Eléctricamente', 'Desde la cabina de mando'],
            ['Manualmente', 'Por la ranura del compartimiento, para hacerla caer desde el PSU']] },
  { id: 'f9', unit: 'emer', type: 'num', ref: 46,
    q: '¿A qué altitud detectan los aneroides para que caigan automáticamente las máscaras?',
    a: '14.000 pies',
    options: ['14.000 pies', '10.000 pies', '18.000 pies', '25.000 pies'] },
  { id: 'f10', unit: 'emer', type: 'def', ref: 47, term: 'Hipoxia',
    q: '¿Qué es la hipoxia?',
    a: 'Es la disminución del oxígeno en la sangre y, por consiguiente, en las células del cerebro y del organismo.' },
  { id: 'f11', unit: 'emer', type: 'order', ref: 48,
    q: 'Clasificación de las turbulencias (de menor a mayor)',
    steps: ['Leve', 'Moderada', 'Severa', 'Extrema'] },
  { id: 'f12', unit: 'emer', type: 'def', ref: 49, term: 'Emergencia súbita',
    q: '¿Qué es una emergencia súbita?',
    a: 'Se entiende aquella que se da de forma sorpresiva y que no permite la preparación de la cabina para una evacuación.' },
  { id: 'f13', unit: 'emer', type: 'order', ref: 0, tag: 'Procedimiento',
    q: 'Procedimiento de extinción de fuego',
    steps: ['Tomo el extintor de la manija.',
            'Quito el pin, rompo el sello y lo coloco en la palma de mi mano.',
            'Me dirijo al fuego a una distancia prudencial, en dirección del viento.',
            'Descargo a la base del fuego en forma de barrido.',
            'Cuento del 1 al 7.',
            'Me alejo del fuego o humo sin darle la espalda.',
            'Verifico que no haya presencia de humo o fuego.',
            'Anuncio: "fuego extinguido".',
            'Informo al capitán: "fuego extinguido", causas, equipo utilizado y acciones de la tripulación.',
            'Me dirijo a la base de TCP más cercana y coloco el extintor de forma horizontal.'] },

  /* ───────────── Supervivencia ───────────── */
  { id: 's1', unit: 'surv', type: 'list', ref: 42,
    q: 'Componentes del chaleco salvavidas',
    items: ['Dos cámaras de hule natural', 'Dos cápsulas de CO₂ para su inflado', 'Dos tubos de goma para inflarlo con la boca',
            'Una luz con su respectiva batería', 'Cinturón de seguridad', 'Dos disparadores'],
    lures: ['Un silbato de rescate', 'Una radiobaliza ELT', 'Un espejo de señales', 'Un paquete de tinte marcador'] },
  { id: 's2', unit: 'surv', type: 'list', ref: 43,
    q: 'Kit de equipo de mantenimiento de la balsa',
    items: ['Bomba de mano con adaptador', 'Navajas y grapas', 'Balde plástico', 'Esponja deshidratada', 'Postes de aluminio con un mástil', 'Toldo'],
    lures: ['Botiquín de primeros auxilios', 'Tabletas purificadoras de agua', 'Heliógrafo', 'Flares o luces de bengala'] },
  { id: 's3', unit: 'surv', type: 'list', ref: 0, tag: 'Balsa',
    q: 'Equipo de supervivencia de la balsa',
    items: ['Botiquín', 'Libro de supervivencia / Biblia', 'Botellas con agua o sobres con aguas especiales', 'Tabletas purificadoras de agua'],
    lures: ['Bomba de mano con adaptador', 'Silbato', 'Paquetes de tintes', 'Balde plástico'] },
  { id: 's4', unit: 'surv', type: 'list', ref: 0, tag: 'Balsa',
    q: 'Equipos de señales de la balsa',
    items: ['Silbato', 'Heliógrafo', 'Lámpara de mano', 'Paquetes de tintes', 'Flares o luces de bengala (mitad humo y mitad luces)'],
    lures: ['Esponja deshidratada', 'Toldo', 'Botiquín', 'Navajas y grapas'] },
  { id: 's5', unit: 'surv', type: 'num', ref: 44,
    q: '¿En qué frecuencias transmite la señal de emergencia el ELT satelital?',
    a: '121.5 y 406.0 MHz',
    options: ['121.5 y 406.0 MHz', '118.0 y 243.0 MHz', '121.5 y 243.0 MHz', '406.0 y 500.0 MHz'] },
  { id: 's6', unit: 'surv', type: 'order', ref: 51,
    q: 'Los 5 principios de sobrevivencia en el mar',
    steps: ['Flotación', 'Protección', 'Sustentación', 'Primeros auxilios', 'Rescate'] },

  /* ───────────── Seguridad (AVSEC) ───────────── */
  { id: 'a1', unit: 'avsec', type: 'list', ref: 52,
    q: 'Formas en que puede recibirse un mensaje de amenaza de bomba',
    items: ['Vía telefónica', 'En persona', 'Por escrito'],
    lures: ['Por señal de radar', 'A través del FAP', 'Por el sistema de luces de llamado'] },
  { id: 'a2', unit: 'avsec', type: 'def', ref: 53, term: 'DEPU',
    q: '¿Qué es un DEPU?',
    a: 'Pasajero deportado sin acompañante.' },
  { id: 'a3', unit: 'avsec', type: 'def', ref: 54, term: 'DEPA',
    q: '¿Qué es un DEPA?',
    a: 'Persona que ha sido expulsada de un país por infringir la ley, únicamente que lo ha hecho a menor escala. Viaja acompañada.' },
  { id: 'a4', unit: 'avsec', type: 'def', ref: 55, term: 'Terrorismo',
    q: '¿Qué es el terrorismo?',
    a: 'Se entiende por terrorismo el uso de la violencia para conseguir objetivos, generalmente de naturaleza política o ideológica.' },
  { id: 'a5', unit: 'avsec', type: 'order', ref: 57,
    q: 'Primeras clases de mercancías peligrosas (en orden)',
    steps: ['Clase 1: Explosivos', 'Clase 2: Gases', 'Clase 3: Líquidos inflamables', 'Clase 4: Líquidos sólidos'] },
  { id: 'a6', unit: 'avsec', type: 'list', ref: 58,
    q: 'Tipos de etiquetas de mercancías peligrosas',
    items: ['Etiqueta de peligro', 'Etiqueta de manipulación'],
    lures: ['Etiqueta de embarque', 'Etiqueta de aduana', 'Etiqueta de equipaje facturado'] },

  /* ───────────── Primeros auxilios ───────────── */
  { id: 'x1', unit: 'pa', type: 'def', ref: 60, term: 'Primeros auxilios',
    q: '¿Qué son los primeros auxilios?',
    a: 'Son las primeras atenciones que se le proporcionan a una persona en un accidente o incidente hasta que llega la ayuda especializada.' },
  { id: 'x2', unit: 'pa', type: 'list', ref: 61,
    q: '5 ejemplos de signos vitales',
    items: ['Respiración', 'Pulso', 'Coloración de la piel', 'Dilatación de las pupilas', 'Temperatura'],
    lures: ['Peso corporal', 'Estatura', 'Nivel de azúcar', 'Fuerza muscular'] },
  { id: 'x3', unit: 'pa', type: 'def', ref: 62, term: 'Hemorragia capilar',
    q: '¿Qué es una hemorragia capilar?',
    a: 'Es la salida de sangre en poca cantidad.' },
  { id: 'x4', unit: 'pa', type: 'def', ref: 63, term: 'Quemadura de 3er grado',
    q: '¿Qué tipo de quemadura afecta todas las capas de la piel llegando incluso a la carbonización de los tejidos?',
    a: 'La quemadura de 3er grado (severa).' },
  { id: 'x5', unit: 'pa', type: 'num', ref: 64,
    q: '¿Cuántas compresiones e insuflaciones se realizan en RCP para adultos?',
    a: '30 compresiones / 2 insuflaciones',
    options: ['30 compresiones / 2 insuflaciones', '15 compresiones / 2 insuflaciones', '30 compresiones / 5 insuflaciones', '20 compresiones / 2 insuflaciones'] },
  { id: 'x6', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Medidas preventivas de shock',
    steps: ['Autoprotegerse.',
            'Recostar a la persona; si es en el suelo, colocar una frazada o aislante entre el piso y ésta.',
            'Levantar ligeramente las piernas, apoyándolas en el fuselaje.',
            'Voltear la cabeza a un lado si no hay sospecha de daño en vértebras.',
            'Cubrir con frazadas para impedir la pérdida de calor corporal.',
            'Administrar oxígeno a 4 litros por minuto según el procedimiento de aplicación.',
            'Verificar constantemente los signos vitales.',
            'No proporcionar comidas ni bebidas.',
            'Si fuera necesario, impartir otra clase de primeros auxilios según lo que presente la persona.',
            'Si pierde la conciencia, verificar PRCAB y, con signos vitales, colocarla en postura de seguridad si no se sospechan lesiones en la espina dorsal.'] },
  { id: 'x7', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Hemorragia nasal',
    steps: ['Autoprotegerse.',
            'Mantener a la persona tranquila y sentada, con la cabeza ligeramente inclinada hacia el frente.',
            'Presionar las fosas nasales con los dedos pulgar e índice.',
            'Aplicar compresas de agua fría en el puente de la nariz.',
            'Si el sangrado persiste, colocar tapones de gasa estéril en las fosas (no utilizar algodón).',
            'Si no se detiene en un tiempo prudencial, pedir ayuda médica.'] },
  { id: 'x8', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Hiperventilación',
    steps: ['Dirigir la atención de la persona a otra cosa que no sea el vuelo.',
            'Dar soporte emocional.',
            'Hacerla respirar en una bolsa de papel si la situación es severa.',
            'Hacer que la persona hable: entre más hable, menos oxígeno consume.',
            'Monitorear su estado constantemente.'] },
  { id: 'x9', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Sensación de desmayo',
    steps: ['Autoprotegerse.',
            'Revisar signos vitales, sobre todo pulso y respiración.',
            'Si existen signos, aplicar medidas preventivas de shock.',
            'Si no hay lugar para colocarla con las piernas hacia arriba, poner su cabeza entre las rodillas para aumentar el flujo de sangre al cerebro.',
            'Administrar oxígeno a 4 litros por minuto según procedimiento de aplicación.',
            'Si no se detectan signos vitales, efectuar reanimación cardiopulmonar.',
            'Solicitar ayuda médica.'] },
  { id: 'x10', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Dolor de oído',
    steps: ['Sugerirle a la persona que bostece.',
            'Proporcionarle un vaso con agua para que lo tome en pequeños sorbos, o que mastique chicle.',
            'En descensos, indicarle que cierre la boca, se tape la nariz y sople (maniobra de Valsalva).',
            'Si es un niño pequeño, tratar de que tome su biberón y dejarlo llorar.',
            'No aplicar gotas ni tapones.'] },
  { id: 'x11', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Mareo por movimiento',
    steps: ['Poner a la persona en posición semirecostada.',
            'Evitar líquidos y bebidas, sobre todo alcohólicas.',
            'Abrir la salida de aire fresco.',
            'Que cierre los ojos y trate de dormir.'] },
  { id: 'x12', unit: 'pa', type: 'list', ref: 0, tag: 'Protocolo',
    q: 'Tratamiento de la hipoxia',
    items: ['Uso de oxígeno suplementario de inmediato',
            'Mantener peso acorde a la estatura, no fumar ni tomar alcohol y ejercitarse para resistir mejor sus efectos'],
    lures: ['Respirar en una bolsa de papel', 'Administrar líquidos azucarados', 'Colocar compresas frías en la nuca'] },
  { id: 'x13', unit: 'pa', type: 'order', ref: 0, tag: 'Protocolo',
    q: 'Obstrucción de vías aéreas (adulto)',
    steps: ['Me presento: "soy tripulante de cabina y estoy acá para ayudarlo".',
            'Le doy 5 palmadas en la espalda y le insisto en toser.',
            'Si el objeto no sale, hago la maniobra de Heimlich hasta que el objeto salga.'] }
];

CC.CARD_BY_ID = Object.fromEntries(CC.CARDS.map(c => [c.id, c]));
