/* Banco de preguntas del Examen de Auxiliar de Cabina de la Autoridad de
   Aviación Civil de El Salvador (AAC, 30-nov-2022). Son 149 preguntas de opción
   múltiple (tipo `mc`); `ref` es su número en el orden del PDF y `a`, la
   respuesta que marca la clave oficial. Las opciones van en el orden del
   examen. Pertenecen al curso TCP con el origen `aac`, así que se pueden
   estudiar junto al examen final o por separado. */
window.CC = window.CC || {};

CC.AAC = {
  UNITS: [
    { id: 'aac-vuelo', course: 'tcp', src: 'aac', name: 'Aeronave y vuelo', icon: '🛩️', hue: 210, blurb: 'Empenaje, sustentación, flaps y alabeo' },
    { id: 'aac-meteo', course: 'tcp', src: 'aac', name: 'Meteo, METAR y hora Z', icon: '⛅', hue: 195, blurb: 'Nubes, presión, TAF, METAR y hora local' },
    { id: 'aac-norma', course: 'tcp', src: 'aac', name: 'RAC: tripulación y licencias', icon: '⚖️', hue: 40, blurb: 'Tiempos de servicio, entrenamiento y aptitud' },
    { id: 'aac-ops', course: 'tcp', src: 'aac', name: 'Operación y cabina de mando', icon: '🧑‍✈️', hue: 330, blurb: 'Cabina estéril, manuales, puertas y autoridad' },
    { id: 'aac-equipo', course: 'tcp', src: 'aac', name: 'Equipo de emergencia', icon: '🔦', hue: 225, blurb: 'Luces, lámparas, megáfonos, halón y botiquines' },
    { id: 'aac-a320', course: 'tcp', src: 'aac', name: 'Sistemas del A320', icon: '🖥️', hue: 250, blurb: 'CIDS, FAP, AAP, PTP, agua y luces' },
    { id: 'aac-slide', course: 'tcp', src: 'aac', name: 'Puertas y toboganes', icon: '🚪', hue: 300, blurb: 'Salidas del A320, toboganes y balsas' },
    { id: 'aac-emer', course: 'tcp', src: 'aac', name: 'Evacuación e impacto', icon: '🚨', hue: 355, blurb: 'TEST, posición de impacto, ABP y amarizaje' },
    { id: 'aac-fuego', course: 'tcp', src: 'aac', name: 'Fuego y humo', icon: '🔥', hue: 18, blurb: 'Clases de fuego, extintores y PBE' },
    { id: 'aac-fisio', course: 'tcp', src: 'aac', name: 'Descompresión e hipoxia', icon: '🫁', hue: 175, blurb: 'Tiempo útil de conciencia, máscaras y oxígeno' },
    { id: 'aac-surv', course: 'tcp', src: 'aac', name: 'ELT y supervivencia', icon: '📡', hue: 165, blurb: 'ELT, bote salvavidas y sobrevivencia en el mar' },
    { id: 'aac-mp', course: 'tcp', src: 'aac', name: 'Mercancías peligrosas', icon: '⚠️', hue: 50, blurb: 'Definición, accidentes, NOTOC y amenaza de bomba' },
    { id: 'aac-pa', course: 'tcp', src: 'aac', name: 'Auxilios a bordo', icon: '🚑', hue: 135, blurb: 'Shock, Heimlich, desmayo y prioridades' }
  ],

  CARDS: [
    /* ───────────── Aeronave y vuelo ───────────── */
    { id: 'aac113', unit: 'aac-vuelo', type: 'mc', ref: 113,
      q: 'Los componentes de la cola o empenaje del A319/320 son:',
      options: ['Flaps, slats, elevadores y timón direccional', 'Estabilizador vertical, estabilizador horizontal, elevadores y timón direccional', 'Borde de ataque y borde de fuga'],
      a: 'Estabilizador vertical, estabilizador horizontal, elevadores y timón direccional' },
    { id: 'aac114', unit: 'aac-vuelo', type: 'mc', ref: 114,
      q: 'Parte capaz de producir sustentación en un avión:',
      options: ['Las alas', 'El fuselaje', 'El empenaje'],
      a: 'Las alas' },
    { id: 'aac115', unit: 'aac-vuelo', type: 'mc', ref: 115,
      q: 'El movimiento llamado lateral o alabeo es producido por:',
      options: ['Los elevadores', 'Los flaps', 'Ninguno de los anteriores'],
      a: 'Ninguno de los anteriores',
      note: 'El alabeo lo producen los alerones.' },
    { id: 'aac116', unit: 'aac-vuelo', type: 'mc', ref: 116,
      q: 'Dispositivos que incrementan la sustentación a bajas velocidades:',
      options: ['Flaps', 'Slats', '1 y 2 son correctas'],
      a: '1 y 2 son correctas' },
    { id: 'aac117', unit: 'aac-vuelo', type: 'mc', ref: 117,
      q: 'El tren de aterrizaje del A319/320 en posición extendida produce:',
      options: ['Sustentación', 'Tracción', 'Resistencia'],
      a: 'Resistencia' },
    { id: 'aac128', unit: 'aac-vuelo', type: 'mc', ref: 128,
      q: 'Las partes del fuselaje del A319/320 que no son presurizadas son:',
      options: ['Los compartimientos del tren de nariz y del tren principal', 'Los compartimientos de carga y el bulk cargo', '1 y 2 son correctas'],
      a: 'Los compartimientos del tren de nariz y del tren principal' },
    { id: 'aac133', unit: 'aac-vuelo', type: 'mc', ref: 133,
      q: 'Las luces de navegación de las puntas de las alas, roja a la izquierda y verde a la derecha, sirven para identificar de noche la posición del avión.',
      options: ['Verdadero', 'Falso'],
      a: 'Verdadero' },

    /* ───────────── Meteo, METAR y hora Z ───────────── */
    { id: 'aac38', unit: 'aac-meteo', type: 'mc', ref: 38,
      q: 'Las nubes más peligrosas para el vuelo de las aeronaves son:',
      options: ['Cumulonimbus', 'Altoestratos', 'Cirrus'],
      a: 'Cumulonimbus' },
    { id: 'aac39', unit: 'aac-meteo', type: 'mc', ref: 39,
      q: 'El principal problema de la formación de hielo sobre las alas de una aeronave se debe a que ___, por lo que se debe informar de inmediato a la cabina de mando.',
      options: ['Se produce un excesivo peso sobre la estructura', 'Se deforma el perfil aerodinámico, lo que reduce la sustentación de vuelo', 'Se produce un gran desbalance a lo largo del eje longitudinal del avión'],
      a: 'Se deforma el perfil aerodinámico, lo que reduce la sustentación de vuelo' },
    { id: 'aac118', unit: 'aac-meteo', type: 'mc', ref: 118,
      q: 'Definición de altura:',
      options: ['Distancia vertical entre un punto móvil y un punto de referencia sobre la tierra', 'Distancia vertical que resulta de triangular un punto en el espacio y dos sobre la tierra', 'Distancia vertical entre un punto móvil o fijo y un punto de referencia sobre la tierra'],
      a: 'Distancia vertical entre un punto móvil o fijo y un punto de referencia sobre la tierra' },
    { id: 'aac119', unit: 'aac-meteo', type: 'mc', ref: 119,
      q: 'Es una zona o área donde las presiones son más bajas que las de los alrededores:',
      options: ['Baja presión', 'Alta presión', 'Baja presión relacionada con temperatura'],
      a: 'Baja presión' },
    { id: 'aac120', unit: 'aac-meteo', type: 'mc', ref: 120,
      q: 'No se deben considerar ajustes altimétricos cuando se vuela en los contornos de las zonas de baja presión.',
      options: ['Verdadero', 'Falso'],
      a: 'Verdadero' },
    { id: 'aac121', unit: 'aac-meteo', type: 'mc', ref: 121,
      q: 'La turbulencia orográfica es:',
      options: ['Causada por el calentamiento de la superficie terrestre', 'Causada por la rugosidad del terreno, edificios, cerros o colonias pequeñas', 'Causada por la diferencia de temperatura que existe en distintos niveles'],
      a: 'Causada por la rugosidad del terreno, edificios, cerros o colonias pequeñas' },
    { id: 'aac122', unit: 'aac-meteo', type: 'mc', ref: 122,
      q: 'TAF significa:',
      options: ['Terminal Aerodrome Forecast', 'Terminal Advisory Forecast', 'Team Aerodrome Forecast'],
      a: 'Terminal Aerodrome Forecast' },
    { id: 'aac123', unit: 'aac-meteo', type: 'mc', ref: 123,
      q: 'El pronóstico METAR es emitido cada hora.',
      options: ['Verdadero', 'Falso'],
      a: 'Verdadero' },
    { id: 'aac124', unit: 'aac-meteo', type: 'mc', ref: 124,
      q: 'El código 9999 en un METAR se descodifica como:',
      options: ['Visibilidad expresada en millas náuticas', 'Visibilidad expresada en millas terrestres', 'Visibilidad expresada en kilómetros'],
      a: 'Visibilidad expresada en kilómetros' },
    { id: 'aac125', unit: 'aac-meteo', type: 'mc', ref: 125,
      q: 'En el MSLP METAR 291400Z 08006KT 9999 28/22 1010.0 29.84, la presión de la estación es de:',
      options: ['1010.0 milibares', '29.84 pulgadas de mercurio', '1 y 2 son correctas'],
      a: '1 y 2 son correctas' },
    { id: 'aac126', unit: 'aac-meteo', type: 'mc', ref: 126,
      q: 'Si el vuelo TA310 con destino a Miami reporta su estimado de llegada a las 17:15 Z, la hora local estimada de llegada es:',
      options: ['11:15 horas', '13:15 horas', '12:15 horas'],
      a: '12:15 horas',
      note: 'La clave toma Miami a UTC−5 (hora estándar del Este).' },
    { id: 'aac127', unit: 'aac-meteo', type: 'mc', ref: 127,
      q: 'Si el vuelo TA520 con destino a Los Ángeles reporta su estimado de llegada a las 05:20 Z, la hora local estimada de llegada es:',
      options: ['23:20 horas', '21:20 horas', '22:20 horas'],
      a: '22:20 horas',
      note: 'La clave toma Los Ángeles a UTC−7 (horario de verano del Pacífico).' },

    /* ───────────── RAC: tripulación y licencias ───────────── */
    { id: 'aac7', unit: 'aac-norma', type: 'mc', ref: 7,
      q: '¿Cuál es la razón primordial por la que se requiere la presencia de los tripulantes de cabina en los vuelos de transporte comercial de pasajeros?',
      options: ['Para ofrecer comodidad, alimentos, bebidas y licores a los pasajeros', 'Para atender a los pilotos y a los pasajeros en sus necesidades básicas', 'Para garantizar la mayor seguridad a los pasajeros y tripulantes durante todo el vuelo'],
      a: 'Para garantizar la mayor seguridad a los pasajeros y tripulantes durante todo el vuelo' },
    { id: 'aac8', unit: 'aac-norma', type: 'mc', ref: 8,
      q: '«Miembro de la tripulación» significa:',
      options: ['Cada miembro de la tripulación de vuelo o de la tripulación de cabina', 'Persona titular de una licencia emitida por la AAC', 'Persona a quien el explotador asigna obligaciones que ha de cumplir a bordo de una aeronave durante el tiempo de vuelo'],
      a: 'Persona a quien el explotador asigna obligaciones que ha de cumplir a bordo de una aeronave durante el tiempo de vuelo' },
    { id: 'aac12', unit: 'aac-norma', type: 'mc', ref: 12,
      q: 'Según las limitaciones de tiempo de servicio para tripulantes de cabina, el tiempo máximo para una tripulación de más de tres tripulantes en 24 horas es de:',
      options: ['10 horas', '14 horas', '16 horas'],
      a: '14 horas' },
    { id: 'aac21', unit: 'aac-norma', type: 'mc', ref: 21,
      q: 'De acuerdo con las regulaciones de la AAC, los miembros de la tripulación no podrán ejercer funciones si han ingerido cualquier tipo de bebida alcohólica o están bajo los efectos de cualquier otra droga en un lapso de ___ horas previo al vuelo:',
      options: ['12 horas', '8 horas', '15 horas'],
      a: '8 horas' },
    { id: 'aac83', unit: 'aac-norma', type: 'mc', ref: 83,
      q: 'Se deberá incluir al menos un tripulante de cabina cuando:',
      options: ['La configuración sea de 19 asientos o menos', 'La configuración sea de 19 asientos o más', 'La configuración sea de 50 asientos'],
      a: 'La configuración sea de 19 asientos o más' },
    { id: 'aac84', unit: 'aac-norma', type: 'mc', ref: 84,
      q: 'En casos imprevistos, se puede reducir el número mínimo requerido de miembros de la tripulación de cabina a condición de que:',
      options: ['Se haya reducido el número de pasajeros de acuerdo con los procedimientos especificados en el manual de operaciones', 'Se entregue un informe a la AAC después de finalizado el vuelo', '1 y 2 son correctas'],
      a: '1 y 2 son correctas' },
    { id: 'aac86', unit: 'aac-norma', type: 'mc', ref: 86,
      q: 'Un tripulante de cabina podrá operar en cuatro tipos de avión, siempre que los equipos de seguridad y los procedimientos de emergencia sean similares para:',
      options: ['Tres de los tipos como mínimo', 'Dos de los tipos como mínimo', 'Ninguno de los anteriores'],
      a: 'Dos de los tipos como mínimo' },
    { id: 'aac87', unit: 'aac-norma', type: 'mc', ref: 87,
      q: 'Un tripulante de cabina podrá ser programado para volar por un periodo de ocho horas o menos:',
      options: ['Durante cualquier periodo de 12 horas consecutivas, sin un periodo de descanso durante esas ocho horas', 'Durante cualquier periodo de 18 horas consecutivas, sin un periodo de descanso durante esas ocho horas', 'Durante cualquier periodo de 24 horas consecutivas, sin un periodo de descanso durante esas ocho horas'],
      a: 'Durante cualquier periodo de 24 horas consecutivas, sin un periodo de descanso durante esas ocho horas' },
    { id: 'aac91', unit: 'aac-norma', type: 'mc', ref: 91,
      q: 'El tiempo utilizado en transportación hacia o desde el aeropuerto, el hotel o un punto determinado:',
      options: ['No es considerado como tiempo de servicio', 'No es considerado parte del tiempo de descanso', 'Es considerado como tiempo de servicio'],
      a: 'No es considerado parte del tiempo de descanso' },
    { id: 'aac101', unit: 'aac-norma', type: 'mc', ref: 101,
      q: 'Un tripulante en servicio deberá someterse a una prueba que indique el porcentaje de alcohol ingerido:',
      options: ['A solicitud de un inspector de la AAC', 'A solicitud del operador', '1 y 2 son correctas'],
      a: '1 y 2 son correctas' },
    { id: 'aac104', unit: 'aac-norma', type: 'mc', ref: 104,
      q: 'Si el entrenamiento recurrente de emergencias y primeros auxilios se imparte en los últimos tres meses del periodo de validez de la comprobación anterior, el periodo se puede extender:',
      options: ['A partir de la fecha en que se impartió hasta 6 meses contados desde la fecha de vencimiento de la comprobación anterior', 'A partir de la fecha en que se impartió hasta 12 meses contados desde la fecha de vencimiento de la comprobación anterior', '1 y 2 son correctas'],
      a: 'A partir de la fecha en que se impartió hasta 12 meses contados desde la fecha de vencimiento de la comprobación anterior' },
    { id: 'aac105', unit: 'aac-norma', type: 'mc', ref: 105,
      q: 'Se deberá realizar entrenamiento de diferencias para tripulantes de cabina antes de actuar:',
      options: ['En una versión de avión con cabina de mando diferente', 'En una versión del tipo actual del avión', 'En un avión con los mismos procedimientos con respecto a los tipos o versiones operados'],
      a: 'En una versión del tipo actual del avión' },
    { id: 'aac107', unit: 'aac-norma', type: 'mc', ref: 107,
      q: 'El solicitante de una licencia de tripulante de cabina deberá poseer una evaluación médica:',
      options: ['Clase I', 'Clase II', 'Clase II vigente'],
      a: 'Clase II vigente' },
    { id: 'aac139', unit: 'aac-norma', type: 'mc', ref: 139,
      q: 'El operador no designará a un jefe de cabina a no ser que:',
      options: ['Esa persona tenga como mínimo un año de experiencia operativa o haya superado un curso adecuado', 'Esa persona tenga como mínimo un año de experiencia operativa y haya superado un curso adecuado', 'Esa persona tenga como mínimo tres años de experiencia operativa y/o haya superado un curso adecuado'],
      a: 'Esa persona tenga como mínimo un año de experiencia operativa y haya superado un curso adecuado' },
    { id: 'aac149', unit: 'aac-norma', type: 'mc', ref: 149,
      q: 'Ningún tripulante puede volar más de 32 horas durante 7 días consecutivos.',
      options: ['Verdadero', 'Falso'],
      a: 'Verdadero' },

    /* ───────────── Operación y cabina de mando ───────────── */
    { id: 'aac28', unit: 'aac-ops', type: 'mc', ref: 28,
      q: 'El concepto de cabina estéril tiene como finalidad:',
      options: ['Máxima concentración de la tripulación de vuelo', 'Máximo confort para los pasajeros', 'Mejor servicio de cabina'],
      a: 'Máxima concentración de la tripulación de vuelo' },
    { id: 'aac46', unit: 'aac-ops', type: 'mc', ref: 46,
      q: 'Se considera cabina estéril durante:',
      options: ['El taxeo', 'Las fases críticas del vuelo', 'El encendido de motores'],
      a: 'Las fases críticas del vuelo' },
    { id: 'aac65', unit: 'aac-ops', type: 'mc', ref: 65,
      q: '¿Qué edad debe tener un niño o infante para que pueda ocupar un asiento en la aeronave?',
      options: ['3 años', '2 años', '4 años'],
      a: '2 años' },
    { id: 'aac66', unit: 'aac-ops', type: 'mc', ref: 66,
      q: 'La admisión a la cabina de mando será responsabilidad y autorización de:',
      options: ['El jefe de cabina', 'El piloto al mando', 'El agente de tierra'],
      a: 'El piloto al mando' },
    { id: 'aac81', unit: 'aac-ops', type: 'mc', ref: 81,
      q: 'Se debe pedir permiso para cerrar la puerta principal cuando:',
      options: ['Todos los pasajeros estén sentados', 'Todos los pasajeros estén a bordo', 'Toda la documentación requerida esté a bordo'],
      a: 'Todos los pasajeros estén sentados' },
    { id: 'aac93', unit: 'aac-ops', type: 'mc', ref: 93,
      q: 'Dentro de la estructura del Manual de Operaciones, la parte D comprende:',
      options: ['Generalidades', 'Temas relativos a la operación', 'Entrenamientos'],
      a: 'Entrenamientos' },
    { id: 'aac94', unit: 'aac-ops', type: 'mc', ref: 94,
      q: 'El manual de tripulantes de cabina:',
      options: ['Forma parte del Manual General de Operaciones', 'No forma parte del Manual General de Operaciones', 'Ninguno de los anteriores'],
      a: 'Forma parte del Manual General de Operaciones' },
    { id: 'aac95', unit: 'aac-ops', type: 'mc', ref: 95,
      q: 'COA significa:',
      options: ['Certificado de operación de aerovías', 'Certificado de operación aeronáutico', 'Ninguno de los anteriores'],
      a: 'Ninguno de los anteriores',
      note: 'COA es el Certificado de Operador Aéreo.' },
    { id: 'aac97', unit: 'aac-ops', type: 'mc', ref: 97,
      q: 'El responsable de no permitir que ningún miembro de la tripulación lleve a cabo actividad alguna durante el despegue, el ascenso inicial, la aproximación final y el aterrizaje, excepto las funciones que se requieran para la operación segura del avión, es:',
      options: ['El piloto al mando', 'El primer oficial', 'El jefe de cabina'],
      a: 'El piloto al mando' },
    { id: 'aac99', unit: 'aac-ops', type: 'mc', ref: 99,
      q: 'Los infantes con menos de 7 días de nacidos:',
      options: ['Podrán ser transportados en avión', 'No podrán ser transportados en avión a menos que presenten una certificación médica que los autorice a viajar', 'Ninguno de los anteriores'],
      a: 'No podrán ser transportados en avión a menos que presenten una certificación médica que los autorice a viajar' },
    { id: 'aac100', unit: 'aac-ops', type: 'mc', ref: 100,
      q: 'La tripulación de la cabina de mando informará a la tripulación de cabina de pasajeros de los códigos de acceso y de emergencia para el uso de puertas fase II:',
      options: ['Durante el briefing previo al vuelo', 'Durante el vuelo, al alcanzar 10,000 pies', 'Por medio del intercomunicador'],
      a: 'Durante el briefing previo al vuelo' },
    { id: 'aac102', unit: 'aac-ops', type: 'mc', ref: 102,
      q: 'La responsabilidad de elaborar y colocar las viñetas con los códigos y colores en las bitácoras de mantenimiento para el uso de las puertas fase II es de:',
      options: ['El departamento de mantenimiento', 'Compartida entre el departamento de seguridad de vuelo, prevención de accidentes y seguridad de la aviación', 'El departamento de tripulantes de cabina'],
      a: 'El departamento de mantenimiento' },
    { id: 'aac145', unit: 'aac-ops', type: 'mc', ref: 145,
      q: 'El jefe de cabina podrá asumir la autoridad máxima de un vuelo determinado:',
      options: ['En ningún caso', 'Si el piloto al mando se encuentra incapacitado', 'Si el piloto al mando se encuentra incapacitado y de acuerdo con la cadena de mando en una situación de emergencia'],
      a: 'Si el piloto al mando se encuentra incapacitado y de acuerdo con la cadena de mando en una situación de emergencia' },
    { id: 'aac148', unit: 'aac-ops', type: 'mc', ref: 148,
      q: 'El código de acceso y de emergencia para la operación de la puerta de la cabina de mando se encuentra en:',
      options: ['El manual general de operaciones', 'La cara interior de la cubierta de la bitácora de mantenimiento de la aeronave', 'El manual de emergencia de la compañía'],
      a: 'La cara interior de la cubierta de la bitácora de mantenimiento de la aeronave' },

    /* ───────────── Equipo de emergencia ───────────── */
    { id: 'aac6', unit: 'aac-equipo', type: 'mc', ref: 6,
      q: 'El único switch en la cabina de pasajeros que tiene prioridad sobre la cabina de mando es:',
      options: ['Luces de emergencia', 'Timbre de llamada a tripulantes', 'Switch de servicio en tierra'],
      a: 'Luces de emergencia' },
    { id: 'aac19', unit: 'aac-equipo', type: 'mc', ref: 19,
      q: 'Las luces de emergencia se iluminarán automáticamente en caso de:',
      options: ['Impacto', 'Pérdida de energía', 'Activarlas desde la cabina de mando'],
      a: 'Pérdida de energía' },
    { id: 'aac24', unit: 'aac-equipo', type: 'mc', ref: 24,
      q: 'Para poder operar las luces de emergencia desde la cabina de pasajeros, el interruptor en la cabina de mando debe estar:',
      options: ['En ON', 'En standby', 'No afecta su posición'],
      a: 'No afecta su posición' },
    { id: 'aac32', unit: 'aac-equipo', type: 'mc', ref: 32,
      q: 'Los megáfonos requeridos a bordo van de acuerdo con el número de:',
      options: ['Asientos', 'Pasajeros', 'Ambos'],
      a: 'Asientos' },
    { id: 'aac33', unit: 'aac-equipo', type: 'mc', ref: 33,
      q: 'Si en el avión se requiere un solo megáfono, este será ubicado:',
      options: ['Adelante', 'Atrás', 'No es relevante su posición'],
      a: 'Atrás' },
    { id: 'aac34', unit: 'aac-equipo', type: 'mc', ref: 34,
      q: '¿Cuántos extintores de halón se requieren a bordo de un avión con capacidad de 0 a 60 asientos?',
      options: ['2', '3', '4'],
      a: '2' },
    { id: 'aac36', unit: 'aac-equipo', type: 'mc', ref: 36,
      q: '¿Cuántos botiquines se requieren a bordo de una aeronave con capacidad para 99 pasajeros?',
      options: ['1', '3', '2'],
      a: '2',
      note: 'Ojo: la clave AAC marca 2 aquí, pero en la pregunta 82 (de 0 a 99 pasajeros) marca 1.' },
    { id: 'aac42', unit: 'aac-equipo', type: 'mc', ref: 42,
      q: 'La duración de operación de las luces de emergencia una vez removidas de su compartimiento es de:',
      options: ['40 minutos', '20 minutos', '50 minutos'],
      a: '20 minutos' },
    { id: 'aac43', unit: 'aac-equipo', type: 'mc', ref: 43,
      q: 'La duración de operación de las lámparas manuales de cada estación de los tripulantes es de:',
      options: ['4 horas', '6 horas', '8 horas'],
      a: '6 horas' },
    { id: 'aac74', unit: 'aac-equipo', type: 'mc', ref: 74,
      q: 'La duración de las lámparas removibles a bordo es de:',
      options: ['4 horas', '6 horas', '8 horas'],
      a: '6 horas' },
    { id: 'aac82', unit: 'aac-equipo', type: 'mc', ref: 82,
      q: '¿Cuántos botiquines se requieren a bordo de un avión con capacidad de 0 a 99 pasajeros?',
      options: ['1', '2', '3'],
      a: '1',
      note: 'Ojo: en la pregunta 36 (99 pasajeros) la clave AAC marca 2.' },

    /* ───────────── Sistemas del A320 ───────────── */
    { id: 'aac16', unit: 'aac-a320', type: 'mc', ref: 16,
      q: 'Si durante una inspección previa al vuelo se detecta que la luz ámbar del calentador de agua de un lavatorio está apagada, estando el switch en posición ON, probablemente:',
      options: ['Se descargó el extintor', 'Es una condición normal', 'Hubo un cortocircuito'],
      a: 'Hubo un cortocircuito' },
    { id: 'aac20', unit: 'aac-a320', type: 'mc', ref: 20,
      q: 'El APU suministra al avión:',
      options: ['Electricidad', 'Aire acondicionado', 'Electricidad, aire comprimido y aire acondicionado en tierra'],
      a: 'Electricidad, aire comprimido y aire acondicionado en tierra' },
    { id: 'aac68', unit: 'aac-a320', type: 'mc', ref: 68,
      q: 'En tierra, el aire acondicionado y la electricidad son suplidos a la aeronave por:',
      options: ['Baterías', 'El motor n.º 2 o planta externa', 'Ambas respuestas son correctas'],
      a: 'El motor n.º 2 o planta externa' },
    { id: 'aac79', unit: 'aac-a320', type: 'mc', ref: 79,
      q: 'El control de las luces de la cabina de pasajeros se encuentra:',
      options: ['En el panel de control del tripulante de cabina n.º 1', 'En la cabina de mando', 'Ambos son correctos'],
      a: 'Ambos son correctos' },
    { id: 'aac92', unit: 'aac-a320', type: 'mc', ref: 92,
      q: 'El RESET PUSH BUTTON, localizado en el FAP y en el AAP, se utiliza para:',
      options: ['Reiniciar el CIDS', 'Cancelar el sistema de alerta de evacuación', 'Apagar las alarmas de evacuación y/o las alarmas de detección de humo en los baños'],
      a: 'Apagar las alarmas de evacuación y/o las alarmas de detección de humo en los baños' },
    { id: 'aac103', unit: 'aac-a320', type: 'mc', ref: 103,
      q: 'La iluminación de la cabina de pasajeros (OFF, ON, DIM 1, DIM 2) es controlada desde:',
      options: ['La cabina de mando', 'El FAP', 'El PTP'],
      a: 'El FAP' },
    { id: 'aac106', unit: 'aac-a320', type: 'mc', ref: 106,
      q: 'En el AAP se encuentra el módulo de lectura de la cantidad de agua y de residuos a bordo de la aeronave.',
      options: ['Verdadero', 'Falso'],
      a: 'Falso' },
    { id: 'aac108', unit: 'aac-a320', type: 'mc', ref: 108,
      q: 'CIDS significa:',
      options: ['Cabin Intercommunication Data System', 'Centralized Intercommunication Data System', 'Ninguna de las anteriores'],
      a: 'Cabin Intercommunication Data System' },
    { id: 'aac109', unit: 'aac-a320', type: 'mc', ref: 109,
      q: 'MCDU significa:',
      options: ['Monitoring Ceiling Display Unit', 'Multifunction Control and Display Unit', 'Minimum Ceiling Display Unit'],
      a: 'Multifunction Control and Display Unit' },
    { id: 'aac110', unit: 'aac-a320', type: 'mc', ref: 110,
      q: 'DEU significa:',
      options: ['Display Encoder Unit', 'Display Emergency Unit', 'Decoder Encoder Unit'],
      a: 'Decoder Encoder Unit' },
    { id: 'aac111', unit: 'aac-a320', type: 'mc', ref: 111,
      q: 'SDCU significa:',
      options: ['Smoke Detection Control Unit', 'Smoke Display Central Unit', 'Secondary Detection Central Unit'],
      a: 'Smoke Detection Control Unit' },
    { id: 'aac112', unit: 'aac-a320', type: 'mc', ref: 112,
      q: 'PTP significa:',
      options: ['Programming and Test Panel', 'Programming Time Panel', 'Ninguno de los anteriores'],
      a: 'Programming and Test Panel' },
    { id: 'aac131', unit: 'aac-a320', type: 'mc', ref: 131,
      q: 'Todas las cortinas de las ventanas del A319/320 se cierran de arriba hacia abajo.',
      options: ['Verdadero', 'Falso'],
      a: 'Falso' },
    { id: 'aac134', unit: 'aac-a320', type: 'mc', ref: 134,
      q: 'El compartimiento donde se encuentra el lazo o soga está localizado:',
      options: ['Arriba del asiento del capitán', 'Arriba del asiento del capitán y del copiloto', 'Arriba del asiento del capitán, del copiloto y del observador'],
      a: 'Arriba del asiento del capitán y del copiloto' },
    { id: 'aac135', unit: 'aac-a320', type: 'mc', ref: 135,
      q: 'Cuando los motores están encendidos y se abre la puerta de la cabina de mando, las luces de la entrada de la cabina de pasajeros:',
      options: ['Se apagan automáticamente', 'Disminuyen su intensidad automáticamente', 'Disminuyen su intensidad a un 25 % automáticamente'],
      a: 'Disminuyen su intensidad automáticamente' },
    { id: 'aac136', unit: 'aac-a320', type: 'mc', ref: 136,
      q: 'En caso de emergencia, la puerta de los baños puede ser abierta desde afuera:',
      options: ['Con el manual release tool', 'Sin necesidad de usar ninguna llave', 'Con el hacha que se encuentra en la cabina de mando'],
      a: 'Sin necesidad de usar ninguna llave' },
    { id: 'aac138', unit: 'aac-a320', type: 'mc', ref: 138,
      q: 'En el PTP el tripulante de cabina encuentra la siguiente información:',
      options: ['Presión de los toboganes y presión de la botella de nitrógeno', 'Cantidades de hidráulico', 'Presión de inflado de las llantas'],
      a: 'Presión de los toboganes y presión de la botella de nitrógeno' },
    { id: 'aac140', unit: 'aac-a320', type: 'mc', ref: 140,
      q: 'Para detener el paso del agua hacia el baño y hacia el galley se deberá:',
      options: ['Cerrar la válvula manual que cierra el paso del agua, correspondiente a cada galley o a cada baño', 'Cerrar la válvula que cierra el paso del agua localizada en la estación del jefe de cabina', 'Presionar el botón que cierra el paso del agua, localizado en el FAP'],
      a: 'Cerrar la válvula manual que cierra el paso del agua, correspondiente a cada galley o a cada baño' },
    { id: 'aac144', unit: 'aac-a320', type: 'mc', ref: 144,
      q: 'La alarma aural que se apaga presionando el botón de RESET es parte de:',
      options: ['El AIP', 'Los detectores de humo en los equipos A319/320', 'El FAP'],
      a: 'Los detectores de humo en los equipos A319/320' },

    /* ───────────── Puertas y toboganes ───────────── */
    { id: 'aac23', unit: 'aac-slide', type: 'mc', ref: 23,
      q: 'Durante el retroempuje, los toboganes deben estar:',
      options: ['Desarmados', 'Armados', 'En standby'],
      a: 'Armados' },
    { id: 'aac41', unit: 'aac-slide', type: 'mc', ref: 41,
      q: 'Durante la preparación de un amarizaje en un avión equipado con toboganes/balsa, estos deberán estar ___ antes del impacto:',
      options: ['Desarmados', 'Armados', 'Inflados'],
      a: 'Armados' },
    { id: 'aac52', unit: 'aac-slide', type: 'mc', ref: 52,
      q: 'En la preparación para el amarizaje, los toboganes del A320 deben estar:',
      options: ['Armados', 'Desarmados', 'En posición de ditching'],
      a: 'Armados' },
    { id: 'aac53', unit: 'aac-slide', type: 'mc', ref: 53,
      q: 'Los toboganes tardan en inflarse:',
      options: ['5 segundos en operación automática y 36 segundos en operación manual', '5 segundos en operación manual y aproximadamente 4 segundos en operación automática', 'Ninguna de las anteriores'],
      a: '5 segundos en operación manual y aproximadamente 4 segundos en operación automática' },
    { id: 'aac54', unit: 'aac-slide', type: 'mc', ref: 54,
      q: 'Para abrir la puerta de un A320 en operación de emergencia se utiliza el sistema:',
      options: ['Neumático', 'Eléctrico', 'Ninguno de los anteriores'],
      a: 'Neumático' },
    { id: 'aac55', unit: 'aac-slide', type: 'mc', ref: 55,
      q: 'La luz blanca en la puerta del A320 permanece encendida:',
      options: ['Cuando el tobogán está armado', 'Cuando el tobogán está armado y alguien trata de abrir la puerta', 'Al inflarse el tobogán'],
      a: 'Cuando el tobogán está armado y alguien trata de abrir la puerta' },
    { id: 'aac56', unit: 'aac-slide', type: 'mc', ref: 56,
      q: 'Si al retirar una ventana de emergencia de un A320 el tobogán no se infla, debemos inmediatamente:',
      options: ['Redirigir a los pasajeros a otra salida', 'Halar el disparador manual', 'Cerrar la ventana'],
      a: 'Halar el disparador manual' },
    { id: 'aac60', unit: 'aac-slide', type: 'mc', ref: 60,
      q: '¿Cuántos toboganes posee el A320?',
      options: ['4', '6', '3'],
      a: '6' },
    { id: 'aac61', unit: 'aac-slide', type: 'mc', ref: 61,
      q: 'La capacidad normal del tobogán/balsa es de:',
      options: ['55 pasajeros', '44 pasajeros', '43 pasajeros'],
      a: '44 pasajeros' },
    { id: 'aac62', unit: 'aac-slide', type: 'mc', ref: 62,
      q: 'La capacidad máxima de un tobogán/balsa del A320 es de:',
      options: ['44 pasajeros', '55 pasajeros', '69 pasajeros'],
      a: '55 pasajeros' },
    { id: 'aac129', unit: 'aac-slide', type: 'mc', ref: 129,
      q: 'Las ventanas de emergencia, ubicadas sobre las alas, son de tipo tapón:',
      options: ['Pueden ser abiertas solamente por dentro', 'Pueden ser abiertas por fuera y por dentro', 'En el A320 una puede ser abierta por fuera, por cada lado del avión'],
      a: 'Pueden ser abiertas por fuera y por dentro' },
    { id: 'aac130', unit: 'aac-slide', type: 'mc', ref: 130,
      q: 'El A320 está equipado con:',
      options: ['4 salidas de emergencia', '6 salidas de emergencia', '8 salidas de emergencia'],
      a: '8 salidas de emergencia' },
    { id: 'aac132', unit: 'aac-slide', type: 'mc', ref: 132,
      q: 'El tobogán/balsa se activa cuando una de las ventanas ubicadas sobre las alas es abierta durante una emergencia en tierra.',
      options: ['Verdadero', 'Falso'],
      a: 'Falso' },
    { id: 'aac137', unit: 'aac-slide', type: 'mc', ref: 137,
      q: 'Cuando se intenta abrir una de las puertas de la cabina de pasajeros desde afuera y se observa una luz roja encendida, esto significa que:',
      options: ['El tobogán está armado y la puerta no debe ser abierta', 'La presión de la botella de nitrógeno de la puerta está en la zona roja del manómetro', 'La cabina está levemente presurizada y la puerta no debe ser abierta'],
      a: 'La cabina está levemente presurizada y la puerta no debe ser abierta' },

    /* ───────────── Evacuación e impacto ───────────── */
    { id: 'aac14', unit: 'aac-emer', type: 'mc', ref: 14,
      q: 'El término ABP se refiere a:',
      options: ['La clave para indicar a los tripulantes que se tiene un caso de secuestro o de interferencia ilícita', 'Los pasajeros que necesitan asistencia en una evacuación', 'Los pasajeros que pueden brindar ayuda en las salidas de emergencia en caso de evacuación'],
      a: 'Los pasajeros que pueden brindar ayuda en las salidas de emergencia en caso de evacuación' },
    { id: 'aac22', unit: 'aac-emer', type: 'mc', ref: 22,
      q: 'La efectividad y seguridad en los casos de emergencia depende de:',
      options: ['Seguir las instrucciones del capitán', 'Conocimiento de los procedimientos de emergencia y del uso correcto del equipo de emergencia', 'Seguir las instrucciones del jefe de cabina'],
      a: 'Conocimiento de los procedimientos de emergencia y del uso correcto del equipo de emergencia' },
    { id: 'aac47', unit: 'aac-emer', type: 'mc', ref: 47,
      q: 'El propósito del repaso silencioso es:',
      options: ['Estar preparado y listo para responder a una emergencia durante el despegue y el aterrizaje', 'Repasar las tareas concernientes al resto del vuelo', 'Recordar las tareas asignadas para el servicio'],
      a: 'Estar preparado y listo para responder a una emergencia durante el despegue y el aterrizaje' },
    { id: 'aac48', unit: 'aac-emer', type: 'mc', ref: 48,
      q: 'El propósito de la posición de impacto es:',
      options: ['Evitar que los pasajeros se pongan de pie', 'Minimizar lesiones durante el impacto', 'Asegurar a los pasajeros a los asientos'],
      a: 'Minimizar lesiones durante el impacto' },
    { id: 'aac49', unit: 'aac-emer', type: 'mc', ref: 49,
      q: 'Las siglas TEST definen:',
      options: ['Tipo de emergencia, Evacuación, Señal para tomar posición de impacto y Tiempo', 'Tipo de emergencia, Evaluación, Señal y Tiempo', 'Tiempo, Evaluación, Salidas y Tipo de emergencia'],
      a: 'Tipo de emergencia, Evacuación, Señal para tomar posición de impacto y Tiempo' },
    { id: 'aac69', unit: 'aac-emer', type: 'mc', ref: 69,
      q: 'El capitán dará la orden de tomar posición de impacto a los:',
      options: ['12,000 pies', '3,000 pies', '500 pies'],
      a: '500 pies' },
    { id: 'aac70', unit: 'aac-emer', type: 'mc', ref: 70,
      q: 'Antes de abrir una salida de emergencia hay que:',
      options: ['Esperar que el capitán encienda las luces de emergencia', 'Esperar la orden de evacuar', 'Verificar condiciones interiores y exteriores'],
      a: 'Verificar condiciones interiores y exteriores' },
    { id: 'aac72', unit: 'aac-emer', type: 'mc', ref: 72,
      q: 'Los primeros tres pasos en la preparación de la cabina para un amarizaje son:',
      options: ['Anuncio de la emergencia, retirar objetos punzantes, chalecos, cinturones, mesas y respaldos', 'Cinturones, respaldos y mesas, seleccionar a los ABP, dar reporte al capitán', 'Revisar la salida de emergencia, asignar el equipo de emergencia, asegurar el galley'],
      a: 'Anuncio de la emergencia, retirar objetos punzantes, chalecos, cinturones, mesas y respaldos' },
    { id: 'aac73', unit: 'aac-emer', type: 'mc', ref: 73,
      q: 'En una evacuación en tierra, el tripulante n.º 2 encuentra su salida bloqueada. ¿Qué orden les daría a sus pasajeros?',
      options: ['«Salida bloqueada, vaya a la otra salida»', '«Puerta bloqueada, devuélvanse»', '«Puerta bloqueada, use la otra»'],
      a: '«Salida bloqueada, vaya a la otra salida»' },
    { id: 'aac90', unit: 'aac-emer', type: 'mc', ref: 90,
      q: '¿Cuál es el procedimiento correcto en caso de incapacidad del piloto?',
      options: ['Mover el asiento del piloto incapacitado hacia atrás y reclinar el respaldo', 'Asegurar los arneses del piloto incapacitado, mover el asiento hacia adelante y reclinar el asiento completamente', 'Asegurar e inmovilizar los arneses, mover el asiento completamente hacia atrás y reclinar el asiento completamente'],
      a: 'Asegurar e inmovilizar los arneses, mover el asiento completamente hacia atrás y reclinar el asiento completamente' },

    /* ───────────── Fuego y humo ───────────── */
    { id: 'aac9', unit: 'aac-fuego', type: 'mc', ref: 9,
      q: 'Un fuego clase A es producido por:',
      options: ['Gasolina, aceite, químicos', 'Papel, madera, tela', 'Electricidad'],
      a: 'Papel, madera, tela' },
    { id: 'aac10', unit: 'aac-fuego', type: 'mc', ref: 10,
      q: 'Un fuego clase B es producido por:',
      options: ['Ácidos', 'Electricidad', 'Líquidos inflamables'],
      a: 'Líquidos inflamables' },
    { id: 'aac17', unit: 'aac-fuego', type: 'mc', ref: 17,
      q: 'Los fuegos de tipo B se pueden combatir con extintores de:',
      options: ['Agua', 'Halón', 'Ambos'],
      a: 'Halón' },
    { id: 'aac18', unit: 'aac-fuego', type: 'mc', ref: 18,
      q: 'Los fuegos de tipo A se pueden combatir con extintores de:',
      options: ['Agua', 'Halón', 'Ambos'],
      a: 'Ambos' },
    { id: 'aac25', unit: 'aac-fuego', type: 'mc', ref: 25,
      q: 'Ante la presencia de humo severo en la cabina:',
      options: ['El humo tiende a subir, por lo que los pasajeros deben buscar el nivel más bajo', 'El humo tiende a bajar, por lo que los pasajeros deben buscar el nivel más alto', 'Se deben utilizar las botellas de oxígeno'],
      a: 'El humo tiende a subir, por lo que los pasajeros deben buscar el nivel más bajo' },
    { id: 'aac31', unit: 'aac-fuego', type: 'mc', ref: 31,
      q: 'Si la cabina de pasajeros se llena de humo denso, la tripulación de vuelo ejecutará:',
      options: ['Un descenso de emergencia', 'Una despresurización de cabina', 'Ambas'],
      a: 'Un descenso de emergencia' },
    { id: 'aac37', unit: 'aac-fuego', type: 'mc', ref: 37,
      q: 'La cabina de pasajeros es de tipo A; esto quiere decir que:',
      options: ['Es un compartimiento con ventilación controlada', 'Es un compartimiento con sistema de extinción de fuego desde la cabina de mando', 'Es un compartimiento que tiene extintores de mano accesibles y cualquier tripulante tiene acceso a cualquier rincón para combatir el fuego'],
      a: 'Es un compartimiento que tiene extintores de mano accesibles y cualquier tripulante tiene acceso a cualquier rincón para combatir el fuego' },
    { id: 'aac57', unit: 'aac-fuego', type: 'mc', ref: 57,
      q: 'Es de color gris y generalmente se encuentra uno por aeronave:',
      options: ['Extintor de halón', 'Extintor de agua', 'Extintor de freón'],
      a: 'Extintor de agua' },
    { id: 'aac58', unit: 'aac-fuego', type: 'mc', ref: 58,
      q: 'Estos extintores poseen dos boquillas:',
      options: ['Extintor de freón', 'Extintor de agua', 'Extintor de halón'],
      a: 'Extintor de freón' },
    { id: 'aac59', unit: 'aac-fuego', type: 'mc', ref: 59,
      q: 'Serán usadas cuando el humo o las emanaciones tóxicas impidan apagar un fuego eficazmente:',
      options: ['Detectores de humo en lavatorios', 'PBE', 'Máscaras de oxígeno'],
      a: 'PBE' },
    { id: 'aac64', unit: 'aac-fuego', type: 'mc', ref: 64,
      q: 'Los extintores de los lavatorios del A320 se descargan cuando existe una temperatura de:',
      options: ['170 °F', '174 °F', '180 °F'],
      a: '174 °F' },

    /* ───────────── Descompresión e hipoxia ───────────── */
    { id: 'aac15', unit: 'aac-fisio', type: 'mc', ref: 15,
      q: 'Si un avión que vuela a 35,000 pies sufre una descompresión rápida, el tiempo útil de conciencia es de aproximadamente:',
      options: ['1 minuto', '15 a 20 segundos', '20 a 30 segundos'],
      a: '20 a 30 segundos' },
    { id: 'aac26', unit: 'aac-fisio', type: 'mc', ref: 26,
      q: 'Si ha buceado y debe efectuar un vuelo a más de 8,000 pies de altitud de cabina, deberá esperar:',
      options: ['12 horas', '10 días', '24 horas'],
      a: '24 horas' },
    { id: 'aac27', unit: 'aac-fisio', type: 'mc', ref: 27,
      q: '¿De cuál de estas condiciones resulta la hipoxia?',
      options: ['Excesivo oxígeno en la corriente sanguínea', 'Insuficiente oxígeno llegando al cerebro', 'Excesivo dióxido de carbono en la corriente sanguínea'],
      a: 'Insuficiente oxígeno llegando al cerebro' },
    { id: 'aac29', unit: 'aac-fisio', type: 'mc', ref: 29,
      q: 'Inmediatamente después de una descompresión rápida, la tripulación de vuelo ejecutará:',
      options: ['Un descenso de emergencia', 'Un anuncio a los pasajeros', 'Una inspección de la cabina'],
      a: 'Un descenso de emergencia' },
    { id: 'aac30', unit: 'aac-fisio', type: 'mc', ref: 30,
      q: 'En caso de una descompresión rápida, lo primero que se debe hacer es:',
      options: ['Asistir a los pasajeros con las máscaras', 'Ponerse la máscara de oxígeno más cercana', 'Hacer una inspección de cabina'],
      a: 'Ponerse la máscara de oxígeno más cercana' },
    { id: 'aac40', unit: 'aac-fisio', type: 'mc', ref: 40,
      q: 'A la hora de revisar las botellas de oxígeno, lo más importante que hay que tener en cuenta es:',
      options: ['Que tenga la máscara acoplada a la toma HI', 'Que esté asegurada', 'Ambas son correctas'],
      a: 'Ambas son correctas' },
    { id: 'aac51', unit: 'aac-fisio', type: 'mc', ref: 51,
      q: 'Las máscaras de oxígeno caerán cuando la altitud de la cabina exceda:',
      options: ['Los 10,000 pies', 'Los 14,000 pies', 'Los 5,000 pies'],
      a: 'Los 14,000 pies' },
    { id: 'aac67', unit: 'aac-fisio', type: 'mc', ref: 67,
      q: 'Después de haber donado sangre, el tripulante de cabina debe esperar por lo menos ___ antes de fungir como miembro de la tripulación:',
      options: ['8 horas', '12 horas', '24 horas'],
      a: '24 horas' },
    { id: 'aac80', unit: 'aac-fisio', type: 'mc', ref: 80,
      q: 'Si un avión volando a 18,000 pies tiene una descompresión rápida, el tiempo útil de conciencia es de aproximadamente:',
      options: ['1 a 2 minutos', '20 a 30 minutos', '3 a 5 minutos'],
      a: '20 a 30 minutos' },
    { id: 'aac146', unit: 'aac-fisio', type: 'mc', ref: 146,
      q: 'El tiempo útil de conciencia no puede variar bajo ninguna circunstancia.',
      options: ['Verdadero', 'Falso'],
      a: 'Falso' },

    /* ───────────── ELT y supervivencia ───────────── */
    { id: 'aac11', unit: 'aac-surv', type: 'mc', ref: 11,
      q: '¿En cuáles vuelos se requieren chalecos salvavidas para cada pasajero y tripulante, botes salvavidas y luces pirotécnicas?',
      options: ['En los que sobrevuelan 50 MN o más sobre agua', 'En los que sobrevuelan 30 MN o más sobre agua', 'En los que sobrevuelan 100 MN o más sobre agua'],
      a: 'En los que sobrevuelan 50 MN o más sobre agua' },
    { id: 'aac35', unit: 'aac-surv', type: 'mc', ref: 35,
      q: 'La duración y el alcance de un ELT al ser activado es de:',
      options: ['24 horas y 100 MN', '72 horas y 200 MN', '48 horas y 200 MN'],
      a: '48 horas y 200 MN' },
    { id: 'aac44', unit: 'aac-surv', type: 'mc', ref: 44,
      q: 'El ELT es un dispositivo que:',
      options: ['Emite la señal internacional de emergencia que facilita la localización del avión', 'Emite señales de radio para la navegación', 'Permite la comunicación directa entre los aviones de búsqueda y el avión siniestrado'],
      a: 'Emite la señal internacional de emergencia que facilita la localización del avión' },
    { id: 'aac45', unit: 'aac-surv', type: 'mc', ref: 45,
      q: '¿Cuánto tarda el ELT en activarse si se utiliza en agua dulce o en agua salada?',
      options: ['Agua dulce, 10 minutos; agua salada, 5 minutos', 'Agua dulce, 5 minutos; agua salada, 2 segundos', 'Agua salada, 5 segundos; agua dulce, 5 minutos'],
      a: 'Agua salada, 5 segundos; agua dulce, 5 minutos' },
    { id: 'aac71', unit: 'aac-surv', type: 'mc', ref: 71,
      q: 'El ELT fijo del avión se encuentra:',
      options: ['En la cabina de mando', 'En la parte delantera de la cabina de pasajeros', 'Arriba del galley trasero'],
      a: 'Arriba del galley trasero' },
    { id: 'aac75', unit: 'aac-surv', type: 'mc', ref: 75,
      q: '¿Cuántos elementos para la señalización hay en el bote salvavidas?',
      options: ['6', '5', '4'],
      a: '5' },
    { id: 'aac76', unit: 'aac-surv', type: 'mc', ref: 76,
      q: '¿En qué momento hay que sacar y asegurar el bote salvavidas?',
      options: ['Cuando el avión se haya detenido', 'Cuando el capitán dé la orden de evacuar', 'Cuando el jefe de cabina lo ordene'],
      a: 'Cuando el capitán dé la orden de evacuar' },
    { id: 'aac77', unit: 'aac-surv', type: 'mc', ref: 77,
      q: 'La secuencia correcta de los principios de sobrevivencia en el mar es:',
      options: ['Señalización, flotación, sobrevivencia', 'Flotación, sobrevivencia, señalización', 'Sobrevivencia, señalización, flotación'],
      a: 'Flotación, sobrevivencia, señalización' },
    { id: 'aac78', unit: 'aac-surv', type: 'mc', ref: 78,
      q: 'En un amaraje, el primer paso de sobrevivencia en condiciones frías es:',
      options: ['Instalar el toldo', 'Remover la ropa húmeda y secarla', 'Mantener el bote lo más seco posible'],
      a: 'Instalar el toldo' },
    { id: 'aac85', unit: 'aac-surv', type: 'mc', ref: 85,
      q: 'Transmite en 121.5 y en 243.0 MHz:',
      options: ['ELT', 'Rescue 99', '1 y 2 son correctas'],
      a: '1 y 2 son correctas' },

    /* ───────────── Mercancías peligrosas ───────────── */
    { id: 'aac13', unit: 'aac-mp', type: 'mc', ref: 13,
      q: '«Todo objeto o sustancia que, cuando se transporta por vía aérea, puede constituir un riesgo importante para la salud, la seguridad o la propiedad». Esta definición corresponde a:',
      options: ['Productos orgánicos', 'Mercancías peligrosas', 'Carga facturada'],
      a: 'Mercancías peligrosas' },
    { id: 'aac50', unit: 'aac-mp', type: 'mc', ref: 50,
      q: 'Si durante el vuelo la tripulación recibe una amenaza de bomba y se encuentra el dispositivo, usted deberá:',
      options: ['Mover el dispositivo', 'Poner cobijas y toallas húmedas encima del dispositivo', 'Desconectar el dispositivo si puede'],
      a: 'Mover el dispositivo' },
    { id: 'aac88', unit: 'aac-mp', type: 'mc', ref: 88,
      q: 'El entrenamiento recurrente de mercancías peligrosas para tripulantes de cabina se imparte:',
      options: ['Cada 12 meses', 'Cada 24 meses', 'Cada 36 meses'],
      a: 'Cada 12 meses' },
    { id: 'aac96', unit: 'aac-mp', type: 'mc', ref: 96,
      q: 'Suceso asociado y relacionado con el transporte de mercancías peligrosas que produce lesiones mortales o graves a una persona o daños importantes en bienes:',
      options: ['Accidente con mercancías peligrosas', 'Incidente con mercancías peligrosas', 'Actividad que involucra mercancías peligrosas'],
      a: 'Accidente con mercancías peligrosas' },
    { id: 'aac98', unit: 'aac-mp', type: 'mc', ref: 98,
      q: 'El documento que debe llenarse toda vez que se transporten mercancías peligrosas a bordo de una aeronave se denomina:',
      options: ['Lista de verificación en caso de incidentes y accidentes', 'Guía de respuesta de emergencia', 'Notificación al capitán'],
      a: 'Notificación al capitán',
      note: 'Es la NOTOC (Notification to Captain).' },

    /* ───────────── Auxilios a bordo ───────────── */
    { id: 'aac1', unit: 'aac-pa', type: 'mc', ref: 1,
      q: 'Ante un cuadro de intoxicación por alimento se debe:',
      options: ['Recostar a la persona', 'Mantener a la persona tranquila', 'Provocar el vómito'],
      a: 'Provocar el vómito' },
    { id: 'aac2', unit: 'aac-pa', type: 'mc', ref: 2,
      q: 'Un signo de shock se reconoce por:',
      options: ['Piel fría y sudoración', 'Rostro pálido', 'Ambas son correctas'],
      a: 'Ambas son correctas' },
    { id: 'aac3', unit: 'aac-pa', type: 'mc', ref: 3,
      q: 'La maniobra de Heimlich se utiliza en caso de:',
      options: ['Asfixia por obstrucción', 'Intoxicación', 'Paro respiratorio'],
      a: 'Asfixia por obstrucción' },
    { id: 'aac4', unit: 'aac-pa', type: 'mc', ref: 4,
      q: 'A una persona que ha sufrido un desmayo se le debe:',
      options: ['Dejar quieta hasta que la atienda un médico', 'Acostar utilizando el tratamiento de shock', 'Ninguna de las anteriores'],
      a: 'Acostar utilizando el tratamiento de shock' },
    { id: 'aac5', unit: 'aac-pa', type: 'mc', ref: 5,
      q: 'El tratamiento de shock consiste en:',
      options: ['Acostar a la persona con las piernas a un nivel más bajo que la cabeza', 'Acostar a la persona con las piernas a un nivel más alto que la cabeza', 'Dar RCP a la persona'],
      a: 'Acostar a la persona con las piernas a un nivel más alto que la cabeza' },
    { id: 'aac63', unit: 'aac-pa', type: 'mc', ref: 63,
      q: 'El orden de prioridad para aplicar los primeros auxilios es:',
      options: ['Asfixia, hemorragia, shock', 'Hemorragia, asfixia, shock', 'Shock, hemorragia, asfixia'],
      a: 'Hemorragia, asfixia, shock' },
    { id: 'aac89', unit: 'aac-pa', type: 'mc', ref: 89,
      q: 'El orden de prioridad para impartir primeros auxilios es el siguiente:',
      options: ['Quemaduras, asfixia y shock', 'Convulsiones, shock y asfixia', 'Hemorragia, asfixia y shock'],
      a: 'Hemorragia, asfixia y shock' },
    { id: 'aac141', unit: 'aac-pa', type: 'mc', ref: 141,
      q: 'Anotar los datos de identificación del pasajero para la elaboración del reporte correspondiente es parte de:',
      options: ['La descripción de los pasos para la aplicación de primeros auxilios', 'El procedimiento para la aplicación de primeros auxilios', 'El procedimiento en caso de secuestro del avión'],
      a: 'El procedimiento para la aplicación de primeros auxilios' },
    { id: 'aac142', unit: 'aac-pa', type: 'mc', ref: 142,
      q: 'Si la fractura es expuesta, la prioridad es el manejo de la hemorragia, sin movilizar el hueso expuesto.',
      options: ['Verdadero', 'Falso'],
      a: 'Verdadero' },
    { id: 'aac143', unit: 'aac-pa', type: 'mc', ref: 143,
      q: 'Es el aumento en la frecuencia respiratoria:',
      options: ['Hipoventilación', 'Hiperventilación', 'Ninguna de las anteriores'],
      a: 'Hiperventilación' },
    { id: 'aac147', unit: 'aac-pa', type: 'mc', ref: 147,
      q: 'La respiración boca a boca en infantes se inicia con tres respiraciones rápidas y después una respiración cada tres segundos.',
      options: ['Verdadero', 'Falso'],
      a: 'Falso' }
  ]
};
