/* Extensión ESL · Career Paths: Flight Attendant, libro 3.
   Las 15 unidades del libro (entrevistas, formación, bases, reservas,
   programación, CRM, cabina estéril, emergencias, primeros auxilios y
   seguridad) con su vocabulario y la función comunicativa de cada una.
   Traducciones y ejemplos propios; del libro solo se toman el temario y la
   lista de palabras. */
window.CC = window.CC || {};

CC.CP3 = {
  UNITS: [
    { id: 'cp3-01', course: 'esl', src: 'cp3', n: 1, name: 'La entrevista de trabajo', icon: '🤝', hue: 140,
      blurb: 'Interviews: résumé, teamwork, multitask, demeanor…' },
    { id: 'cp3-02', course: 'esl', src: 'cp3', n: 2, name: 'La formación', icon: '🎓', hue: 215,
      blurb: 'Training: recurrent training, HAZMAT, MEL, aircraft type…' },
    { id: 'cp3-03', course: 'esl', src: 'cp3', n: 3, name: 'Traslados y bases', icon: '🏠', hue: 25,
      blurb: 'Relocations and Bases: hub, deadhead, commuter, non-rev…' },
    { id: 'cp3-04', course: 'esl', src: 'cp3', n: 4, name: 'La reserva (guardias)', icon: '📟', hue: 315,
      blurb: 'Reserve Duty: on call, short notice, ready reserve…' },
    { id: 'cp3-05', course: 'esl', src: 'cp3', n: 5, name: 'Horarios y programación', icon: '🗓️', hue: 185,
      blurb: 'Schedules: pairings, block time, line holder, pick up…' },
    { id: 'cp3-06', course: 'esl', src: 'cp3', n: 6, name: 'Bidding: solicitar la programación', icon: '🗳️', hue: 265,
      blurb: 'Bidding: seniority, bid packet, bid award, trip trade…' },
    { id: 'cp3-07', course: 'esl', src: 'cp3', n: 7, name: 'Consejos de servicio al cliente', icon: '🌟', hue: 50,
      blurb: 'Customer Service: composure, defuse, courteous, escalate…' },
    { id: 'cp3-08', course: 'esl', src: 'cp3', n: 8, name: 'Gestión de recursos de la tripulación', icon: '🧠', hue: 245,
      blurb: 'CRM: assertiveness, situational awareness, decision making…' },
    { id: 'cp3-09', course: 'esl', src: 'cp3', n: 9, name: 'La cabina estéril', icon: '🔇', hue: 285,
      blurb: 'The Sterile Cockpit: distraction, non-essential, urgent…' },
    { id: 'cp3-10', course: 'esl', src: 'cp3', n: 10, name: 'Emergencias en vuelo (1): amerizaje', icon: '🌊', hue: 195,
      blurb: 'Flight Emergencies: ditch, raft, life jacket, bird strike…' },
    { id: 'cp3-11', course: 'esl', src: 'cp3', n: 11, name: 'Emergencias en vuelo (2): fuego y aterrizajes', icon: '🔥', hue: 15,
      blurb: 'Flight Emergencies: brace position, smoke, decompression, slide…' },
    { id: 'cp3-12', course: 'esl', src: 'cp3', n: 12, name: 'Emergencias médicas', icon: '🚑', hue: 355,
      blurb: 'Medical Emergencies: CPR, AED, choke, allergic reaction…' },
    { id: 'cp3-13', course: 'esl', src: 'cp3', n: 13, name: 'Primeros auxilios', icon: '🩹', hue: 85,
      blurb: 'First Aid: bandage, sprain, splint, apply pressure…' },
    { id: 'cp3-14', course: 'esl', src: 'cp3', n: 14, name: 'Seguridad a bordo (1): pasajeros conflictivos', icon: '🚨', hue: 40,
      blurb: 'Aircraft Security: intoxicated, abusive, divert, custody…' },
    { id: 'cp3-15', course: 'esl', src: 'cp3', n: 15, name: 'Seguridad a bordo (2): amenazas', icon: '🛡️', hue: 220,
      blurb: 'Aircraft Security: air marshal, restrain, suspicious, weapon…' }
  ],

  CARDS: [
    /* ───────────── 1 · Interviews ───────────── */
    { id: 'cp3-application', unit: 'cp3-01', type: 'def', term: 'Application',
      q: '¿Qué significa «application»?',
      a: 'Solicitud (de empleo)' },
    { id: 'cp3-call-back', unit: 'cp3-01', type: 'def', term: 'Call back',
      q: '¿Qué significa «call back»?',
      a: 'Volver a llamar; segunda convocatoria',
      note: 'Ej.: “I got a call back for a second interview!”' },
    { id: 'cp3-competitive', unit: 'cp3-01', type: 'def', term: 'Competitive',
      q: '¿Qué significa «competitive»?',
      a: 'Competitivo: con muchos candidatos' },
    { id: 'cp3-demeanor', unit: 'cp3-01', type: 'def', term: 'Demeanor',
      q: '¿Qué significa «demeanor»?',
      a: 'Actitud y comportamiento (porte)',
      note: 'Ej.: “a calm, friendly demeanor”.' },
    { id: 'cp3-diploma', unit: 'cp3-01', type: 'def', term: 'Diploma',
      q: '¿Qué significa «diploma»?',
      a: 'Diploma (título de estudios)' },
    { id: 'cp3-friendly', unit: 'cp3-01', type: 'def', term: 'Friendly',
      q: '¿Qué significa «friendly»?',
      a: 'Amable, simpático' },
    { id: 'cp3-group-interview', unit: 'cp3-01', type: 'def', term: 'Group interview',
      q: '¿Qué significa «group interview»?',
      a: 'Entrevista en grupo (dinámica de grupo)' },
    { id: 'cp3-interview', unit: 'cp3-01', type: 'def', term: 'Interview',
      q: '¿Qué significa «interview»?',
      a: 'Entrevista' },
    { id: 'cp3-leadership', unit: 'cp3-01', type: 'def', term: 'Leadership',
      q: '¿Qué significa «leadership»?',
      a: 'Liderazgo' },
    { id: 'cp3-multitask', unit: 'cp3-01', type: 'def', term: 'Multitask',
      q: '¿Qué significa «multitask»?',
      a: 'Hacer varias cosas a la vez' },
    { id: 'cp3-physically-fit', unit: 'cp3-01', type: 'def', term: 'Physically fit',
      q: '¿Qué significa «physically fit»?',
      a: 'En buena forma física' },
    { id: 'cp3-prioritize', unit: 'cp3-01', type: 'def', term: 'Prioritize',
      q: '¿Qué significa «prioritize»?',
      a: 'Priorizar (dar prioridad)' },
    { id: 'cp3-resume', unit: 'cp3-01', type: 'def', term: 'Résumé',
      q: '¿Qué significa «résumé»?',
      a: 'Currículum (hoja de vida)',
      note: 'Se pronuncia “RÉ-zu-mei”. En el Reino Unido se dice «CV».' },
    { id: 'cp3-teamwork', unit: 'cp3-01', type: 'def', term: 'Teamwork',
      q: '¿Qué significa «teamwork»?',
      a: 'Trabajo en equipo' },
    { id: 'cp3-work-experience', unit: 'cp3-01', type: 'def', term: 'Work experience',
      q: '¿Qué significa «work experience»?',
      a: 'Experiencia laboral' },
    { id: 'cp3-01-qualities', unit: 'cp3-01', type: 'list',
      q: 'Qué valoran en una entrevista de auxiliar',
      items: ['Teamwork', 'A friendly demeanor', 'The ability to multitask', 'Leadership'],
      lures: ['Arriving late', 'Poor grooming', 'Criticizing past employers'] },
    { id: 'cp3-01-say', unit: 'cp3-01', type: 'num',
      q: 'En la entrevista te piden un ejemplo de trabajo en equipo. ¿Cómo empiezas?',
      a: 'For instance, at my last job I trained three new colleagues.',
      options: ['For instance, at my last job I trained three new colleagues.', 'For example, in my last work I formed three new colleagues.', 'Per example, at my last job I trained three new colleagues.', 'Like example, at my last job I trained three new colleagues.'],
      say: 'For instance, at my last job I trained three new colleagues.',
      note: '«Formar» a alguien es «train», no «form»; y un empleo es «a job», no «a work».' },
    { id: 'cp3-01-pairs', unit: 'cp3-01', type: 'match',
      q: 'Giving examples: dar ejemplos',
      pairs: [['For example…', 'Por ejemplo…'],
              ['Such as…', 'Como (tales como)…'],
              ['A good example is…', 'Un buen ejemplo es…'],
              ['Let me give you an example', 'Le pongo un ejemplo']] },

    /* ───────────── 2 · Training ───────────── */
    { id: 'cp3-24-hour-clock', unit: 'cp3-02', type: 'def', term: '24-hour clock',
      q: '¿Qué significa «24-hour clock»?',
      a: 'Reloj de 24 horas',
      note: 'Ej.: 14:30 se lee «fourteen thirty».', say: 'twenty-four hour clock' },
    { id: 'cp3-aircraft-type', unit: 'cp3-02', type: 'def', term: 'Aircraft type',
      q: '¿Qué significa «aircraft type»?',
      a: 'Tipo de aeronave (modelo de avión)',
      note: 'Ej.: “Which aircraft types are you qualified on?”' },
    { id: 'cp3-cabin-controls', unit: 'cp3-02', type: 'def', term: 'Cabin controls',
      q: '¿Qué significa «cabin controls»?',
      a: 'Mandos de la cabina: luces, megafonía, temperatura…' },
    { id: 'cp3-code', unit: 'cp3-02', type: 'def', term: 'Code',
      q: '¿Qué significa «code»?',
      a: 'Código' },
    { id: 'cp3-comat', unit: 'cp3-02', type: 'def', term: 'COMAT',
      q: '¿Qué significa «COMAT»?',
      a: 'COMAT: material de la propia compañía transportado en sus vuelos',
      note: 'De «company material».', say: 'Co-mat' },
    { id: 'cp3-equipment', unit: 'cp3-02', type: 'def', term: 'Equipment',
      q: '¿Qué significa «equipment»?',
      a: 'Equipo (material)',
      note: 'Es incontable: «a piece of equipment».' },
    { id: 'cp3-hazmat', unit: 'cp3-02', type: 'def', term: 'HAZMAT',
      q: '¿Qué significa «HAZMAT»?',
      a: 'Materiales peligrosos (mercancías peligrosas)',
      note: 'De «hazardous materials».', say: 'Haz-mat' },
    { id: 'cp3-location', unit: 'cp3-02', type: 'def', term: 'Location',
      q: '¿Qué significa «location»?',
      a: 'Ubicación' },
    { id: 'cp3-log', unit: 'cp3-02', type: 'def', term: 'Log',
      q: '¿Qué significa «log»?',
      a: 'Registro (bitácora); anotar',
      note: 'Ej.: “Log the defect in the cabin logbook.”' },
    { id: 'cp3-manual', unit: 'cp3-02', type: 'def', term: 'Manual',
      q: '¿Qué significa «manual»?',
      a: 'Manual' },
    { id: 'cp3-mel', unit: 'cp3-02', type: 'def', term: 'MEL',
      q: '¿Qué significa «MEL»?',
      a: 'MEL: lista del equipo mínimo con el que el avión puede volar',
      note: 'De «Minimum Equipment List».', say: 'M E L' },
    { id: 'cp3-oxygen-system', unit: 'cp3-02', type: 'def', term: 'Oxygen system',
      q: '¿Qué significa «oxygen system»?',
      a: 'Sistema de oxígeno' },
    { id: 'cp3-recurrent-training', unit: 'cp3-02', type: 'def', term: 'Recurrent training',
      q: '¿Qué significa «recurrent training»?',
      a: 'Entrenamiento periódico (recurrente)',
      note: 'Se repite cada año para mantener la habilitación.' },
    { id: 'cp3-safety', unit: 'cp3-02', type: 'def', term: 'Safety',
      q: '¿Qué significa «safety»?',
      a: 'Seguridad operacional (frente a accidentes)',
      note: '«Safety» protege de accidentes; «security», de actos ilícitos.' },
    { id: 'cp3-training-flight', unit: 'cp3-02', type: 'def', term: 'Training flight',
      q: '¿Qué significa «training flight»?',
      a: 'Vuelo de entrenamiento (de prácticas)' },
    { id: 'cp3-02-acronyms', unit: 'cp3-02', type: 'match',
      q: 'Siglas de la formación y su significado',
      pairs: [['HAZMAT', 'Hazardous materials'],
              ['COMAT', 'Company material'],
              ['MEL', 'Minimum Equipment List'],
              ['CRM', 'Crew resource management']] },
    { id: 'cp3-02-say', unit: 'cp3-02', type: 'num',
      q: 'Le explicas a un alumno qué es lo más importante a bordo. ¿Qué dices?',
      a: 'Safety always comes first.',
      options: ['Safety always comes first.', 'Safety always goes in first place.', 'Safety is always the first thing first.', 'Safety always is first of all.'],
      say: 'Safety always comes first.',
      note: '«Come first» = «ser lo primero, tener prioridad».' },
    { id: 'cp3-02-pairs', unit: 'cp3-02', type: 'match',
      q: 'Talking about priorities: prioridades',
      pairs: [['Safety comes first', 'La seguridad es lo primero'],
              ['The top priority is…', 'La máxima prioridad es…'],
              ['That can wait', 'Eso puede esperar'],
              ['First things first', 'Vamos por partes']] },

    /* ───────────── 3 · Relocations and Bases ───────────── */
    { id: 'cp3-assignment', unit: 'cp3-03', type: 'def', term: 'Assignment',
      q: '¿Qué significa «assignment»?',
      a: 'Asignación: destino o tarea asignada' },
    { id: 'cp3-base', unit: 'cp3-03', type: 'def', term: 'Base',
      q: '¿Qué significa «base»?',
      a: 'Base: la ciudad donde empiezan y terminan tus viajes',
      syn: ['Domicile'] },
    { id: 'cp3-commuter', unit: 'cp3-03', type: 'def', term: 'Commuter',
      q: '¿Qué significa «commuter»?',
      a: 'Tripulante que vive en otra ciudad y viaja a su base para trabajar' },
    { id: 'cp3-deadhead', unit: 'cp3-03', type: 'def', term: 'Deadhead',
      q: '¿Qué significa «deadhead»?',
      a: 'Viajar como pasajero por trabajo (posicionamiento)',
      note: 'El tripulante va a otro aeropuerto para empezar un viaje, pero no trabaja en ese vuelo.' },
    { id: 'cp3-domicile', unit: 'cp3-03', type: 'def', term: 'Domicile',
      q: '¿Qué significa «domicile»?',
      a: 'Domicilio laboral (base asignada)',
      note: 'En muchas aerolíneas es sinónimo de «base».', syn: ['Base'] },
    { id: 'cp3-ferry', unit: 'cp3-03', type: 'def', term: 'Ferry',
      q: '¿Qué significa «ferry»?',
      a: 'Vuelo ferry: trasladar un avión sin pasajeros',
      note: 'Por mantenimiento, entrega o para reposicionarlo.' },
    { id: 'cp3-hub', unit: 'cp3-03', type: 'def', term: 'Hub',
      q: '¿Qué significa «hub»?',
      a: 'Centro de conexiones: el aeropuerto principal de la aerolínea' },
    { id: 'cp3-jumpseater', unit: 'cp3-03', type: 'def', term: 'Jumpseater',
      q: '¿Qué significa «jumpseater»?',
      a: 'Quien viaja en un asiento plegable de la tripulación sin trabajar' },
    { id: 'cp3-move', unit: 'cp3-03', type: 'def', term: 'Move',
      q: '¿Qué significa «move»?',
      a: 'Mudarse; mudanza',
      syn: ['Relocate'] },
    { id: 'cp3-non-rev', unit: 'cp3-03', type: 'def', term: 'Non-rev',
      q: '¿Qué significa «non-rev»?',
      a: 'Empleado que vuela gratis o con descuento, sin pagar pasaje',
      note: 'De «non-revenue». Viaja si quedan plazas libres.' },
    { id: 'cp3-rank', unit: 'cp3-03', type: 'def', term: 'Rank',
      q: '¿Qué significa «rank»?',
      a: 'Rango (categoría)' },
    { id: 'cp3-relocate', unit: 'cp3-03', type: 'def', term: 'Relocate',
      q: '¿Qué significa «relocate»?',
      a: 'Trasladarse: cambiar de ciudad por trabajo',
      syn: ['Move'] },
    { id: 'cp3-transfer-request', unit: 'cp3-03', type: 'def', term: 'Transfer request',
      q: '¿Qué significa «transfer request»?',
      a: 'Solicitud de traslado' },
    { id: 'cp3-03-say', unit: 'cp3-03', type: 'num',
      q: 'Te han asignado a otra base. ¿Cómo se lo cuentas a un compañero?',
      a: 'I’ve been assigned to the Miami base starting next month.',
      options: ['I’ve been assigned to the Miami base starting next month.', 'I have been assign to the Miami base next month.', 'I’ve been assigning to the Miami base next month.', 'They assigned me to Miami base since next month.'],
      say: 'I’ve been assigned to the Miami base starting next month.',
      note: 'Voz pasiva: «I’ve been assigned to…» (me han asignado a…).' },
    { id: 'cp3-03-pairs', unit: 'cp3-03', type: 'match',
      q: 'Discussing assignments: hablar de asignaciones',
      pairs: [['I’ve been assigned to…', 'Me asignaron a…'],
              ['Where are you based?', '¿Dónde tienes la base?'],
              ['I put in a transfer request', 'Pedí un traslado'],
              ['It starts next month', 'Empieza el mes que viene']] },

    /* ───────────── 4 · Reserve Duty ───────────── */
    { id: 'cp3-cover', unit: 'cp3-04', type: 'def', term: 'Cover',
      q: '¿Qué significa «cover»?',
      a: 'Cubrir: reemplazar a alguien en un vuelo',
      note: 'Ej.: “Can you cover my trip on Friday?”' },
    { id: 'cp3-duty-rig', unit: 'cp3-04', type: 'def', term: 'Duty rig',
      q: '¿Qué significa «duty rig»?',
      a: 'Duty rig: horas de pago garantizadas según la duración de la jornada' },
    { id: 'cp3-duty-free-period', unit: 'cp3-04', type: 'def', term: 'Duty-free period',
      q: '¿Qué significa «duty-free period»?',
      a: 'Período libre de servicio (descanso garantizado)',
      note: 'No confundir con «duty-free», la tienda libre de impuestos.' },
    { id: 'cp3-guaranteed', unit: 'cp3-04', type: 'def', term: 'Guaranteed',
      q: '¿Qué significa «guaranteed»?',
      a: 'Garantizado' },
    { id: 'cp3-mandatory', unit: 'cp3-04', type: 'def', term: 'Mandatory',
      q: '¿Qué significa «mandatory»?',
      a: 'Obligatorio' },
    { id: 'cp3-on-call', unit: 'cp3-04', type: 'def', term: 'On call',
      q: '¿Qué significa «on call»?',
      a: 'De guardia (localizable)',
      note: 'Ej.: “I’m on call this weekend.”' },
    { id: 'cp3-on-short-notice', unit: 'cp3-04', type: 'def', term: 'On short notice',
      q: '¿Qué significa «on short notice»?',
      a: 'Con poca antelación (de última hora)' },
    { id: 'cp3-out-sick', unit: 'cp3-04', type: 'def', term: 'Out sick',
      q: '¿Qué significa «out sick»?',
      a: 'De baja por enfermedad',
      note: 'Ej.: “Two flight attendants called out sick.”' },
    { id: 'cp3-packed', unit: 'cp3-04', type: 'def', term: 'Packed',
      q: '¿Qué significa «packed»?',
      a: 'Con la maleta hecha' },
    { id: 'cp3-prepared', unit: 'cp3-04', type: 'def', term: 'Prepared',
      q: '¿Qué significa «prepared»?',
      a: 'Preparado, listo' },
    { id: 'cp3-ready-reserve', unit: 'cp3-04', type: 'def', term: 'Ready reserve',
      q: '¿Qué significa «ready reserve»?',
      a: 'Reserva en el aeropuerto: esperar allí, listo para salir de inmediato' },
    { id: 'cp3-travel-bag', unit: 'cp3-04', type: 'def', term: 'Travel bag',
      q: '¿Qué significa «travel bag»?',
      a: 'Maleta de viaje' },
    { id: 'cp3-warning', unit: 'cp3-04', type: 'def', term: 'Warning',
      q: '¿Qué significa «warning»?',
      a: 'Aviso, advertencia',
      note: 'Ej.: “Reserves may get only two hours’ warning.”' },
    { id: 'cp3-04-say', unit: 'cp3-04', type: 'num',
      q: 'Llamas a un tripulante de reserva para un vuelo que sale pronto. ¿Qué dices?',
      a: 'We need you at the airport as soon as possible.',
      options: ['We need you at the airport as soon as possible.', 'We need you in the airport so soon as possible.', 'We need that you come to the airport quickly possible.', 'You need come to the airport the most soon.'],
      say: 'We need you at the airport as soon as possible.',
      note: '«Lo antes posible» = «as soon as possible» (ASAP).' },
    { id: 'cp3-04-pairs', unit: 'cp3-04', type: 'match',
      q: 'Describing urgency: expresar urgencia',
      pairs: [['As soon as possible', 'Lo antes posible'],
              ['Right away', 'Enseguida'],
              ['It’s urgent', 'Es urgente'],
              ['There’s no time to lose', 'No hay tiempo que perder']] },

    /* ───────────── 5 · Schedules ───────────── */
    { id: 'cp3-back-to-back', unit: 'cp3-05', type: 'def', term: 'Back-to-back',
      q: '¿Qué significa «back-to-back»?',
      a: 'Seguidos: uno tras otro, sin descanso en medio',
      note: 'Ej.: “I flew back-to-back trips this week.”' },
    { id: 'cp3-block-time', unit: 'cp3-05', type: 'def', term: 'Block time',
      q: '¿Qué significa «block time»?',
      a: 'Tiempo de bloque (de calzos a calzos): desde que el avión deja la puerta hasta que llega a la siguiente' },
    { id: 'cp3-block-in', unit: 'cp3-05', type: 'def', term: 'Block-in',
      q: '¿Qué significa «block-in»?',
      a: 'Llegada a calzos: el avión se detiene en la puerta' },
    { id: 'cp3-block-out', unit: 'cp3-05', type: 'def', term: 'Block-out',
      q: '¿Qué significa «block-out»?',
      a: 'Salida de calzos: el avión empieza a moverse desde la puerta' },
    { id: 'cp3-crew-scheduling', unit: 'cp3-05', type: 'def', term: 'Crew scheduling',
      q: '¿Qué significa «crew scheduling»?',
      a: 'Programación de tripulaciones: el departamento que asigna los vuelos' },
    { id: 'cp3-drop', unit: 'cp3-05', type: 'def', term: 'Drop',
      q: '¿Qué significa «drop»?',
      a: 'Soltar (dejar) un viaje',
      note: 'Ej.: “I dropped my Tuesday trip.”' },
    { id: 'cp3-line', unit: 'cp3-05', type: 'def', term: 'Line',
      q: '¿Qué significa «line»?',
      a: 'Línea: el calendario mensual de viajes de un tripulante' },
    { id: 'cp3-line-holder', unit: 'cp3-05', type: 'def', term: 'Line holder',
      q: '¿Qué significa «line holder»?',
      a: 'Tripulante con línea fija (no de reserva)' },
    { id: 'cp3-monthly-guarantee', unit: 'cp3-05', type: 'def', term: 'Monthly guarantee',
      q: '¿Qué significa «monthly guarantee»?',
      a: 'Garantía mensual: horas mínimas pagadas al mes' },
    { id: 'cp3-pairings', unit: 'cp3-05', type: 'def', term: 'Pairings',
      q: '¿Qué significa «pairings»?',
      a: 'Viajes programados: secuencias de vuelos que salen de la base y vuelven a ella',
      syn: ['Rotation', 'Sequence', 'Trip'] },
    { id: 'cp3-pick-up', unit: 'cp3-05', type: 'def', term: 'Pick up',
      q: '¿Qué significa «pick up»?',
      a: 'Tomar un viaje extra',
      note: 'Ej.: “I picked up an extra trip to Cancún.”' },
    { id: 'cp3-reassignment', unit: 'cp3-05', type: 'def', term: 'Reassignment',
      q: '¿Qué significa «reassignment»?',
      a: 'Reasignación: cambio de viaje que hace la programación' },
    { id: 'cp3-rotation', unit: 'cp3-05', type: 'def', term: 'Rotation',
      q: '¿Qué significa «rotation»?',
      a: 'Rotación: viaje de ida y vuelta a la base',
      syn: ['Pairings', 'Sequence', 'Trip'] },
    { id: 'cp3-sequence', unit: 'cp3-05', type: 'def', term: 'Sequence',
      q: '¿Qué significa «sequence»?',
      a: 'Secuencia: serie de vuelos de un mismo viaje',
      syn: ['Pairings', 'Rotation', 'Trip'] },
    { id: 'cp3-thirty-in-seven', unit: 'cp3-05', type: 'def', term: 'Thirty-in-seven',
      q: '¿Qué significa «thirty-in-seven»?',
      a: 'Treinta en siete: límite de 30 horas de vuelo en cualquier período de 7 días',
      say: 'Thirty in seven' },
    { id: 'cp3-trip', unit: 'cp3-05', type: 'def', term: 'Trip',
      q: '¿Qué significa «trip»?',
      a: 'Viaje (de uno o varios días)',
      syn: ['Pairings', 'Rotation', 'Sequence'] },
    { id: 'cp3-05-say', unit: 'cp3-05', type: 'num',
      q: 'Dudas si dejar un viaje y quieres la opinión de un compañero. ¿Qué preguntas?',
      a: 'Do you think I should drop this trip?',
      options: ['Do you think I should drop this trip?', 'You think I should to drop this trip?', 'Do you think I should dropping this trip?', 'What you think, I drop this trip?'],
      say: 'Do you think I should drop this trip?',
      note: '«Should» va seguido del verbo sin «to».' },
    { id: 'cp3-05-pairs', unit: 'cp3-05', type: 'match',
      q: 'Asking for advice: pedir consejo',
      pairs: [['Should I…?', '¿Debería…?'],
              ['What would you do?', '¿Tú qué harías?'],
              ['Any advice?', '¿Algún consejo?'],
              ['Is it a good idea to…?', '¿Es buena idea…?']] },

    /* ───────────── 6 · Bidding ───────────── */
    { id: 'cp3-basis', unit: 'cp3-06', type: 'def', term: 'Basis',
      q: '¿Qué significa «basis»?',
      a: 'Base, criterio',
      note: 'Ej.: “Lines are awarded on the basis of seniority.”' },
    { id: 'cp3-bid-award', unit: 'cp3-06', type: 'def', term: 'Bid award',
      q: '¿Qué significa «bid award»?',
      a: 'Adjudicación: el resultado de las solicitudes' },
    { id: 'cp3-bid-line', unit: 'cp3-06', type: 'def', term: 'Bid line',
      q: '¿Qué significa «bid line»?',
      a: 'Línea solicitable: calendario de viajes que se puede pedir' },
    { id: 'cp3-bid-packet', unit: 'cp3-06', type: 'def', term: 'Bid packet',
      q: '¿Qué significa «bid packet»?',
      a: 'Paquete de programación: los viajes y líneas disponibles del mes' },
    { id: 'cp3-bid-period', unit: 'cp3-06', type: 'def', term: 'Bid period',
      q: '¿Qué significa «bid period»?',
      a: 'Período de solicitud: el mes que se programa' },
    { id: 'cp3-bid-sheet', unit: 'cp3-06', type: 'def', term: 'Bid sheet',
      q: '¿Qué significa «bid sheet»?',
      a: 'Hoja de solicitud con tus preferencias' },
    { id: 'cp3-bidding', unit: 'cp3-06', type: 'def', term: 'Bidding',
      q: '¿Qué significa «bidding»?',
      a: 'Solicitud de programación: pedir viajes por orden de preferencia' },
    { id: 'cp3-determine', unit: 'cp3-06', type: 'def', term: 'Determine',
      q: '¿Qué significa «determine»?',
      a: 'Determinar, decidir' },
    { id: 'cp3-junior', unit: 'cp3-06', type: 'def', term: 'Junior',
      q: '¿Qué significa «junior»?',
      a: 'De poca antigüedad (novato)',
      note: 'Lo contrario es «senior».' },
    { id: 'cp3-request', unit: 'cp3-06', type: 'def', term: 'Request',
      q: '¿Qué significa «request»?',
      a: 'Solicitud; solicitar' },
    { id: 'cp3-seniority', unit: 'cp3-06', type: 'def', term: 'Seniority',
      q: '¿Qué significa «seniority»?',
      a: 'Antigüedad (en la empresa)',
      note: 'Decide quién elige primero vuelos, vacaciones y bases.' },
    { id: 'cp3-trip-trade', unit: 'cp3-06', type: 'def', term: 'Trip trade',
      q: '¿Qué significa «trip trade»?',
      a: 'Intercambio de viajes entre tripulantes' },
    { id: 'cp3-06-say', unit: 'cp3-06', type: 'num',
      q: 'Tienes que decirle a un compañero que no le dieron las vacaciones que pidió. ¿Cómo empiezas?',
      a: 'I’m afraid I have some bad news.',
      options: ['I’m afraid I have some bad news.', 'I’m afraid I have a bad new.', 'I’m afraid I have some bad newses.', 'Sorry, I have bads news.'],
      say: 'I’m afraid I have some bad news.',
      note: '«News» es incontable y termina en s: «some news», «the news is…».' },
    { id: 'cp3-06-pairs', unit: 'cp3-06', type: 'match',
      q: 'Delivering bad news: dar malas noticias',
      pairs: [['I’m afraid…', 'Me temo que…'],
              ['Unfortunately…', 'Por desgracia…'],
              ['I’m sorry to tell you…', 'Siento decirte…'],
              ['I know this isn’t what you wanted to hear', 'Sé que no es lo que querías oír']] },

    /* ───────────── 7 · Customer Service Tips ───────────── */
    { id: 'cp3-challenging', unit: 'cp3-07', type: 'def', term: 'Challenging',
      q: '¿Qué significa «challenging»?',
      a: 'Difícil: que supone un reto' },
    { id: 'cp3-communication', unit: 'cp3-07', type: 'def', term: 'Communication',
      q: '¿Qué significa «communication»?',
      a: 'Comunicación' },
    { id: 'cp3-composure', unit: 'cp3-07', type: 'def', term: 'Composure',
      q: '¿Qué significa «composure»?',
      a: 'Compostura (calma)',
      note: 'Ej.: “Keep your composure, even with rude passengers.”' },
    { id: 'cp3-courteous', unit: 'cp3-07', type: 'def', term: 'Courteous',
      q: '¿Qué significa «courteous»?',
      a: 'Cortés, atento' },
    { id: 'cp3-customer-service', unit: 'cp3-07', type: 'def', term: 'Customer service',
      q: '¿Qué significa «customer service»?',
      a: 'Servicio (atención) al cliente' },
    { id: 'cp3-deep-breath', unit: 'cp3-07', type: 'def', term: 'Deep breath',
      q: '¿Qué significa «deep breath»?',
      a: 'Respiración profunda',
      note: 'Ej.: “Take a deep breath before you respond.”' },
    { id: 'cp3-defuse', unit: 'cp3-07', type: 'def', term: 'Defuse',
      q: '¿Qué significa «defuse»?',
      a: 'Calmar una situación tensa',
      note: 'Literalmente, desactivar una bomba.' },
    { id: 'cp3-effective', unit: 'cp3-07', type: 'def', term: 'Effective',
      q: '¿Qué significa «effective»?',
      a: 'Eficaz',
      note: 'Falso amigo: no es «efectivo» (dinero), que se dice «cash».' },
    { id: 'cp3-escalate', unit: 'cp3-07', type: 'def', term: 'Escalate',
      q: '¿Qué significa «escalate»?',
      a: 'Agravarse, ir a más',
      note: 'Ej.: “Don’t let the argument escalate.”' },
    { id: 'cp3-flexible', unit: 'cp3-07', type: 'def', term: 'Flexible',
      q: '¿Qué significa «flexible»?',
      a: 'Flexible' },
    { id: 'cp3-judgment', unit: 'cp3-07', type: 'def', term: 'Judgment',
      q: '¿Qué significa «judgment»?',
      a: 'Criterio (buen juicio)',
      note: 'Ej.: “Use your best judgment.”' },
    { id: 'cp3-misunderstanding', unit: 'cp3-07', type: 'def', term: 'Misunderstanding',
      q: '¿Qué significa «misunderstanding»?',
      a: 'Malentendido' },
    { id: 'cp3-patient', unit: 'cp3-07', type: 'def', term: 'Patient',
      q: '¿Qué significa «patient»?',
      a: 'Paciente (que tiene paciencia)',
      note: 'También es sustantivo: un paciente en el hospital.' },
    { id: 'cp3-professional', unit: 'cp3-07', type: 'def', term: 'Professional',
      q: '¿Qué significa «professional»?',
      a: 'Profesional' },
    { id: 'cp3-reach-out', unit: 'cp3-07', type: 'def', term: 'Reach out',
      q: '¿Qué significa «reach out»?',
      a: 'Contactar, acercarse para ayudar',
      note: 'Ej.: “Reach out to the passenger before the problem grows.”' },
    { id: 'cp3-upset', unit: 'cp3-07', type: 'def', term: 'Upset',
      q: '¿Qué significa «upset»?',
      a: 'Molesto, disgustado' },
    { id: 'cp3-07-say', unit: 'cp3-07', type: 'num',
      q: 'Necesitas que un compañero vigile el carrito un momento. ¿Qué le pides?',
      a: 'Could you do me a favor and watch the cart for a minute?',
      options: ['Could you do me a favor and watch the cart for a minute?', 'Could you make me a favor and watch the cart?', 'Can you do a favor to me and watch the cart?', 'Do me the favor to watch the cart a minute?'],
      say: 'Could you do me a favor and watch the cart for a minute?',
      note: '«Hacer un favor» es «do a favor», no «make».' },
    { id: 'cp3-07-pairs', unit: 'cp3-07', type: 'match',
      q: 'Asking for a favor: pedir un favor',
      pairs: [['Could you do me a favor?', '¿Me haces un favor?'],
              ['Would you mind…?', '¿Te importaría…?'],
              ['I’d really appreciate it', 'Te lo agradecería mucho'],
              ['I owe you one', 'Te debo una']] },

    /* ───────────── 8 · Crew Resource Management (CRM) ───────────── */
    { id: 'cp3-address', unit: 'cp3-08', type: 'def', term: 'Address',
      q: '¿Qué significa «address»?',
      a: 'Abordar, tratar (un problema)',
      note: 'Ej.: “We need to address this issue now.” También es «dirigirse a» alguien.' },
    { id: 'cp3-agreement', unit: 'cp3-08', type: 'def', term: 'Agreement',
      q: '¿Qué significa «agreement»?',
      a: 'Acuerdo' },
    { id: 'cp3-analysis', unit: 'cp3-08', type: 'def', term: 'Analysis',
      q: '¿Qué significa «analysis»?',
      a: 'Análisis' },
    { id: 'cp3-assertiveness', unit: 'cp3-08', type: 'def', term: 'Assertiveness',
      q: '¿Qué significa «assertiveness»?',
      a: 'Asertividad: decir lo que piensas con claridad y respeto' },
    { id: 'cp3-concern', unit: 'cp3-08', type: 'def', term: 'Concern',
      q: '¿Qué significa «concern»?',
      a: 'Preocupación (inquietud)',
      note: 'Ej.: “I have a safety concern.”' },
    { id: 'cp3-crew-resource-management-crm', unit: 'cp3-08', type: 'def', term: 'Crew resource management (CRM)',
      q: '¿Qué significa «crew resource management (CRM)»?',
      a: 'Gestión de recursos de la tripulación: trabajar en equipo para volar seguro',
      say: 'Crew resource management' },
    { id: 'cp3-decision-making', unit: 'cp3-08', type: 'def', term: 'Decision making',
      q: '¿Qué significa «decision making»?',
      a: 'Toma de decisiones' },
    { id: 'cp3-opening', unit: 'cp3-08', type: 'def', term: 'Opening',
      q: '¿Qué significa «opening»?',
      a: 'Apertura: llamar la atención de la persona antes de plantear el problema' },
    { id: 'cp3-problem-solving', unit: 'cp3-08', type: 'def', term: 'Problem solving',
      q: '¿Qué significa «problem solving»?',
      a: 'Resolución de problemas' },
    { id: 'cp3-recommend', unit: 'cp3-08', type: 'def', term: 'Recommend',
      q: '¿Qué significa «recommend»?',
      a: 'Recomendar' },
    { id: 'cp3-situational-awareness', unit: 'cp3-08', type: 'def', term: 'Situational awareness',
      q: '¿Qué significa «situational awareness»?',
      a: 'Conciencia situacional: saber qué pasa a tu alrededor' },
    { id: 'cp3-solution', unit: 'cp3-08', type: 'def', term: 'Solution',
      q: '¿Qué significa «solution»?',
      a: 'Solución' },
    { id: 'cp3-state', unit: 'cp3-08', type: 'def', term: 'State',
      q: '¿Qué significa «state»?',
      a: 'Expresar, decir claramente',
      note: 'Ej.: “State your concern clearly.” Como sustantivo es «estado».' },
    { id: 'cp3-08-order', unit: 'cp3-08', type: 'order',
      q: 'Ordena los pasos para plantear una inquietud (CRM)',
      steps: ['Opening: get the person’s attention',
              'State your concern',
              'State the problem as you see it',
              'Propose a solution',
              'Obtain agreement'] },
    { id: 'cp3-08-say', unit: 'cp3-08', type: 'num',
      q: 'Hueles a quemado y el comandante duda. ¿Cómo expresas una opinión firme?',
      a: 'Captain, I strongly believe we need to act now.',
      options: ['Captain, I strongly believe we need to act now.', 'Captain, I strong believe we need act now.', 'Captain, I am believing strongly we must to act.', 'Captain, maybe we could possibly act, if you want.'],
      say: 'Captain, I strongly believe we need to act now.',
      note: 'En CRM, la asertividad es clara y directa sin ser agresiva.' },
    { id: 'cp3-08-pairs', unit: 'cp3-08', type: 'match',
      q: 'Giving a strong opinion: opinar con firmeza',
      pairs: [['I strongly believe…', 'Creo firmemente que…'],
              ['I’m convinced that…', 'Estoy convencido de que…'],
              ['There’s no doubt that…', 'No hay duda de que…'],
              ['I feel very strongly about this', 'Lo tengo muy claro']] },

    /* ───────────── 9 · The Sterile Cockpit ───────────── */
    { id: 'cp3-aborted-takeoff', unit: 'cp3-09', type: 'def', term: 'Aborted takeoff',
      q: '¿Qué significa «aborted takeoff»?',
      a: 'Despegue abortado (interrumpido)',
      note: 'También se dice «rejected takeoff».' },
    { id: 'cp3-accident', unit: 'cp3-09', type: 'def', term: 'Accident',
      q: '¿Qué significa «accident»?',
      a: 'Accidente' },
    { id: 'cp3-distraction', unit: 'cp3-09', type: 'def', term: 'Distraction',
      q: '¿Qué significa «distraction»?',
      a: 'Distracción' },
    { id: 'cp3-eliminate', unit: 'cp3-09', type: 'def', term: 'Eliminate',
      q: '¿Qué significa «eliminate»?',
      a: 'Eliminar' },
    { id: 'cp3-emergency', unit: 'cp3-09', type: 'def', term: 'Emergency',
      q: '¿Qué significa «emergency»?',
      a: 'Emergencia' },
    { id: 'cp3-exception', unit: 'cp3-09', type: 'def', term: 'Exception',
      q: '¿Qué significa «exception»?',
      a: 'Excepción',
      note: 'Ej.: “The only exception is a safety issue.”' },
    { id: 'cp3-incident', unit: 'cp3-09', type: 'def', term: 'Incident',
      q: '¿Qué significa «incident»?',
      a: 'Incidente: suceso menos grave que un accidente' },
    { id: 'cp3-limit', unit: 'cp3-09', type: 'def', term: 'Limit',
      q: '¿Qué significa «limit»?',
      a: 'Limitar; límite' },
    { id: 'cp3-missed-approach', unit: 'cp3-09', type: 'def', term: 'Missed approach',
      q: '¿Qué significa «missed approach»?',
      a: 'Aproximación frustrada: el avión no aterriza y vuelve a subir',
      note: 'También se dice «go-around».' },
    { id: 'cp3-non-essential', unit: 'cp3-09', type: 'def', term: 'Non-essential',
      q: '¿Qué significa «non-essential»?',
      a: 'No esencial (innecesario)' },
    { id: 'cp3-seal', unit: 'cp3-09', type: 'def', term: 'Seal',
      q: '¿Qué significa «seal»?',
      a: 'Sellar: cerrar por completo' },
    { id: 'cp3-sterile-cockpit', unit: 'cp3-09', type: 'def', term: 'Sterile cockpit',
      q: '¿Qué significa «sterile cockpit»?',
      a: 'Cabina estéril: en las fases críticas solo se habla de lo esencial para el vuelo',
      note: 'Por debajo de 10 000 pies no se llama a los pilotos salvo por algo urgente o de seguridad.' },
    { id: 'cp3-urgent', unit: 'cp3-09', type: 'def', term: 'Urgent',
      q: '¿Qué significa «urgent»?',
      a: 'Urgente' },
    { id: 'cp3-09-phases', unit: 'cp3-09', type: 'list',
      q: 'Fases en las que rige la cabina estéril',
      items: ['Taxi', 'Takeoff', 'Landing'],
      lures: ['Cruise at 35,000 feet', 'Boarding at the gate'] },
    { id: 'cp3-09-say', unit: 'cp3-09', type: 'num',
      q: 'Aconsejas a un auxiliar nuevo cuándo llamar a la cabina de mando. ¿Qué frase es correcta?',
      a: 'I’d recommend waiting until we reach cruising altitude.',
      options: ['I’d recommend waiting until we reach cruising altitude.', 'I’d recommend to wait until we reach cruising altitude.', 'I recommend you wait until we will reach cruising altitude.', 'I’d recommend you waiting until we reach cruising.'],
      say: 'I’d recommend waiting until we reach cruising altitude.',
      note: 'Tras «recommend» va -ing («recommend waiting») o «that you wait», no «to wait».' },
    { id: 'cp3-09-pairs', unit: 'cp3-09', type: 'match',
      q: 'Making a recommendation: recomendar',
      pairs: [['I’d recommend…', 'Yo recomendaría…'],
              ['It’s best to…', 'Lo mejor es…'],
              ['You’d better…', 'Más vale que…'],
              ['Make sure you…', 'Asegúrate de…']] },

    /* ───────────── 10 · Flight Emergencies 1 ───────────── */
    { id: 'cp3-bird-strike', unit: 'cp3-10', type: 'def', term: 'Bird strike',
      q: '¿Qué significa «bird strike»?',
      a: 'Impacto con aves' },
    { id: 'cp3-ditch', unit: 'cp3-10', type: 'def', term: 'Ditch',
      q: '¿Qué significa «ditch»?',
      a: 'Amerizar: aterrizar de emergencia en el agua',
      syn: ['Water landing'] },
    { id: 'cp3-emergency-locator-transmitter-elt', unit: 'cp3-10', type: 'def', term: 'Emergency locator transmitter (ELT)',
      q: '¿Qué significa «emergency locator transmitter (ELT)»?',
      a: 'Transmisor localizador de emergencia: emite la posición del avión',
      say: 'Emergency locator transmitter' },
    { id: 'cp3-engine-failure', unit: 'cp3-10', type: 'def', term: 'Engine failure',
      q: '¿Qué significa «engine failure»?',
      a: 'Falla de motor' },
    { id: 'cp3-evacuate', unit: 'cp3-10', type: 'def', term: 'Evacuate',
      q: '¿Qué significa «evacuate»?',
      a: 'Evacuar' },
    { id: 'cp3-event', unit: 'cp3-10', type: 'def', term: 'Event',
      q: '¿Qué significa «event»?',
      a: 'Suceso, situación',
      note: 'Ej.: “In the event of a water landing…” = en caso de amerizaje.' },
    { id: 'cp3-flotation-device', unit: 'cp3-10', type: 'def', term: 'Flotation device',
      q: '¿Qué significa «flotation device»?',
      a: 'Dispositivo de flotación',
      note: 'Ej.: “Your seat cushion can be used as a flotation device.”', syn: ['Life jacket'] },
    { id: 'cp3-guide', unit: 'cp3-10', type: 'def', term: 'Guide',
      q: '¿Qué significa «guide»?',
      a: 'Guiar' },
    { id: 'cp3-inflate', unit: 'cp3-10', type: 'def', term: 'Inflate',
      q: '¿Qué significa «inflate»?',
      a: 'Inflar',
      note: 'El chaleco se infla al salir del avión, nunca dentro.' },
    { id: 'cp3-life-jacket', unit: 'cp3-10', type: 'def', term: 'Life jacket',
      q: '¿Qué significa «life jacket»?',
      a: 'Chaleco salvavidas',
      syn: ['Flotation device'] },
    { id: 'cp3-orderly', unit: 'cp3-10', type: 'def', term: 'Orderly',
      q: '¿Qué significa «orderly»?',
      a: 'Ordenado (de forma ordenada)',
      note: 'Ej.: “an orderly evacuation”.' },
    { id: 'cp3-raft', unit: 'cp3-10', type: 'def', term: 'Raft',
      q: '¿Qué significa «raft»?',
      a: 'Balsa salvavidas' },
    { id: 'cp3-water-landing', unit: 'cp3-10', type: 'def', term: 'Water landing',
      q: '¿Qué significa «water landing»?',
      a: 'Aterrizaje en el agua (amerizaje)',
      syn: ['Ditch'] },
    { id: 'cp3-10-ditching', unit: 'cp3-10', type: 'list',
      q: 'En un amerizaje, los pasajeros deben…',
      items: ['Put on their life jackets', 'Inflate them when leaving the aircraft', 'Leave everything behind'],
      lures: ['Inflate them inside the cabin', 'Take their carry-on bags', 'Swim away from the raft'] },
    { id: 'cp3-10-say', unit: 'cp3-10', type: 'num',
      q: 'Antes de un amerizaje, recuerdas lo del chaleco. ¿Qué dices?',
      a: 'Remember: do not inflate your life jacket until you leave the aircraft.',
      options: ['Remember: do not inflate your life jacket until you leave the aircraft.', 'Remember: not inflate your life jacket until you leave the aircraft.', 'Remember: don’t inflate your life jacket before you will leave.', 'Remember: inflate your life jacket now, inside the aircraft.'],
      say: 'Remember: do not inflate your life jacket until you leave the aircraft.',
      note: 'Si se infla dentro, puede atraparte cuando entre agua en la cabina.' },
    { id: 'cp3-10-pairs', unit: 'cp3-10', type: 'match',
      q: 'Giving a reminder: recordatorios en emergencias',
      pairs: [['Remember to…', 'Recuerden…'],
              ['Do not forget…', 'No olviden…'],
              ['Keep in mind that…', 'Tengan presente que…'],
              ['Once again…', 'Una vez más…']] },

    /* ───────────── 11 · Flight Emergencies 2 ───────────── */
    { id: 'cp3-brace-position', unit: 'cp3-11', type: 'def', term: 'Brace position',
      q: '¿Qué significa «brace position»?',
      a: 'Posición de impacto (de protección)' },
    { id: 'cp3-command', unit: 'cp3-11', type: 'def', term: 'Command',
      q: '¿Qué significa «command»?',
      a: 'Orden (voz de mando)',
      note: 'Ej.: “Shout your commands loudly and clearly.”' },
    { id: 'cp3-crash-landing', unit: 'cp3-11', type: 'def', term: 'Crash landing',
      q: '¿Qué significa «crash landing»?',
      a: 'Aterrizaje accidentado: el avión toca tierra con impacto y daños' },
    { id: 'cp3-decompression', unit: 'cp3-11', type: 'def', term: 'Decompression',
      q: '¿Qué significa «decompression»?',
      a: 'Despresurización (descompresión)' },
    { id: 'cp3-emergency-lights', unit: 'cp3-11', type: 'def', term: 'Emergency lights',
      q: '¿Qué significa «emergency lights»?',
      a: 'Luces de emergencia' },
    { id: 'cp3-fire', unit: 'cp3-11', type: 'def', term: 'Fire',
      q: '¿Qué significa «fire»?',
      a: 'Fuego (incendio)' },
    { id: 'cp3-forced-landing', unit: 'cp3-11', type: 'def', term: 'Forced landing',
      q: '¿Qué significa «forced landing»?',
      a: 'Aterrizaje forzoso: aterrizar cuanto antes porque no se puede seguir volando' },
    { id: 'cp3-inclement', unit: 'cp3-11', type: 'def', term: 'Inclement',
      q: '¿Qué significa «inclement»?',
      a: 'Inclemente (malo)',
      note: 'Ej.: “inclement weather” = mal tiempo.' },
    { id: 'cp3-megaphone', unit: 'cp3-11', type: 'def', term: 'Megaphone',
      q: '¿Qué significa «megaphone»?',
      a: 'Megáfono' },
    { id: 'cp3-precautionary-landing', unit: 'cp3-11', type: 'def', term: 'Precautionary landing',
      q: '¿Qué significa «precautionary landing»?',
      a: 'Aterrizaje preventivo: aterrizar antes de que un problema empeore' },
    { id: 'cp3-slide', unit: 'cp3-11', type: 'def', term: 'Slide',
      q: '¿Qué significa «slide»?',
      a: 'Tobogán (de evacuación)' },
    { id: 'cp3-smoke', unit: 'cp3-11', type: 'def', term: 'Smoke',
      q: '¿Qué significa «smoke»?',
      a: 'Humo' },
    { id: 'cp3-turbulent', unit: 'cp3-11', type: 'def', term: 'Turbulent',
      q: '¿Qué significa «turbulent»?',
      a: 'Turbulento (con turbulencia)',
      note: '«Turbulence» es el sustantivo; «turbulent», el adjetivo.' },
    { id: 'cp3-11-say', unit: 'cp3-11', type: 'num',
      q: 'Un pasajero pregunta qué hacer si hay humo en la cabina. ¿Qué consejo le das?',
      a: 'Stay low and cover your nose and mouth.',
      options: ['Stay low and cover your nose and mouth.', 'Stand up high, where the air is cleaner.', 'Open the window to let the smoke out.', 'Run to the back and wait there.'],
      say: 'Stay low and cover your nose and mouth.',
      note: 'El humo sube: cerca del suelo el aire es más respirable.' },
    { id: 'cp3-11-pairs', unit: 'cp3-11', type: 'match',
      q: 'Giving advice: aconsejar',
      pairs: [['You should…', 'Debería…'],
              ['If I were you…', 'Yo que usted…'],
              ['It’s a good idea to…', 'Es buena idea…'],
              ['Try not to…', 'Intente no…']] },

    /* ───────────── 12 · Medical Emergencies ───────────── */
    { id: 'cp3-airway-obstruction', unit: 'cp3-12', type: 'def', term: 'Airway obstruction',
      q: '¿Qué significa «airway obstruction»?',
      a: 'Obstrucción de la vía aérea' },
    { id: 'cp3-allergic-reaction', unit: 'cp3-12', type: 'def', term: 'Allergic reaction',
      q: '¿Qué significa «allergic reaction»?',
      a: 'Reacción alérgica' },
    { id: 'cp3-automatic-external-defibrillator-aed', unit: 'cp3-12', type: 'def', term: 'Automatic external defibrillator (AED)',
      q: '¿Qué significa «automatic external defibrillator (AED)»?',
      a: 'Desfibrilador externo automático (DEA)',
      say: 'Automatic external defibrillator' },
    { id: 'cp3-biohazard-kit', unit: 'cp3-12', type: 'def', term: 'Biohazard kit',
      q: '¿Qué significa «biohazard kit»?',
      a: 'Kit de riesgo biológico: para limpiar sangre, vómito u otros fluidos' },
    { id: 'cp3-cardiac-arrest', unit: 'cp3-12', type: 'def', term: 'Cardiac arrest',
      q: '¿Qué significa «cardiac arrest»?',
      a: 'Paro cardíaco',
      note: 'No es lo mismo que un infarto: en el paro, el corazón deja de bombear.' },
    { id: 'cp3-choke', unit: 'cp3-12', type: 'def', term: 'Choke',
      q: '¿Qué significa «choke»?',
      a: 'Atragantarse' },
    { id: 'cp3-cpr', unit: 'cp3-12', type: 'def', term: 'CPR',
      q: '¿Qué significa «CPR»?',
      a: 'RCP (reanimación cardiopulmonar)',
      note: 'De «cardiopulmonary resuscitation».', say: 'C P R' },
    { id: 'cp3-epipen', unit: 'cp3-12', type: 'def', term: 'EpiPen',
      q: '¿Qué significa «EpiPen»?',
      a: 'EpiPen: autoinyector de adrenalina para alergias graves' },
    { id: 'cp3-heart-attack', unit: 'cp3-12', type: 'def', term: 'Heart attack',
      q: '¿Qué significa «heart attack»?',
      a: 'Infarto (ataque al corazón)' },
    { id: 'cp3-heimlich-maneuver', unit: 'cp3-12', type: 'def', term: 'Heimlich maneuver',
      q: '¿Qué significa «Heimlich maneuver»?',
      a: 'Maniobra de Heimlich' },
    { id: 'cp3-medical-emergency', unit: 'cp3-12', type: 'def', term: 'Medical emergency',
      q: '¿Qué significa «medical emergency»?',
      a: 'Emergencia médica' },
    { id: 'cp3-stroke', unit: 'cp3-12', type: 'def', term: 'Stroke',
      q: '¿Qué significa «stroke»?',
      a: 'Derrame cerebral (ictus)',
      note: 'Señales: cara caída, debilidad en un brazo y habla extraña (regla FAST).' },
    { id: 'cp3-12-say', unit: 'cp3-12', type: 'num',
      q: 'Un pasajero está pálido y sudando. ¿Cómo expresas tu preocupación?',
      a: 'Excuse me, sir, are you feeling all right? You look very pale.',
      options: ['Excuse me, sir, are you feeling all right? You look very pale.', 'Excuse me, sir, are you feeling right? You see very pale.', 'Excuse me, sir, you feel good? You are very white.', 'Sir, what passes to you? You look pale.'],
      say: 'Excuse me, sir, are you feeling all right? You look very pale.',
      note: '«Look» describe el aspecto: «You look pale». «¿Qué le pasa?» es «What’s wrong?», nunca «What passes?».' },
    { id: 'cp3-12-pairs', unit: 'cp3-12', type: 'match',
      q: 'Expressing concern: expresar preocupación',
      pairs: [['I’m worried about…', 'Me preocupa…'],
              ['Are you feeling all right?', '¿Se siente bien?'],
              ['Is something wrong?', '¿Le pasa algo?'],
              ['I don’t like the look of…', 'No me gusta el aspecto de…']] },

    /* ───────────── 13 · First Aid ───────────── */
    { id: 'cp3-apply', unit: 'cp3-13', type: 'def', term: 'Apply',
      q: '¿Qué significa «apply»?',
      a: 'Aplicar (poner)',
      note: 'Ej.: “Apply pressure to the wound.”' },
    { id: 'cp3-bandage', unit: 'cp3-13', type: 'def', term: 'Bandage',
      q: '¿Qué significa «bandage»?',
      a: 'Venda (vendaje); vendar' },
    { id: 'cp3-blister', unit: 'cp3-13', type: 'def', term: 'Blister',
      q: '¿Qué significa «blister»?',
      a: 'Ampolla' },
    { id: 'cp3-burn', unit: 'cp3-13', type: 'def', term: 'Burn',
      q: '¿Qué significa «burn»?',
      a: 'Quemadura; quemar' },
    { id: 'cp3-contusion', unit: 'cp3-13', type: 'def', term: 'Contusion',
      q: '¿Qué significa «contusion»?',
      a: 'Contusión (moretón)' },
    { id: 'cp3-cut', unit: 'cp3-13', type: 'def', term: 'Cut',
      q: '¿Qué significa «cut»?',
      a: 'Corte (cortadura)' },
    { id: 'cp3-first-aid-kit', unit: 'cp3-13', type: 'def', term: 'First-aid kit',
      q: '¿Qué significa «first-aid kit»?',
      a: 'Botiquín de primeros auxilios' },
    { id: 'cp3-fracture', unit: 'cp3-13', type: 'def', term: 'Fracture',
      q: '¿Qué significa «fracture»?',
      a: 'Fractura' },
    { id: 'cp3-laceration', unit: 'cp3-13', type: 'def', term: 'Laceration',
      q: '¿Qué significa «laceration»?',
      a: 'Laceración: corte profundo e irregular' },
    { id: 'cp3-latex-glove', unit: 'cp3-13', type: 'def', term: 'Latex glove',
      q: '¿Qué significa «latex glove»?',
      a: 'Guante de látex',
      note: 'Póntelo siempre antes de tocar sangre.' },
    { id: 'cp3-pressure', unit: 'cp3-13', type: 'def', term: 'Pressure',
      q: '¿Qué significa «pressure»?',
      a: 'Presión' },
    { id: 'cp3-scrape', unit: 'cp3-13', type: 'def', term: 'Scrape',
      q: '¿Qué significa «scrape»?',
      a: 'Raspón (raspadura)' },
    { id: 'cp3-splint', unit: 'cp3-13', type: 'def', term: 'Splint',
      q: '¿Qué significa «splint»?',
      a: 'Férula: tablilla para inmovilizar' },
    { id: 'cp3-sprain', unit: 'cp3-13', type: 'def', term: 'Sprain',
      q: '¿Qué significa «sprain»?',
      a: 'Esguince (torcedura)' },
    { id: 'cp3-treat', unit: 'cp3-13', type: 'def', term: 'Treat',
      q: '¿Qué significa «treat»?',
      a: 'Tratar, atender (a un herido)',
      note: 'También es «invitar»: “It’s my treat.”' },
    { id: 'cp3-wound', unit: 'cp3-13', type: 'def', term: 'Wound',
      q: '¿Qué significa «wound»?',
      a: 'Herida',
      note: 'Se pronuncia “wuund”; no confundir con «wound» (enrollado), que suena “waund”.' },
    { id: 'cp3-13-say', unit: 'cp3-13', type: 'num',
      q: 'Informas al sobrecargo del estado de un pasajero que se cayó. ¿Qué frase es correcta?',
      a: 'He has a small cut on his forehead, but he’s conscious.',
      options: ['He has a small cut on his forehead, but he’s conscious.', 'He has a small cut in his front, but he is conscient.', 'He is a small cut on the forehead, but conscious.', 'He has a cut small on his forehead, but he’s conscious.'],
      say: 'He has a small cut on his forehead, but he’s conscious.',
      note: '«Consciente» es «conscious», no «conscient». Y la frente es «forehead».' },
    { id: 'cp3-13-pairs', unit: 'cp3-13', type: 'match',
      q: 'Describing condition: el estado de un herido',
      pairs: [['He’s conscious', 'Está consciente'],
              ['She’s breathing normally', 'Respira con normalidad'],
              ['It’s bleeding a lot', 'Sangra mucho'],
              ['He feels dizzy', 'Está mareado']] },

    /* ───────────── 14 · Aircraft Security 1 ───────────── */
    { id: 'cp3-abusive', unit: 'cp3-14', type: 'def', term: 'Abusive',
      q: '¿Qué significa «abusive»?',
      a: 'Insultante, ofensivo' },
    { id: 'cp3-aggressive', unit: 'cp3-14', type: 'def', term: 'Aggressive',
      q: '¿Qué significa «aggressive»?',
      a: 'Agresivo' },
    { id: 'cp3-arrest', unit: 'cp3-14', type: 'def', term: 'Arrest',
      q: '¿Qué significa «arrest»?',
      a: 'Arrestar (detener); arresto' },
    { id: 'cp3-assault', unit: 'cp3-14', type: 'def', term: 'Assault',
      q: '¿Qué significa «assault»?',
      a: 'Agresión (ataque físico); agredir' },
    { id: 'cp3-authorities', unit: 'cp3-14', type: 'def', term: 'Authorities',
      q: '¿Qué significa «authorities»?',
      a: 'Autoridades' },
    { id: 'cp3-custody', unit: 'cp3-14', type: 'def', term: 'Custody',
      q: '¿Qué significa «custody»?',
      a: 'Custodia (detención)',
      note: 'Ej.: “The police took the passenger into custody.”' },
    { id: 'cp3-divert', unit: 'cp3-14', type: 'def', term: 'Divert',
      q: '¿Qué significa «divert»?',
      a: 'Desviar el vuelo a otro aeropuerto' },
    { id: 'cp3-drunk', unit: 'cp3-14', type: 'def', term: 'Drunk',
      q: '¿Qué significa «drunk»?',
      a: 'Borracho (ebrio)',
      syn: ['Intoxicated'] },
    { id: 'cp3-follow', unit: 'cp3-14', type: 'def', term: 'Follow',
      q: '¿Qué significa «follow»?',
      a: 'Seguir; cumplir (instrucciones)',
      note: 'Ej.: “Passengers must follow crew instructions.”' },
    { id: 'cp3-intimidate', unit: 'cp3-14', type: 'def', term: 'Intimidate',
      q: '¿Qué significa «intimidate»?',
      a: 'Intimidar' },
    { id: 'cp3-intoxicated', unit: 'cp3-14', type: 'def', term: 'Intoxicated',
      q: '¿Qué significa «intoxicated»?',
      a: 'Bajo los efectos del alcohol o de drogas',
      note: 'Falso amigo: no es «intoxicado» por comida en mal estado («food poisoning»).', syn: ['Drunk'] },
    { id: 'cp3-jetway', unit: 'cp3-14', type: 'def', term: 'Jetway',
      q: '¿Qué significa «jetway»?',
      a: 'Pasarela de embarque (manga)' },
    { id: 'cp3-notify', unit: 'cp3-14', type: 'def', term: 'Notify',
      q: '¿Qué significa «notify»?',
      a: 'Notificar, avisar' },
    { id: 'cp3-refuse', unit: 'cp3-14', type: 'def', term: 'Refuse',
      q: '¿Qué significa «refuse»?',
      a: 'Negarse; rechazar',
      note: 'Ej.: “We may refuse boarding to intoxicated passengers.”' },
    { id: 'cp3-security', unit: 'cp3-14', type: 'def', term: 'Security',
      q: '¿Qué significa «security»?',
      a: 'Seguridad frente a actos ilícitos',
      note: '«Security» protege de delitos o ataques; «safety», de accidentes.' },
    { id: 'cp3-14-steps', unit: 'cp3-14', type: 'order',
      q: 'Ordena la respuesta ante un pasajero conflictivo (pauta típica)',
      steps: ['Ask the passenger politely to stop',
              'Give a firm verbal warning',
              'Inform the captain',
              'Restrain the passenger if safety is at risk',
              'Hand the passenger over to the authorities on arrival'] },
    { id: 'cp3-14-say', unit: 'cp3-14', type: 'num',
      q: 'Tras un incidente con un pasajero ebrio, los demás están nerviosos. ¿Qué dices?',
      a: 'The situation is under control. There’s nothing to worry about.',
      options: ['The situation is under control. There’s nothing to worry about.', 'The situation is under control. There is nothing for worry.', 'The situation is in control. Nothing to worry.', 'Is under control. Don’t be worry.'],
      say: 'The situation is under control. There’s nothing to worry about.',
      note: '«No se preocupe» es «Don’t worry», no «Don’t be worry».' },
    { id: 'cp3-14-pairs', unit: 'cp3-14', type: 'match',
      q: 'Providing reassurance: tranquilizar',
      pairs: [['You’re safe now', 'Ya está a salvo'],
              ['The police are on their way', 'La policía ya viene'],
              ['We’ve dealt with it', 'Ya lo hemos resuelto'],
              ['There’s no need to be alarmed', 'No hay motivo para alarmarse']] },

    /* ───────────── 15 · Aircraft Security 2 ───────────── */
    { id: 'cp3-air-marshal', unit: 'cp3-15', type: 'def', term: 'Air marshal',
      q: '¿Qué significa «air marshal»?',
      a: 'Agente de seguridad a bordo (policía aérea encubierta)' },
    { id: 'cp3-alert', unit: 'cp3-15', type: 'def', term: 'Alert',
      q: '¿Qué significa «alert»?',
      a: 'Alerta; alertar (avisar)' },
    { id: 'cp3-assume', unit: 'cp3-15', type: 'def', term: 'Assume',
      q: '¿Qué significa «assume»?',
      a: 'Suponer (dar por hecho)',
      note: 'Ej.: “Never assume a bag is harmless.”' },
    { id: 'cp3-force', unit: 'cp3-15', type: 'def', term: 'Force',
      q: '¿Qué significa «force»?',
      a: 'Fuerza; forzar',
      note: 'Ej.: “Use only the force necessary to restrain the passenger.”' },
    { id: 'cp3-handcuff', unit: 'cp3-15', type: 'def', term: 'Handcuff',
      q: '¿Qué significa «handcuff»?',
      a: 'Esposas; esposar',
      note: 'Como sustantivo suele ir en plural: «handcuffs».' },
    { id: 'cp3-heightened', unit: 'cp3-15', type: 'def', term: 'Heightened',
      q: '¿Qué significa «heightened»?',
      a: 'Reforzado (aumentado)',
      note: 'Ej.: “heightened security” = seguridad reforzada.' },
    { id: 'cp3-in-possession-of', unit: 'cp3-15', type: 'def', term: 'In possession of',
      q: '¿Qué significa «in possession of»?',
      a: 'En posesión de (que lleva consigo)' },
    { id: 'cp3-restrain', unit: 'cp3-15', type: 'def', term: 'Restrain',
      q: '¿Qué significa «restrain»?',
      a: 'Inmovilizar (sujetar a alguien)' },
    { id: 'cp3-self-defense', unit: 'cp3-15', type: 'def', term: 'Self-defense',
      q: '¿Qué significa «self-defense»?',
      a: 'Defensa personal' },
    { id: 'cp3-suspect', unit: 'cp3-15', type: 'def', term: 'Suspect',
      q: '¿Qué significa «suspect»?',
      a: 'Sospechoso (la persona); sospechar',
      note: 'Ej.: “The suspect was handcuffed.”' },
    { id: 'cp3-suspicious', unit: 'cp3-15', type: 'def', term: 'Suspicious',
      q: '¿Qué significa «suspicious»?',
      a: 'Que levanta sospechas (raro, sospechoso)',
      note: 'Ej.: “a suspicious bag”.' },
    { id: 'cp3-terrorism', unit: 'cp3-15', type: 'def', term: 'Terrorism',
      q: '¿Qué significa «terrorism»?',
      a: 'Terrorismo' },
    { id: 'cp3-weapon', unit: 'cp3-15', type: 'def', term: 'Weapon',
      q: '¿Qué significa «weapon»?',
      a: 'Arma',
      note: 'Se pronuncia “UE-pon”.' },
    { id: 'cp3-ziptie', unit: 'cp3-15', type: 'def', term: 'Ziptie',
      q: '¿Qué significa «ziptie»?',
      a: 'Brida (cincho de plástico)',
      note: 'A bordo se usan como esposas de plástico.' },
    { id: 'cp3-15-say', unit: 'cp3-15', type: 'num',
      q: 'Te eligieron para el curso avanzado de seguridad. ¿Cómo muestras entusiasmo?',
      a: 'That’s fantastic! I can’t wait to start.',
      options: ['That’s fantastic! I can’t wait to start.', 'That’s fantastic! I can’t wait for start.', 'Is fantastic! I can’t wait to start.', 'That’s fantastic! I don’t can wait to start.'],
      say: 'That’s fantastic! I can’t wait to start.',
      note: '«I can’t wait to…» = «me muero de ganas de…».' },
    { id: 'cp3-15-pairs', unit: 'cp3-15', type: 'match',
      q: 'Expressing enthusiasm: mostrar entusiasmo',
      pairs: [['That’s great news!', '¡Qué buena noticia!'],
              ['I can’t wait!', '¡Qué ganas!'],
              ['I’m really looking forward to it', 'Tengo muchas ganas'],
              ['How exciting!', '¡Qué emoción!']] }
  ]
};
